import React,{useEffect,useMemo,useRef,useState} from 'react';
import {UploadCloud,Images,Search,Copy,ExternalLink,Trash2,Loader2,FileText,Save,X} from 'lucide-react';
import {MediaItem,MEDIA_ACCEPT,listMedia,uploadMediaBatch,copyMediaUrl} from '../../lib/mediaApi';
import {adminApi} from '../../lib/adminApi';
export const AdminMediaLibrary:React.FC<{onShowToast:(message:string)=>void}>=({onShowToast})=>{
 const [items,setItems]=useState<MediaItem[]>([]),[cursor,setCursor]=useState<string|null>(null),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[loading,setLoading]=useState(false),[uploading,setUploading]=useState(false),[progress,setProgress]=useState({done:0,total:0}),[errors,setErrors]=useState<string[]>([]),[drag,setDrag]=useState(false),[editing,setEditing]=useState<MediaItem|null>(null),[saving,setSaving]=useState(false);
 const filesRef=useRef<HTMLInputElement>(null),uploadLock=useRef(false);
 const load=async(next?:string)=>{setLoading(true);try{const d=await listMedia(next);setItems(prev=>next?[...prev,...d.items.filter(x=>!prev.some(p=>p.key===x.key))]:d.items);setCursor(d.cursor)}catch(e){onShowToast(e instanceof Error?e.message:'Không tải được thư viện.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[]);
 const upload=async(files:File[])=>{if(!files.length||uploadLock.current)return;uploadLock.current=true;setUploading(true);setErrors([]);setProgress({done:0,total:files.length});try{const results=await uploadMediaBatch(files,(done,total)=>setProgress({done,total}));const successful=results.filter(x=>x.item);setErrors(results.filter(x=>x.error).map(x=>x.file.name+': '+x.error));onShowToast(`Đã tải ${successful.length}/${files.length} tệp.`);await load()}catch(e){setErrors([e instanceof Error?e.message:'Không tải được tệp.'])}finally{setUploading(false);uploadLock.current=false;if(filesRef.current)filesRef.current.value=''}};
 const remove=async(item:MediaItem)=>{if(!confirm(`Xóa tệp “${item.name}”? Tệp đang dùng trong nội dung sẽ được giữ lại.`))return;try{await adminApi('/api/media',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({key:item.key})});setItems(prev=>prev.filter(x=>x.key!==item.key));onShowToast('Đã xóa tệp.')}catch(e){onShowToast(e instanceof Error?e.message:'Không xóa được tệp.')}};
 const save=async()=>{if(!editing)return;setSaving(true);try{await adminApi('/api/media',{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({key:editing.key,alt:editing.alt||'',caption:editing.caption||''})});setItems(prev=>prev.map(x=>x.key===editing.key?editing:x));setEditing(null);onShowToast('Đã lưu mô tả và chú thích ảnh.')}catch(e){onShowToast(e instanceof Error?e.message:'Không lưu được mô tả.')}finally{setSaving(false)}};
 const copy=async(item:MediaItem)=>{try{await copyMediaUrl(item.url);onShowToast('Đã sao chép liên kết.')}catch{onShowToast('Không sao chép được. Mở tệp và lấy liên kết trên thanh địa chỉ.')}};
 const visible=useMemo(()=>items.filter(x=>(filter==='all'||(filter==='images'?x.type.startsWith('image/'):x.type==='application/pdf'))&&(x.name+' '+(x.alt||'')+' '+(x.caption||'')).toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi'))),[items,query,filter]);
 return <div className="space-y-6"><header className="flex flex-wrap justify-between gap-4 items-end"><div><p className="text-[10px] font-bold uppercase tracking-widest text-sky-700">Nội dung / Thư viện</p><h2 className="text-2xl font-bold text-slate-900 mt-2">Hình ảnh & tài liệu</h2><p className="text-sm text-slate-500 mt-2">Tải một lần, sử dụng ở nhiều trang. Quản lý banner, logo, ảnh hoạt động và tài liệu.</p></div><button type="button" onClick={()=>void load()} disabled={loading||uploading} className="border rounded-xl px-4 py-2 text-xs font-semibold">Làm mới thư viện</button></header>
 <div onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);void upload(Array.from(e.dataTransfer.files))}} className={`rounded-2xl border-2 border-dashed p-7 text-center ${drag?'border-sky-500 bg-sky-100':'border-slate-300 bg-slate-50'}`}><UploadCloud size={30} className="mx-auto text-sky-700 mb-3"/><h3 className="font-bold">Kéo thả ảnh hoặc tài liệu vào đây</h3><p className="text-xs text-slate-500 mt-2 mb-4">Tối đa 50 tệp mỗi lượt · 20 MB/tệp · JPG, PNG, WebP, GIF, AVIF, SVG, PDF</p><input ref={filesRef} type="file" multiple accept={MEDIA_ACCEPT} className="hidden" onChange={e=>void upload(Array.from(e.target.files||[]))}/><button type="button" disabled={uploading} onClick={()=>filesRef.current?.click()} className="rounded-xl bg-sky-700 px-5 py-2.5 font-semibold text-sm text-white disabled:opacity-50">{uploading?'Đang tải…':'Chọn nhiều tệp'}</button>{uploading&&<div role="status" className="max-w-md mx-auto mt-4"><p className="text-xs mb-2">Đã xử lý {progress.done}/{progress.total} tệp</p><progress className="w-full" value={progress.done} max={progress.total||1}/></div>}</div>
 {errors.length>0&&<div role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-4 text-xs text-rose-700"><b>Các tệp chưa tải được:</b><ul className="list-disc pl-5 mt-2">{errors.map((error,i)=><li key={i}>{error}</li>)}</ul></div>}
 <div className="flex flex-wrap gap-3"><label className="flex gap-2 items-center border rounded-xl px-3 py-2.5 flex-1 min-w-[180px]"><Search size={16}/><input aria-label="Tìm tệp" className="outline-none flex-1 text-sm" placeholder="Tìm tên, mô tả hoặc chú thích…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Lọc loại tệp" value={filter} onChange={e=>setFilter(e.target.value)} className="border rounded-xl px-3 text-xs"><option value="all">Tất cả tệp</option><option value="images">Hình ảnh</option><option value="documents">Tài liệu PDF</option></select></div>
 <p className="text-xs text-slate-500">{visible.length} tệp phù hợp trong {items.length} tệp đã tải{cursor?' · Còn tệp ở trang tiếp theo':''}</p>
 <div className="grid grid-cols-2 md:grid-cols-3 xl:grid-cols-4 gap-4">{visible.map(item=><article key={item.key} className="border rounded-2xl bg-white overflow-hidden"><button type="button" onClick={()=>setEditing({...item})} className="block w-full aspect-[4/3] bg-slate-50 p-3" aria-label={`Xem và chỉnh mô tả ${item.name}`}>{item.type.startsWith('image/')?<img src={item.url} alt={item.alt||item.name} loading="lazy" className="w-full h-full object-contain"/>:<FileText size={38} className="mx-auto text-sky-700"/>}</button><div className="p-3"><h3 className="font-semibold text-xs truncate" title={item.name}>{item.name}</h3><p className="text-[10px] text-slate-500 mt-1">{(item.size/1024/1024).toFixed(2)} MB · {item.uploaded?new Date(item.uploaded).toLocaleDateString('vi-VN'):''}</p><div className="flex gap-2 mt-3"><button type="button" onClick={()=>void copy(item)} aria-label="Sao chép liên kết" className="border rounded-lg p-2"><Copy size={14}/></button><a href={item.url} target="_blank" rel="noopener noreferrer" aria-label="Mở tệp" className="border rounded-lg p-2"><ExternalLink size={14}/></a><button type="button" onClick={()=>void remove(item)} aria-label="Xóa tệp" className="ml-auto border rounded-lg p-2 text-rose-700"><Trash2 size={14}/></button></div></div></article>)}</div>
 {loading&&<p className="flex gap-2 justify-center text-sm"><Loader2 size={18} className="animate-spin"/>Đang tải thư viện…</p>}{!loading&&!visible.length&&<div className="text-center border rounded-2xl p-10 text-slate-500"><Images className="mx-auto mb-3"/>Chưa có tệp phù hợp.</div>}{cursor&&<button type="button" disabled={loading} onClick={()=>void load(cursor)} className="border rounded-xl px-5 py-2 text-sm">Tải thêm tệp</button>}
 {editing&&<div className="fixed inset-0 z-[200] bg-slate-950/60 p-4 flex items-center justify-center"><section role="dialog" aria-modal="true" aria-label="Chi tiết tệp" className="bg-white rounded-2xl w-full max-w-3xl max-h-[90vh] overflow-auto p-5"><header className="flex justify-between mb-5"><h3 className="font-bold">Chi tiết tệp</h3><button type="button" aria-label="Đóng" onClick={()=>setEditing(null)}><X/></button></header><div className="grid md:grid-cols-2 gap-6"><div className="bg-slate-50 rounded-xl p-4">{editing.type.startsWith('image/')?<img src={editing.url} alt={editing.alt||editing.name} className="max-h-80 w-full object-contain"/>:<FileText className="mx-auto" size={40}/>}</div><div className="space-y-4"><p className="text-xs break-all font-semibold">{editing.name}</p><label className="block text-xs font-semibold">Mô tả thay thế (alt)<input value={editing.alt||''} maxLength={500} onChange={e=>setEditing({...editing,alt:e.target.value})} className="block border rounded-lg p-3 mt-2 w-full"/></label><label className="block text-xs font-semibold">Chú thích<textarea rows={3} value={editing.caption||''} maxLength={2000} onChange={e=>setEditing({...editing,caption:e.target.value})} className="block border rounded-lg p-3 mt-2 w-full"/></label><p className="text-[11px] text-slate-500">Mô tả này dùng để tìm kiếm trong thư viện. Nội dung thay thế trên từng trang lấy theo trường mô tả của trang.</p><button type="button" disabled={saving} onClick={()=>void save()} className="bg-sky-700 text-white rounded-xl p-3 text-xs inline-flex gap-2 items-center"><Save size={15}/>{saving?'Đang lưu…':'Lưu thông tin'}</button></div></div></section></div>}
 </div>;
};
