import React,{useEffect,useMemo,useState} from 'react';
import {Plus,Trash2,Save,Search,Loader2,X,Upload,ShieldCheck,QrCode,ExternalLink,History} from 'lucide-react';
import {adminApi} from '../../lib/adminApi';

type Row={id:string;kind:string;title:string;subtitle?:string;status?:string;note?:string;bankId?:string;bankName?:string;bankAccount?:string;accountHolder?:string;transferMemo?:string;vietQrUrl?:string;receiptUrl?:string;receivedDate?:string;amount?:string;contributionType?:string;public?:boolean;partnerType?:string;contactName?:string;contactEmail?:string;contactPhone?:string;website?:string;startDate?:string;endDate?:string;certificateCode?:string;recipientName?:string;recipientEmail?:string;programName?:string;issueDate?:string;certificateUrl?:string;verificationStatus?:string;actor?:string;action?:string;target?:string;eventTime?:string};
const labels:Record<string,string>={partners:'Đối tác & Đơn vị đồng hành',contributions:'Tài trợ, Đóng góp & Quyên góp',certificates:'Giấy chứng nhận trung tâm',logs:'Nhật ký hoạt động'};
const inputClass='w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-sky-400 focus:ring-4 focus:ring-sky-100';

export const AdminRecordsManager:React.FC<{kind:string,onShowToast:(m:string)=>void}>=({kind,onShowToast})=>{
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[edit,setEdit]=useState<Row|null>(null),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false);
 const load=async()=>{setLoading(true);try{const d=await adminApi(`/api/admin-records?kind=${encodeURIComponent(kind)}`);setRows(d.items||[])}catch(e:any){onShowToast(e.message||'Không thể tải dữ liệu.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[kind]);
 useEffect(()=>{if(!edit)return;const prev=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=prev}},[edit]);
 const filtered=useMemo(()=>rows.filter(r=>(`${r.title} ${r.subtitle||''} ${r.status||''}`).toLowerCase().includes(q.toLowerCase())),[rows,q]);
 const save=async()=>{if(!edit?.title.trim())return onShowToast('Vui lòng nhập tên / tiêu đề.');setSaving(true);try{await adminApi('/api/admin-records',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(edit)});setEdit(null);await load();onShowToast('Đã lưu thay đổi.')}catch(e:any){onShowToast(e.message||'Không thể lưu.')}finally{setSaving(false)}};
 const del=async(id:string)=>{if(!confirm('Xóa bản ghi này? Thao tác sẽ được ghi vào nhật ký quản trị.'))return;try{await adminApi('/api/admin-records',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});await load();onShowToast('Đã xóa bản ghi.')}catch(e:any){onShowToast(e.message||'Không thể xóa.')}};
 const set=(key:keyof Row,value:any)=>setEdit(v=>v?{...v,[key]:value}:v);
 const Field=({k,label,type='text',span=false,placeholder}:{k:keyof Row,label:string,type?:string,span?:boolean,placeholder?:string})=><label className={span?'sm:col-span-2':''}><span className="mb-1.5 block text-xs font-bold text-slate-600">{label}</span><input type={type} value={String(edit?.[k]??'')} onChange={e=>set(k,e.target.value)} className={inputClass} placeholder={placeholder}/></label>;
 const generateQr=()=>{if(!edit)return;const bank=(edit.bankId||'').trim(),account=(edit.bankAccount||'').replace(/[^0-9A-Za-z]/g,'');if(!bank||!account)return onShowToast('Nhập Mã ngân hàng VietQR và số tài khoản trước.');const p=new URLSearchParams();if(edit.accountHolder?.trim())p.set('accountName',edit.accountHolder.trim());if(edit.transferMemo?.trim())p.set('addInfo',edit.transferMemo.trim().slice(0,50));const numeric=String(edit.amount||'').replace(/[^0-9]/g,'');if(numeric)p.set('amount',numeric);set('vietQrUrl',`https://img.vietqr.io/image/${encodeURIComponent(bank)}-${encodeURIComponent(account)}-compact2.png?${p}`);onShowToast('Đã tạo QR từ thông tin ngân hàng.');};
 const uploadReceipt=async(file?:File)=>{if(!file)return;setUploading(true);try{const fd=new FormData();fd.append('file',file);const d=await adminApi('/api/media/upload',{method:'POST',body:fd});set('receiptUrl',d.url);onShowToast('Đã tải chứng từ lên hệ thống.')}catch(e:any){onShowToast(e.message||'Không thể tải chứng từ.')}finally{setUploading(false)}};
 const newRow=()=>setEdit({id:`${kind}-${crypto.randomUUID?.()||Date.now()}`,kind,title:'',status:'Bản nháp',public:false,receivedDate:kind==='contributions'?new Date().toISOString().slice(0,10):undefined});

 if(kind==='logs')return <div className="space-y-4"><div><h2 className="text-xl font-black">{labels[kind]}</h2><p className="mt-1 text-xs text-slate-500">Nhật ký được hệ thống tự ghi khi dữ liệu quản trị thay đổi; không nhập thủ công.</p></div><div className="overflow-hidden rounded-2xl border bg-white"><div className="flex items-center gap-2 border-b p-3"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full outline-none text-sm" placeholder="Tìm trong nhật ký..."/></div>{loading?<div className="p-10 flex justify-center"><Loader2 className="animate-spin"/></div>:filtered.length===0?<div className="p-10 text-center text-sm text-slate-500">Chưa có sự kiện quản trị.</div>:<div className="divide-y">{filtered.map(r=><div key={r.id} className="p-4 flex gap-3"><History size={17} className="mt-0.5 text-slate-400"/><div><div className="font-bold text-sm">{r.title}</div><div className="mt-1 text-xs text-slate-500">{r.subtitle}</div></div></div>)}</div>}</div></div>;

 return <div className="space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-black">{labels[kind]||'Quản lý dữ liệu'}</h2><p className="text-xs text-slate-500 mt-1">Dữ liệu lưu trên máy chủ. Chỉ nội dung được duyệt công khai mới nên xuất hiện trên website.</p></div><button onClick={newRow} className="px-4 py-2 bg-[#0F2B5B] text-white rounded-xl text-sm font-bold flex items-center gap-2"><Plus size={16}/>Thêm mới</button></div><div className="bg-white border rounded-2xl overflow-hidden"><div className="p-3 border-b flex items-center gap-2"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full outline-none text-sm" placeholder="Tìm kiếm..."/></div>{loading?<div className="p-10 flex justify-center"><Loader2 className="animate-spin"/></div>:filtered.length===0?<div className="p-10 text-center text-sm text-slate-500">Chưa có dữ liệu.</div>:<div className="divide-y">{filtered.map(r=><div key={r.id} className="p-4 flex items-center gap-3"><div className="min-w-0 flex-1"><button onClick={()=>setEdit(r)} className="font-bold text-left hover:text-sky-700">{r.title}</button><div className="text-xs text-slate-500 mt-1 truncate">{r.subtitle}</div></div><span className="hidden sm:inline rounded-full bg-slate-100 px-2.5 py-1 text-[11px] font-bold">{r.status}</span><button aria-label="Xóa" onClick={()=>void del(r.id)} className="p-2 text-rose-600 hover:bg-rose-50 rounded-lg"><Trash2 size={16}/></button></div>)}</div>}</div>
 {edit&&<div className="fixed inset-0 z-[100] bg-slate-950/55 backdrop-blur-[2px] p-2 sm:p-5 flex items-center justify-center" onMouseDown={e=>{if(e.currentTarget===e.target)setEdit(null)}}><div role="dialog" aria-modal="true" className="flex w-full max-w-4xl max-h-[calc(100dvh-16px)] sm:max-h-[calc(100dvh-40px)] flex-col overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-2xl">
  <header className="shrink-0 flex items-start justify-between gap-4 border-b px-5 py-4 sm:px-6"><div><h3 className="text-lg font-black text-slate-900">{edit.title?'Chỉnh sửa':'Thêm mới'} {labels[kind]?.toLowerCase()}</h3><p className="mt-1 text-xs text-slate-500">Thông tin được lưu tập trung và có lịch sử thay đổi.</p></div><button onClick={()=>setEdit(null)} className="rounded-lg p-2 hover:bg-slate-100"><X size={18}/></button></header>
  <div className="min-h-0 flex-1 overflow-y-auto overscroll-contain px-5 py-5 sm:px-6">
   <section className="grid sm:grid-cols-2 gap-4"><Field k="title" label="Tên / Tiêu đề" span/><Field k="subtitle" label="Mô tả / Phân loại"/><label><span className="mb-1.5 block text-xs font-bold text-slate-600">Trạng thái</span><select value={edit.status||'Bản nháp'} onChange={e=>set('status',e.target.value)} className={inputClass}><option>Bản nháp</option><option>Chờ xác minh</option><option>Đã xác minh</option><option>Đã công khai</option><option>Đã đối soát</option><option>Ngừng hiệu lực</option></select></label></section>
   {kind==='contributions'&&<><h4 className="mt-7 mb-3 font-black text-sm">Thông tin tài trợ / đóng góp</h4><section className="grid sm:grid-cols-2 gap-4"><Field k="contributionType" label="Hình thức" placeholder="Tiền mặt, chuyển khoản, hiện vật..."/><Field k="amount" label="Số tiền / giá trị"/><Field k="receivedDate" label="Ngày tiếp nhận" type="date"/></section><h4 className="mt-7 mb-3 font-black text-sm">Thanh toán & QR</h4><section className="grid sm:grid-cols-2 gap-4"><Field k="bankId" label="Mã ngân hàng VietQR" placeholder="VD: TPB, VCB, MB..."/><Field k="bankName" label="Tên ngân hàng"/><Field k="bankAccount" label="Số tài khoản"/><Field k="accountHolder" label="Chủ tài khoản"/><Field k="transferMemo" label="Nội dung chuyển khoản" span/></section><div className="mt-4 rounded-2xl border border-sky-100 bg-sky-50/60 p-4"><div className="flex flex-wrap items-center justify-between gap-3"><div><div className="font-bold text-sm flex items-center gap-2"><QrCode size={17}/>VietQR tự động</div><p className="text-xs text-slate-500 mt-1">QR được tạo từ thông tin ngân hàng; không cần dán URL thủ công.</p></div><button type="button" onClick={generateQr} className="rounded-xl bg-sky-700 px-4 py-2 text-xs font-bold text-white">Tạo / cập nhật QR</button></div>{edit.vietQrUrl&&<div className="mt-4 flex flex-wrap items-center gap-4"><img src={edit.vietQrUrl} alt="VietQR" className="h-36 w-36 rounded-xl border bg-white object-contain p-2"/><a href={edit.vietQrUrl} target="_blank" rel="noreferrer" className="text-xs font-bold text-sky-700 flex gap-1">Mở QR <ExternalLink size={14}/></a></div>}</div><h4 className="mt-7 mb-3 font-black text-sm">Minh chứng</h4><div className="rounded-2xl border border-dashed border-slate-300 p-4"><label className="flex cursor-pointer items-center justify-center gap-2 rounded-xl bg-slate-50 px-4 py-3 text-sm font-bold hover:bg-slate-100"><Upload size={17}/>{uploading?'Đang tải lên...':'Tải chứng từ / biên nhận'}<input className="hidden" type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif,image/svg+xml,application/pdf" disabled={uploading} onChange={e=>void uploadReceipt(e.target.files?.[0])}/></label>{edit.receiptUrl&&<a href={edit.receiptUrl} target="_blank" rel="noreferrer" className="mt-3 flex items-center gap-1 text-xs font-bold text-sky-700">Xem chứng từ đã tải <ExternalLink size={14}/></a>}</div></>}
   {kind==='partners'&&<section className="mt-6 grid sm:grid-cols-2 gap-4"><Field k="partnerType" label="Loại đối tác / đồng hành"/><Field k="contactName" label="Người liên hệ"/><Field k="contactEmail" label="Email liên hệ" type="email"/><Field k="contactPhone" label="Điện thoại"/><Field k="website" label="Website"/><Field k="startDate" label="Ngày bắt đầu" type="date"/><Field k="endDate" label="Ngày kết thúc" type="date"/></section>}
   {kind==='certificates'&&<section className="mt-6 grid sm:grid-cols-2 gap-4"><Field k="certificateCode" label="Mã giấy chứng nhận"/><Field k="recipientName" label="Người nhận"/><Field k="recipientEmail" label="Email người nhận" type="email"/><Field k="programName" label="Chương trình / hoạt động"/><Field k="issueDate" label="Ngày cấp" type="date"/><Field k="certificateUrl" label="Liên kết file chứng nhận"/><Field k="verificationStatus" label="Trạng thái xác thực"/></section>}
   <label className="mt-6 block"><span className="mb-1.5 block text-xs font-bold text-slate-600">Ghi chú nội bộ</span><textarea value={edit.note||''} onChange={e=>set('note',e.target.value)} rows={4} className={inputClass}/></label>
   <label className="mt-5 flex items-start gap-3 rounded-xl border p-4 text-sm"><input type="checkbox" className="mt-0.5" checked={!!edit.public} onChange={e=>set('public',e.target.checked)}/><span><b>Cho phép sử dụng ở khu vực công khai</b><span className="block text-xs text-slate-500 mt-1">Đánh dấu này không đồng nghĩa dữ liệu đã được xác minh. Chỉ công khai sau khi kiểm tra chứng từ và thông tin liên quan.</span></span></label>
   {kind==='contributions'&&<div className="mt-4 flex gap-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-900"><ShieldCheck size={17} className="shrink-0"/><span>Không tự chuyển sang “Đã xác minh/Đã đối soát” chỉ vì đã tạo QR hoặc tải chứng từ. Trạng thái phải phản ánh việc kiểm tra thực tế.</span></div>}
  </div>
  <footer className="shrink-0 flex justify-end gap-2 border-t bg-white px-5 py-4 sm:px-6"><button onClick={()=>setEdit(null)} className="px-4 py-2 border rounded-xl text-sm font-bold">Hủy</button><button disabled={saving} onClick={()=>void save()} className="px-4 py-2 bg-[#0F2B5B] disabled:opacity-60 text-white rounded-xl text-sm font-bold flex items-center gap-2">{saving?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>}Lưu thay đổi</button></footer>
 </div></div>}</div>;
}
