import React,{useEffect,useMemo,useRef,useState} from 'react';
import {Check,Copy,ExternalLink,Eye,FileText,Loader2,RefreshCw,Search,Trash2,UploadCloud,X} from 'lucide-react';
import { AdminMediaLibrary } from './AdminMediaLibrary';
import { adminApi as api } from '../../lib/adminApi';

type Kind='comments'|'contacts'|'media'|'registrations'|'participants';
const statusLabel:Record<string,string>={pending:'Chờ xử lý',approved:'Đã duyệt',hidden:'Đã ẩn',reviewed:'Đã xem',closed:'Đã đóng',reviewing:'Đang xem xét',accepted:'Đã tiếp nhận',rejected:'Đã từ chối'};
const fmt=(v:any)=>v?new Date(v).toLocaleString('vi-VN'):'';
const safeExternal=(url:string)=>/^https?:\/\//i.test(url||'');

const RemoteRecordsManager:React.FC<{kind:Kind;onShowToast:(m:string)=>void}>=({kind,onShowToast})=>{
 const [items,setItems]=useState<any[]>([]),[loading,setLoading]=useState(false),[q,setQ]=useState(''),[detail,setDetail]=useState<any|null>(null);
 const fileRef=useRef<HTMLInputElement|null>(null);
 const endpoint=kind==='comments'?'/api/comments':kind==='contacts'?'/api/contact':kind==='registrations'?'/api/registrations':kind==='participants'?'/api/registrations?view=participants':'/api/media';
 const load=async()=>{setLoading(true);try{const d=await api(kind==='comments'?'/api/comments?admin=1':endpoint);setItems(Array.isArray(d?.items)?d.items:[])}catch(e:any){onShowToast(e?.message||'Không thể tải dữ liệu.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[kind]);
 useEffect(()=>{if(!detail)return;const old=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=old}},[detail]);
 const filtered=useMemo(()=>items.filter(x=>JSON.stringify(x).toLowerCase().includes(q.trim().toLowerCase())),[items,q]);
 const del=async(x:any)=>{if(kind==='participants'){onShowToast('Người tham gia được tạo từ hồ sơ đã tiếp nhận; quản lý trạng thái tại chương trình.');return} if(!confirm(kind==='media'?'Xóa tệp này khỏi kho Media?':'Xóa vĩnh viễn bản ghi này?'))return;try{await api(endpoint,{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify(kind==='media'?{key:x.key}:{id:x.id})});if(detail&&(detail.id===x.id||detail.key===x.key))setDetail(null);onShowToast('Đã xóa.');void load()}catch(e:any){onShowToast(e?.message||'Không thể xóa.')}};
 const setStatus=async(x:any,status:string)=>{try{await api(endpoint,{method:'PATCH',headers:{'content-type':'application/json'},body:JSON.stringify({id:x.id,status})});setDetail((d:any)=>d&&d.id===x.id?{...d,status}:d);onShowToast('Đã cập nhật trạng thái.');void load()}catch(e:any){onShowToast(e?.message||'Không thể cập nhật.')}};
 const upload=async(file:File)=>{const fd=new FormData();fd.append('file',file);setLoading(true);try{await api('/api/media/upload',{method:'POST',body:fd});onShowToast('Đã tải tệp lên kho Media.');void load()}catch(e:any){onShowToast(e?.message||'Không thể tải tệp.')}finally{setLoading(false);if(fileRef.current)fileRef.current.value=''}};
 const title=kind==='comments'?'Bình luận bài viết':kind==='contacts'?'Liên hệ & đề xuất':kind==='registrations'?'Hồ sơ đăng ký chương trình':kind==='participants'?'Người tham gia chương trình':'Kho Media';
 const subtitle=kind==='comments'?'Duyệt hoặc ẩn phản hồi trước khi hiển thị công khai.':kind==='contacts'?'Theo dõi yêu cầu gửi từ website và trạng thái xử lý.':kind==='registrations'?'Tiếp nhận hồ sơ; khi chọn Đã tiếp nhận, hệ thống tự tạo Người tham gia và gửi email theo mẫu của chương trình.':kind==='participants'?'Danh sách được tạo tự động từ các hồ sơ đã tiếp nhận.':'Tệp dùng chung cho website; tải lên một lần và tái sử dụng.';
 const Status=({x}:{x:any})=><span className="text-[11px] px-2.5 py-1 rounded-full bg-slate-100 font-bold text-slate-600">{statusLabel[x.status]||x.status||'—'}</span>;
 const Actions=({x}:{x:any})=><div className="flex flex-wrap gap-2">{kind!=='media'&&<button onClick={()=>setDetail(x)} className="px-2.5 py-1.5 text-xs font-bold rounded-lg border flex items-center gap-1"><Eye size={13}/>Chi tiết</button>}{kind==='comments'?<><button onClick={()=>void setStatus(x,'approved')} className="px-2.5 py-1.5 text-xs font-bold rounded-lg border border-emerald-200 text-emerald-700"><Check size={13}/>Duyệt</button><button onClick={()=>void setStatus(x,'hidden')} className="px-2.5 py-1.5 text-xs font-bold rounded-lg border">Ẩn</button></>:kind==='registrations'?<><button onClick={()=>void setStatus(x,'reviewing')} className="px-2.5 py-1.5 text-xs font-bold rounded-lg border">Đang xem</button><button onClick={()=>void setStatus(x,'accepted')} className="px-2.5 py-1.5 text-xs font-bold rounded-lg border border-emerald-200 text-emerald-700">Tiếp nhận</button><button onClick={()=>void setStatus(x,'rejected')} className="px-2.5 py-1.5 text-xs font-bold rounded-lg border border-rose-200 text-rose-700">Từ chối</button></>:kind==='contacts'?<><button onClick={()=>void setStatus(x,'reviewed')} className="px-2.5 py-1.5 text-xs font-bold rounded-lg border">Đã xem</button><button onClick={()=>void setStatus(x,'closed')} className="px-2.5 py-1.5 text-xs font-bold rounded-lg border">Đóng</button></>:null}<button onClick={()=>void del(x)} className="p-2 border border-rose-200 text-rose-600 rounded-lg" title="Xóa"><Trash2 size={15}/></button></div>;
 return <div className="space-y-4">
  <div className="flex flex-col sm:flex-row sm:items-end sm:justify-between gap-3"><div><h2 className="text-xl font-black text-slate-900">{title}</h2><p className="text-xs text-slate-500 mt-1">{subtitle}</p></div><div className="flex gap-2"><button onClick={()=>void load()} className="px-3 py-2 border rounded-xl text-xs font-bold flex items-center gap-2"><RefreshCw size={14}/>Tải lại</button>{kind==='media'&&<><input ref={fileRef} type="file" accept="image/jpeg,image/png,image/webp,image/gif,image/avif,image/svg+xml,application/pdf" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/><button onClick={()=>fileRef.current?.click()} className="px-3 py-2 bg-sky-600 text-white rounded-xl text-xs font-bold flex items-center gap-2"><UploadCloud size={14}/>Tải tệp</button></>}</div></div>
  <div className="relative"><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm theo tên, email, mã hồ sơ, nội dung..." className="w-full rounded-xl border border-slate-200 pl-10 pr-4 py-3 text-sm outline-none focus:border-sky-400 focus:ring-4 focus:ring-sky-100"/></div>
  {loading?<div className="py-10 flex items-center justify-center gap-2 text-sm text-slate-500"><Loader2 size={16} className="animate-spin"/>Đang xử lý...</div>:<div className="space-y-3">{filtered.length===0?<div className="rounded-2xl border border-dashed p-10 text-center text-sm text-slate-500">Chưa có dữ liệu phù hợp.</div>:filtered.map((x:any)=><div key={x.id||x.key} className="rounded-2xl border border-slate-200 bg-white p-4"><div className="flex flex-col lg:flex-row gap-4 lg:items-center"><div className="flex-1 min-w-0">{kind==='media'?<div className="flex gap-4 items-center"><div className="w-24 h-16 bg-slate-100 rounded-xl overflow-hidden shrink-0">{x.type==='application/pdf'?<div className="w-full h-full flex items-center justify-center"><FileText size={24} className="text-rose-500"/></div>:<img src={x.url} alt="Media" className="w-full h-full object-contain"/>}</div><div className="min-w-0"><div className="font-mono text-xs text-slate-700 break-all">{x.url}</div><div className="text-[11px] text-slate-400 mt-1">{fmt(x.uploaded)}{x.size?` • ${Math.round(x.size/1024)} KB`:''}</div></div></div>:<><div className="flex flex-wrap gap-2 items-center"><strong className="text-sm">{(kind==='registrations'||kind==='participants')?x.full_name:x.name}</strong><Status x={x}/><span className="text-[11px] text-slate-400">{fmt(x.created_at)}</span></div><div className="text-xs text-sky-700 font-semibold mt-1">{kind==='participants'?`${x.program_title||''} • Người tham gia`:kind==='registrations'?`${x.program_title||''}${x.application_code?` • ${x.application_code}`:''}`:kind==='comments'?`Bài: ${x.article_id||'—'}`:x.topic}</div><div className="text-xs text-slate-500 mt-1 truncate">{x.email}{x.phone?` • ${x.phone}`:''}</div><p className="mt-2 text-sm text-slate-600 line-clamp-2 whitespace-pre-wrap">{kind==='participants'?`Tham gia từ ${fmt(x.joined_at)}`:kind==='registrations'?x.motivation:kind==='comments'?x.content:x.message}</p></>}</div><div className="shrink-0">{kind==='participants'?<span className="rounded-full bg-emerald-50 px-3 py-1.5 text-xs font-bold text-emerald-700">Đang tham gia</span>:kind==='media'?<div className="flex gap-2"><button onClick={()=>{navigator.clipboard?.writeText(location.origin+x.url);onShowToast('Đã sao chép liên kết tệp.')}} className="p-2 border rounded-lg" title="Sao chép"><Copy size={15}/></button><a href={x.url} target="_blank" rel="noreferrer" className="p-2 border rounded-lg" title="Mở"><ExternalLink size={15}/></a><button onClick={()=>void del(x)} className="p-2 border border-rose-200 text-rose-600 rounded-lg"><Trash2 size={15}/></button></div>:<Actions x={x}/>}</div></div></div>)}</div>}
  {detail&&<div className="fixed inset-0 z-[120] bg-slate-950/45 backdrop-blur-[2px] p-3 sm:p-6 flex items-center justify-center" onMouseDown={e=>{if(e.target===e.currentTarget)setDetail(null)}}><div className="w-full max-w-3xl max-h-[calc(100vh-32px)] bg-white rounded-2xl shadow-2xl overflow-hidden flex flex-col"><header className="shrink-0 px-5 py-4 border-b flex items-start justify-between gap-4"><div><h3 className="font-black text-slate-900">{kind==='registrations'?'Chi tiết hồ sơ':kind==='comments'?'Chi tiết bình luận':'Chi tiết liên hệ'}</h3><div className="mt-1"><Status x={detail}/></div></div><button onClick={()=>setDetail(null)} className="p-2 rounded-lg hover:bg-slate-100"><X size={18}/></button></header><div className="overflow-y-auto p-5 space-y-4 text-sm"><Info label="Họ tên" value={kind==='registrations'?detail.full_name:detail.name}/><div className="grid sm:grid-cols-2 gap-4"><Info label="Email" value={detail.email}/><Info label="Điện thoại" value={detail.phone}/></div>{kind==='registrations'&&<><div className="grid sm:grid-cols-2 gap-4"><Info label="Chương trình" value={detail.program_title}/><Info label="Mã hồ sơ" value={detail.application_code}/><Info label="Năm sinh" value={detail.birth_year}/><Info label="Đơn vị / trường" value={detail.organization}/></div>{detail.portfolio_url&&<Info label="Hồ sơ / Portfolio" value={safeExternal(detail.portfolio_url)?<a className="text-sky-700 underline break-all" href={detail.portfolio_url} target="_blank" rel="noreferrer">{detail.portfolio_url}</a>:detail.portfolio_url}/>}<Info label="Động lực / nội dung đăng ký" value={<span className="whitespace-pre-wrap">{detail.motivation||'—'}</span>}/></>}{kind==='comments'&&<><Info label="Bài viết" value={detail.article_id}/><Info label="Nội dung" value={<span className="whitespace-pre-wrap">{detail.content}</span>}/></>}{kind==='contacts'&&<><Info label="Chủ đề" value={detail.topic}/><Info label="Nội dung" value={<span className="whitespace-pre-wrap">{detail.message}</span>}/></>}<Info label="Thời gian gửi" value={fmt(detail.created_at)}/></div><footer className="shrink-0 border-t px-5 py-4 flex flex-wrap justify-end gap-2"><Actions x={detail}/><button onClick={()=>setDetail(null)} className="px-4 py-2 rounded-xl bg-slate-900 text-white text-xs font-bold">Đóng</button></footer></div></div>}
 </div>
}

const Info=({label,value}:{label:string;value:any})=><div><div className="text-[11px] uppercase tracking-wide font-bold text-slate-400 mb-1">{label}</div><div className="rounded-xl bg-slate-50 border border-slate-100 px-3 py-2.5 text-slate-700 break-words">{value||'—'}</div></div>;

export const AdminRemoteDataManager:React.FC<{kind:Kind;onShowToast:(m:string)=>void}>=props=>props.kind==='media'?<AdminMediaLibrary onShowToast={props.onShowToast}/>:<RemoteRecordsManager {...props}/>;
