import React,{useEffect,useState} from 'react';
import {CheckCircle2,AlertTriangle,Loader2,RefreshCw} from 'lucide-react';
import {testFirestoreConnection} from '../../lib/firebase';
import {listMedia} from '../../lib/mediaApi';
import {useDataContext} from '../../context/DataContext';
export const AdminSystemHealth:React.FC=()=>{
 const {firebaseSyncStatus,firebaseSyncMessage}=useDataContext();const [results,setResults]=useState<{name:string;ok:boolean;detail:string}[]>([]),[loading,setLoading]=useState(false);
 const check=async()=>{setLoading(true);const [cms,media]=await Promise.allSettled([testFirestoreConnection(),listMedia()]);setResults([{name:'Dữ liệu website',ok:cms.status==='fulfilled'&&cms.value.ok,detail:cms.status==='fulfilled'?cms.value.message:'Không kết nối được dịch vụ dữ liệu.'},{name:'Thư viện hình ảnh',ok:media.status==='fulfilled',detail:media.status==='fulfilled'?'Đã kết nối thư viện. '+media.value.items.length+' tệp trong trang đầu.':String(media.reason?.message||'Không kết nối được thư viện.')}]);setLoading(false)};
 useEffect(()=>{void check()},[]);
 return <section className="max-w-5xl"><header className="flex justify-between gap-5"><div><h2 className="text-2xl font-bold">Tình trạng website</h2><p className="text-sm text-slate-500 mt-2">Kết quả kiểm tra kết nối thực tế trong phiên quản trị hiện tại.</p></div><button type="button" disabled={loading} onClick={()=>void check()} className="inline-flex items-center gap-2 border rounded-xl px-4 py-2 text-xs font-semibold"><RefreshCw size={15}/>Kiểm tra lại</button></header>{loading&&<p role="status" className="flex items-center gap-2 mt-6 text-sm"><Loader2 size={17} className="animate-spin"/>Đang kiểm tra…</p>}<div className="grid md:grid-cols-2 gap-4 mt-6">{results.map(item=><article key={item.name} className="border rounded-2xl bg-white p-5"><div className="flex items-center justify-between gap-3"><h3 className="font-semibold">{item.name}</h3>{item.ok?<CheckCircle2 className="text-emerald-600" size={20}/>:<AlertTriangle className="text-amber-600" size={20}/>}</div><p className="text-xs text-slate-500 mt-3">{item.detail}</p></article>)}</div><div className="border rounded-2xl mt-4 p-5"><h3 className="font-semibold">Trạng thái lưu nội dung</h3><p className={`text-xs mt-2 ${firebaseSyncStatus==='error'?'text-rose-700':'text-slate-500'}`}>{firebaseSyncMessage}</p></div></section>;
};
