import React,{useEffect,useMemo,useState} from 'react';
import {Plus,Trash2,Save,Search,Loader2,X,Upload,ShieldCheck,QrCode,ExternalLink,History,Copy} from 'lucide-react';
import {adminApi} from '../../lib/adminApi';
import {useDataContext} from '../../context/DataContext';

type Row={id:string;kind:string;title:string;subtitle?:string;status?:string;note?:string;public?:boolean;[key:string]:any};
const labels:Record<string,string>={
  partners:'Đối tác & Đơn vị đồng hành',contributions:'Tài trợ, Đóng góp & Quyên góp',certificates:'Giấy chứng nhận trung tâm',logs:'Nhật ký hoạt động',
  events:'Sự kiện',opportunities:'Cơ hội đang mở',documents:'Trung tâm tài liệu',people:'Con người Sky First',impact:'Số liệu & Tác động',transparency:'Công khai & Minh bạch',notifications:'Thông báo website',redirects:'Redirect & URL', 'email-templates':'Mẫu Email', integrations:'Tích hợp & Webhook'
};
const inputClass='w-full rounded-xl border border-slate-200 bg-white px-3 py-2.5 text-sm outline-none transition focus:border-sky-400 focus:ring-4 focus:ring-sky-100';
const fieldSets:Record<string,{key:string;label:string;type?:string;span?:boolean;placeholder?:string}[]>={
  partners:[{key:'category',label:'Lĩnh vực / Chuyên mục'},{key:'partnerType',label:'Loại đối tác / đồng hành'},{key:'website',label:'Website',type:'url'},{key:'logoUrl',label:'Logo từ Media Library',span:true},{key:'startDate',label:'Ngày bắt đầu',type:'date'},{key:'endDate',label:'Ngày kết thúc',type:'date'},{key:'relatedProgram',label:'Chương trình liên quan',span:true}],
  events:[{key:'category',label:'Lĩnh vực / Chuyên mục'},{key:'startDate',label:'Bắt đầu',type:'datetime-local'},{key:'endDate',label:'Kết thúc',type:'datetime-local'},{key:'location',label:'Địa điểm'},{key:'capacity',label:'Giới hạn người',type:'number'},{key:'registrationUrl',label:'Liên kết đăng ký',type:'url',span:true},{key:'mapUrl',label:'Bản đồ / Map URL',type:'url',span:true},{key:'bannerUrl',label:'Ảnh / Banner sự kiện (không ép tỷ lệ)',span:true},{key:'checkinEnabled',label:'Check-in QR (true/false)'},{key:'reportUrl',label:'Báo cáo sau sự kiện',type:'url'}],
  opportunities:[{key:'category',label:'Lĩnh vực / Chuyên mục'},{key:'opportunityType',label:'Loại cơ hội'},{key:'openAt',label:'Mở từ',type:'datetime-local'},{key:'closeAt',label:'Đóng lúc',type:'datetime-local'},{key:'applyUrl',label:'Liên kết ứng tuyển/đăng ký',type:'url',span:true},{key:'location',label:'Khu vực'},{key:'slots',label:'Chỉ tiêu nội bộ',type:'number'},{key:'featured',label:'Nổi bật (true/false)'}],
  documents:[{key:'category',label:'Lĩnh vực / Chuyên mục'},{key:'documentType',label:'Loại tài liệu'},{key:'year',label:'Năm'},{key:'unit',label:'Đơn vị'},{key:'version',label:'Phiên bản'},{key:'effectiveDate',label:'Ngày hiệu lực',type:'date'},{key:'fileUrl',label:'File PDF/Tài liệu',type:'url',span:true}],
  people:[{key:'role',label:'Chức danh'},{key:'unit',label:'Ban / Đơn vị'},{key:'imageUrl',label:'Ảnh thật từ Media Library',span:true},{key:'bio',label:'Giới thiệu',span:true},{key:'facebook',label:'Facebook',type:'url'},{key:'linkedin',label:'LinkedIn',type:'url'},{key:'sortOrder',label:'Thứ tự',type:'number'},{key:'allowIndex',label:'Cho phép index (true/false)'}],
  impact:[{key:'value',label:'Giá trị'},{key:'label',label:'Nhãn chỉ số'},{key:'unit',label:'Đơn vị'},{key:'year',label:'Năm'},{key:'scope',label:'Phạm vi (toàn mạng lưới/đơn vị/dự án)'},{key:'sourceUrl',label:'Nguồn / báo cáo',type:'url',span:true}],
  transparency:[{key:'category',label:'Lĩnh vực / Chuyên mục'},{key:'recordType',label:'Loại công khai'},{key:'project',label:'Dự án / Chương trình'},{key:'date',label:'Ngày cập nhật',type:'date'},{key:'amount',label:'Giá trị / số tiền'},{key:'fileUrl',label:'Tài liệu / chứng từ công khai',type:'url',span:true},{key:'sourceUrl',label:'Nguồn tham chiếu',type:'url',span:true},{key:'changeNote',label:'Ghi chú điều chỉnh',span:true}],
  notifications:[{key:'notificationType',label:'Loại (bar/popup/banner)'},{key:'startAt',label:'Bắt đầu',type:'datetime-local'},{key:'endAt',label:'Kết thúc',type:'datetime-local'},{key:'targetPath',label:'Phạm vi URL',placeholder:'/* hoặc /tham-gia'},{key:'buttonLabel',label:'Tên nút'},{key:'buttonUrl',label:'URL nút'}],
  redirects:[{key:'fromPath',label:'Đường dẫn cũ',placeholder:'/duong-dan-cu'},{key:'toPath',label:'Đường dẫn mới',placeholder:'/duong-dan-moi'},{key:'redirectCode',label:'Mã redirect',placeholder:'301'},{key:'active',label:'Kích hoạt (true/false)'}],
  'email-templates':[{key:'subject',label:'Tiêu đề Email',span:true},{key:'templateKey',label:'Mã template'},{key:'fromName',label:'Tên người gửi'},{key:'body',label:'Nội dung mẫu (hỗ trợ biến {{...}})',span:true}],
  integrations:[{key:'provider',label:'Dịch vụ / Provider'},{key:'endpoint',label:'Endpoint',type:'url',span:true},{key:'enabled',label:'Kích hoạt (true/false)'},{key:'mode',label:'Chế độ (test/live)'},{key:'secretHint',label:'Tên secret trong Cloudflare',span:true}],
  certificates:[{key:'certificateCode',label:'Mã giấy chứng nhận'},{key:'recipientName',label:'Người nhận'},{key:'programName',label:'Chương trình / hoạt động'},{key:'issueDate',label:'Ngày cấp',type:'date'},{key:'certificateUrl',label:'File chứng nhận',type:'url',span:true},{key:'verificationStatus',label:'Trạng thái xác thực'}],
};

export const AdminRecordsManager:React.FC<{kind:string,onShowToast:(m:string)=>void}>=({kind,onShowToast})=>{
 const {siteConfig}=useDataContext();
 const taxonomyOptions=(siteConfig.taxonomyCategories||[]).filter(x=>x.visible!==false);
 const [rows,setRows]=useState<Row[]>([]),[loading,setLoading]=useState(true),[q,setQ]=useState(''),[edit,setEdit]=useState<Row|null>(null),[saving,setSaving]=useState(false),[uploading,setUploading]=useState(false);
 const load=async()=>{setLoading(true);try{const d=await adminApi(`/api/admin-records?kind=${encodeURIComponent(kind)}`);setRows(d.items||[])}catch(e:any){onShowToast(e.message||'Không thể tải dữ liệu.')}finally{setLoading(false)}};
 useEffect(()=>{void load()},[kind]);
 useEffect(()=>{if(!edit)return;const prev=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=prev}},[edit]);
 const filtered=useMemo(()=>rows.filter(r=>JSON.stringify(r).toLowerCase().includes(q.toLowerCase())),[rows,q]);
 const save=async()=>{if(!edit?.title.trim())return onShowToast('Vui lòng nhập tên / tiêu đề.');setSaving(true);try{await adminApi('/api/admin-records',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(edit)});setEdit(null);await load();onShowToast('Đã lưu thay đổi.')}catch(e:any){onShowToast(e.message||'Không thể lưu.')}finally{setSaving(false)}};
 const del=async(id:string)=>{if(!confirm('Xóa bản ghi này? Thao tác sẽ được ghi vào nhật ký quản trị.'))return;try{await adminApi('/api/admin-records',{method:'DELETE',headers:{'content-type':'application/json'},body:JSON.stringify({id})});await load();onShowToast('Đã xóa bản ghi.')}catch(e:any){onShowToast(e.message||'Không thể xóa.')}};
 const set=(key:string,value:any)=>setEdit(v=>v?{...v,[key]:value}:v);
 const upload=async(file?:File,target='fileUrl')=>{if(!file)return;setUploading(true);try{const fd=new FormData();fd.append('file',file);const d=await adminApi('/api/media/upload',{method:'POST',body:fd});set(target,d.url);onShowToast('Đã tải tệp lên R2 Media.')}catch(e:any){onShowToast(e.message||'Không thể tải tệp.')}finally{setUploading(false)}};
 const newRow=()=>setEdit({id:`${kind}-${crypto.randomUUID?.()||Date.now()}`,kind,title:'',subtitle:'',status:'Bản nháp',public:false});
 const generateQr=()=>{if(!edit)return;const bank=(edit.bankId||'').trim(),account=String(edit.bankAccount||'').replace(/[^0-9A-Za-z]/g,'');if(!bank||!account)return onShowToast('Nhập mã ngân hàng VietQR và số tài khoản trước.');const p=new URLSearchParams();if(edit.accountHolder)p.set('accountName',edit.accountHolder);if(edit.transferMemo)p.set('addInfo',String(edit.transferMemo).slice(0,50));const numeric=String(edit.amount||'').replace(/[^0-9]/g,'');if(numeric)p.set('amount',numeric);set('vietQrUrl',`https://img.vietqr.io/image/${encodeURIComponent(bank)}-${encodeURIComponent(account)}-compact2.png?${p}`);onShowToast('Đã tạo VietQR động.');};
 if(kind==='logs')return <div className="space-y-4"><div><h2 className="text-xl font-black">{labels[kind]}</h2><p className="mt-1 text-xs text-slate-500">Nhật ký do hệ thống tự ghi, không tạo thủ công.</p></div><div className="rounded-2xl border bg-white"><div className="flex items-center gap-2 border-b p-3"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full outline-none text-sm" placeholder="Tìm trong nhật ký..."/></div>{loading?<div className="p-10 flex justify-center"><Loader2 className="animate-spin"/></div>:<div className="divide-y">{filtered.map(r=><div key={r.id} className="p-4 flex gap-3"><History size={17} className="mt-0.5 text-slate-400"/><div><div className="font-bold text-sm">{r.title}</div><div className="mt-1 text-xs text-slate-500">{r.subtitle}</div></div></div>)}</div>}</div></div>;
 const fields=fieldSets[kind]||[];
 return <div className="space-y-4"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-black">{labels[kind]||'Quản lý dữ liệu'}</h2><p className="text-xs text-slate-500 mt-1">Quản lý tập trung trên D1; R2 chỉ lưu file. Bản ghi public được cache và không chứa dữ liệu nhạy cảm.</p></div><button onClick={newRow} className="px-4 py-2 bg-[#0F2B5B] text-white rounded-xl text-sm font-bold flex items-center gap-2"><Plus size={16}/>Thêm mới</button></div>
 <div className="bg-white border rounded-2xl overflow-hidden"><div className="p-3 border-b flex items-center gap-2"><Search size={16}/><input value={q} onChange={e=>setQ(e.target.value)} className="w-full outline-none text-sm" placeholder="Tìm kiếm..."/></div>{loading?<div className="p-10 flex justify-center"><Loader2 className="animate-spin"/></div>:filtered.length===0?<div className="p-10 text-center text-sm text-slate-500">Chưa có dữ liệu.</div>:<div className="divide-y">{filtered.map(r=><div key={r.id} className="p-4 flex items-center gap-3"><div className="min-w-0 flex-1"><button onClick={()=>setEdit(r)} className="font-bold text-left hover:text-sky-700">{r.title}</button><div className="text-xs text-slate-500 mt-1 truncate">{r.subtitle||r.status}</div></div>{r.public&&<span className="rounded-full bg-emerald-50 px-2.5 py-1 text-[11px] font-bold text-emerald-700">Công khai</span>}<button onClick={()=>void del(r.id)} className="p-2 text-rose-600"><Trash2 size={16}/></button></div>)}</div>}</div>
 {edit&&<div className="fixed inset-0 z-[120] bg-slate-950/55 p-2 sm:p-5 flex items-center justify-center" onMouseDown={e=>{if(e.currentTarget===e.target)setEdit(null)}}><div className="flex w-full max-w-4xl max-h-[96dvh] flex-col overflow-hidden rounded-2xl border bg-white shadow-2xl"><header className="flex items-start justify-between border-b px-5 py-4"><div><h3 className="text-lg font-black">{edit.title?'Chỉnh sửa':'Thêm mới'} {labels[kind]?.toLowerCase()}</h3><p className="text-xs text-slate-500 mt-1">Dữ liệu có thể dùng lại ở Page Builder, Cổng Công khai và các khu vực public.</p></div><button onClick={()=>setEdit(null)} className="p-2"><X size={18}/></button></header><div className="flex-1 overflow-y-auto p-5 space-y-5">
 <section className="grid sm:grid-cols-2 gap-4"><label className="sm:col-span-2"><span className="text-xs font-bold">Tên / Tiêu đề</span><input value={edit.title||''} onChange={e=>set('title',e.target.value)} className={inputClass}/></label><label><span className="text-xs font-bold">Mô tả ngắn</span><input value={edit.subtitle||''} onChange={e=>set('subtitle',e.target.value)} className={inputClass}/></label><label><span className="text-xs font-bold">Trạng thái</span><input value={edit.status||''} onChange={e=>set('status',e.target.value)} className={inputClass}/></label>
 {fields.map(f=><label key={f.key} className={f.span?'sm:col-span-2':''}><span className="text-xs font-bold">{f.label}</span>{f.key==='category'?<><select value={String(edit.category||'')} onChange={e=>set('category',e.target.value)} className={inputClass}><option value="">Chọn lĩnh vực...</option>{taxonomyOptions.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select>{edit.category==='other'&&<input value={String(edit.categoryCustom||'')} onChange={e=>set('categoryCustom',e.target.value)} className={`${inputClass} mt-2`} placeholder="Nhập lĩnh vực khác..."/>}</>:f.key==='body'||f.key==='bio'||f.key==='changeNote'?<textarea rows={5} value={String(edit[f.key]||'')} onChange={e=>set(f.key,e.target.value)} className={inputClass} placeholder={f.placeholder}/>:<input type={f.type||'text'} value={String(edit[f.key]??'')} onChange={e=>set(f.key,e.target.value)} className={inputClass} placeholder={f.placeholder}/>}</label>)}
 </section>
 {kind==='contributions'&&<><h4 className="font-black text-sm">Funding Hub / VietQR</h4><section className="grid sm:grid-cols-2 gap-4">{[['contributionType','Hình thức'],['amount','Số tiền / giá trị'],['receivedDate','Ngày tiếp nhận'],['recipientEntity','Chủ thể tiếp nhận'],['bankId','Mã ngân hàng VietQR'],['bankName','Tên ngân hàng'],['bankAccount','Số tài khoản'],['accountHolder','Chủ tài khoản'],['transferMemo','Nội dung chuyển khoản'],['campaignId','Mã chiến dịch'],['reconcileStatus','Trạng thái đối soát'],['transactionRef','Mã giao dịch']].map(([k,l])=><label key={k}><span className="text-xs font-bold">{l}</span><input value={String(edit[k]||'')} onChange={e=>set(k,e.target.value)} className={inputClass}/></label>)}</section><div className="rounded-2xl border border-sky-100 bg-sky-50 p-4"><div className="flex justify-between gap-3"><div><b className="text-sm flex items-center gap-2"><QrCode size={17}/>VietQR động</b><p className="text-xs text-slate-500">QR chỉ hỗ trợ nhập thông tin chuyển khoản; trạng thái nhận tiền phải qua đối soát.</p></div><button onClick={generateQr} className="rounded-xl bg-sky-700 px-4 py-2 text-xs font-bold text-white">Tạo QR</button></div>{edit.vietQrUrl&&<div className="mt-3 flex gap-3 items-center"><img src={edit.vietQrUrl} className="h-36 w-36 bg-white rounded-xl p-2"/><button onClick={()=>navigator.clipboard?.writeText(edit.vietQrUrl)} className="text-xs font-bold text-sky-700"><Copy size={14} className="inline"/> Sao chép URL</button></div>}</div></>}
 <div className="rounded-2xl border border-dashed p-4"><label className="cursor-pointer flex items-center justify-center gap-2 font-bold text-sm"><Upload size={17}/>{uploading?'Đang tải...':'Tải file/ảnh/PDF lên R2'}<input type="file" className="hidden" disabled={uploading} onChange={e=>void upload(e.target.files?.[0],kind==='contributions'?'receiptUrl':'fileUrl')}/></label></div>
 <label className="block"><span className="text-xs font-bold">Ghi chú nội bộ</span><textarea rows={4} value={edit.note||''} onChange={e=>set('note',e.target.value)} className={inputClass}/></label>
 {!['redirects','email-templates','integrations','certificates','contributions'].includes(kind)&&<label className="flex gap-3 rounded-xl border p-4 text-sm"><input type="checkbox" checked={!!edit.public} onChange={e=>set('public',e.target.checked)}/><span><b>Cho phép xuất hiện công khai</b><span className="block text-xs text-slate-500 mt-1">Public API tự loại các trường nhạy cảm và có cache.</span></span></label>}
 {kind==='contributions'&&<div className="flex gap-2 rounded-xl bg-amber-50 p-3 text-xs text-amber-900"><ShieldCheck size={17}/><span>Không tự đánh dấu đã nhận/đã đối soát dựa trên việc tạo QR. Webhook ngân hàng nếu có phải xác thực và idempotent.</span></div>}
 </div><footer className="flex justify-end gap-2 border-t p-4"><button onClick={()=>setEdit(null)} className="px-4 py-2 border rounded-xl text-sm font-bold">Hủy</button><button disabled={saving} onClick={()=>void save()} className="px-4 py-2 bg-[#0F2B5B] text-white rounded-xl text-sm font-bold flex items-center gap-2">{saving?<Loader2 size={16} className="animate-spin"/>:<Save size={16}/>}Lưu thay đổi</button></footer></div></div>}</div>;
}
