import React, { useMemo, useState } from 'react';
import { Save, Plus, Trash2, ChevronUp, ChevronDown, Menu, PanelBottom, Gem, Columns3 } from 'lucide-react';
import { useDataContext } from '../../context/DataContext';

export const AdminGlobalContentManager:React.FC<{onShowToast:(m:string)=>void}>=({onShowToast})=>{
  const {siteConfig,updateSiteConfig,corePillars,updateCorePillar}=useDataContext();
  const [draft,setDraft]=useState(()=>JSON.parse(JSON.stringify(siteConfig)));
  const groups=draft.navigationGroups||[];
  const values=draft.coreValues||[];
  const quick=draft.footerQuickLinks||[];
  const contacts=draft.footerContacts||[];
  const portals=draft.footerPortals||[];
  const legal=draft.footerLegalLinks||[];
  const organization=draft.organizationInfo||[];
  const save=async()=>{const ok=await updateSiteConfig(draft);onShowToast(ok?'Đã lưu nội dung toàn cục và đồng bộ lên website.':'Chưa lưu được nội dung. Kiểm tra quyền hoặc kết nối rồi thử lại.');};
  const set=(k:string,v:any)=>setDraft((d:any)=>({...d,[k]:v}));
  const move=(arr:any[],i:number,dir:number)=>{const n=[...arr],j=i+dir;if(j<0||j>=n.length)return arr;[n[i],n[j]]=[n[j],n[i]];return n};
  return <div className="space-y-6 max-w-6xl">
    <div className="bg-white border border-slate-200 rounded-2xl p-5 flex flex-col sm:flex-row gap-4 sm:items-center sm:justify-between"><div><h2 className="text-xl font-black">Nội dung toàn cục</h2><p className="text-xs text-slate-500 mt-1">Chỉnh các thành phần xuất hiện trên nhiều trang: menu, chân trang, trụ cột và giá trị cốt lõi.</p></div><button onClick={save} className="px-4 py-2.5 rounded-xl bg-[#0F2B5B] text-white font-bold text-sm inline-flex items-center gap-2"><Save size={16}/>Lưu toàn bộ</button></div>

    <Card icon={<Menu size={18}/>} title="Menu điều hướng">
      <div className="space-y-4">{groups.map((g:any,gi:number)=><div key={gi} className="border rounded-2xl p-4 bg-slate-50"><div className="flex gap-2 items-center"><input value={g.label} onChange={e=>{const n=[...groups];n[gi]={...g,label:e.target.value};set('navigationGroups',n)}} className="flex-1 border rounded-xl px-3 py-2 font-bold"/><button onClick={()=>set('navigationGroups',move(groups,gi,-1))} className="p-2 border rounded-lg"><ChevronUp size={16}/></button><button onClick={()=>set('navigationGroups',move(groups,gi,1))} className="p-2 border rounded-lg"><ChevronDown size={16}/></button><button onClick={()=>set('navigationGroups',groups.filter((_:any,i:number)=>i!==gi))} className="p-2 border rounded-lg text-rose-600"><Trash2 size={16}/></button></div><div className="mt-3 space-y-2">{(g.items||[]).map((it:any,ii:number)=><div key={ii} className="grid md:grid-cols-12 gap-2 rounded-xl border border-slate-200 bg-white p-2"><input value={it.label} onChange={e=>{const n=JSON.parse(JSON.stringify(groups));n[gi].items[ii].label=e.target.value;set('navigationGroups',n)}} className="md:col-span-3 border rounded-lg px-3 py-2 text-sm font-bold" placeholder="Tên menu"/><input value={it.page||''} onChange={e=>{const n=JSON.parse(JSON.stringify(groups));n[gi].items[ii].page=e.target.value;set('navigationGroups',n)}} className="md:col-span-2 border rounded-lg px-3 py-2 text-sm" placeholder="Route"/><input value={it.slug||''} onChange={e=>{const n=JSON.parse(JSON.stringify(groups));n[gi].items[ii].slug=e.target.value;set('navigationGroups',n)}} className="md:col-span-2 border rounded-lg px-3 py-2 text-sm" placeholder="Slug"/><input value={it.description||''} onChange={e=>{const n=JSON.parse(JSON.stringify(groups));n[gi].items[ii].description=e.target.value;set('navigationGroups',n)}} className="md:col-span-4 border rounded-lg px-3 py-2 text-sm" placeholder="Mô tả ngắn hiển thị trong menu"/><button onClick={()=>{const n=JSON.parse(JSON.stringify(groups));n[gi].items=n[gi].items.filter((_:any,i:number)=>i!==ii);set('navigationGroups',n)}} className="md:col-span-1 p-2 text-rose-600"><Trash2 size={16}/></button></div>)}<button onClick={()=>{const n=JSON.parse(JSON.stringify(groups));n[gi].items=[...(n[gi].items||[]),{label:'Mục mới',page:'custom-page',slug:''}];set('navigationGroups',n)}} className="text-sm font-bold text-sky-700 inline-flex items-center gap-1"><Plus size={15}/>Thêm menu con</button></div></div>)}<button onClick={()=>set('navigationGroups',[...groups,{label:'Nhóm mới',items:[]}])} className="px-3 py-2 rounded-xl border font-bold text-sm inline-flex items-center gap-2"><Plus size={15}/>Thêm nhóm menu</button></div>
    </Card>

    <Card icon={<Gem size={18}/>} title="Số liệu nổi bật trang chủ">
      <p className="mb-4 text-xs leading-5 text-slate-500">Các số này hiển thị ở trang chủ và chạy hiệu ứng đếm một lần khi người xem cuộn tới. Có thể nhập hậu tố như + ngay trong giá trị, ví dụ 350+ hoặc 12.500+.</p>
      <div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4">
        {[
          ['membersCount','membersLabel','membersSubtext','Thành viên'],
          ['communityProjects','projectsLabel','projectsSubtext','Chương trình & hoạt động'],
          ['provincesCount','provincesLabel','provincesSubtext','Địa bàn hoạt động'],
          ['volunteerHours','hoursLabel','hoursSubtext','Giờ hoạt động'],
        ].map(([valueKey,labelKey,subKey,fallback])=><div key={valueKey} className="rounded-2xl border border-slate-200 bg-slate-50 p-3 space-y-2">
          <input value={(draft.stats as any)?.[valueKey]||''} onChange={e=>set('stats',{...(draft.stats||{}),[valueKey]:e.target.value})} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-xl font-black" placeholder="0"/>
          <input value={(draft.stats as any)?.[labelKey]||fallback} onChange={e=>set('stats',{...(draft.stats||{}),[labelKey]:e.target.value})} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-sm font-bold" placeholder={fallback}/>
          <input value={(draft.stats as any)?.[subKey]||''} onChange={e=>set('stats',{...(draft.stats||{}),[subKey]:e.target.value})} className="w-full rounded-xl border border-slate-200 bg-white px-3 py-2 text-xs" placeholder="Dòng mô tả nhỏ (tùy chọn)"/>
        </div>)}
      </div>
    </Card>

    <Card icon={<Columns3 size={18}/>} title="05 trụ cột hoạt động">
      <div className="grid lg:grid-cols-2 gap-3">{corePillars.map((p:any,i:number)=><div key={i} className="border rounded-xl p-3 space-y-2"><input value={p.title} onChange={e=>updateCorePillar(i,{title:e.target.value})} className="w-full border rounded-lg px-3 py-2 font-bold"/><textarea value={p.shortDesc} onChange={e=>updateCorePillar(i,{shortDesc:e.target.value,fullDesc:e.target.value})} rows={3} className="w-full border rounded-lg px-3 py-2 text-sm"/></div>)}</div>
    </Card>

    <Card icon={<Gem size={18}/>} title="06 giá trị cốt lõi">
      <div className="grid lg:grid-cols-2 gap-3">{values.map((v:any,i:number)=><div key={i} className="border rounded-xl p-3 space-y-2"><input value={v.name} onChange={e=>{const n=[...values];n[i]={...v,name:e.target.value};set('coreValues',n)}} className="w-full border rounded-lg px-3 py-2 font-bold"/><textarea value={v.desc} onChange={e=>{const n=[...values];n[i]={...v,desc:e.target.value};set('coreValues',n)}} rows={3} className="w-full border rounded-lg px-3 py-2 text-sm"/></div>)}</div>
    </Card>

    <Card icon={<Gem size={18}/>} title="Design System & hiệu ứng"><div className="grid md:grid-cols-3 gap-3"><input value={draft.designSystem?.primary||'#0B66C3'} onChange={e=>set('designSystem',{...(draft.designSystem||{}),primary:e.target.value})} className="border rounded-xl px-3 py-2" placeholder="Màu chính"/><input value={draft.designSystem?.navy||'#071B3A'} onChange={e=>set('designSystem',{...(draft.designSystem||{}),navy:e.target.value})} className="border rounded-xl px-3 py-2" placeholder="Navy"/><input value={draft.designSystem?.accent||'#22D3EE'} onChange={e=>set('designSystem',{...(draft.designSystem||{}),accent:e.target.value})} className="border rounded-xl px-3 py-2" placeholder="Accent"/><input value={draft.designSystem?.radius||'24px'} onChange={e=>set('designSystem',{...(draft.designSystem||{}),radius:e.target.value})} className="border rounded-xl px-3 py-2" placeholder="Radius"/><input value={draft.designSystem?.container||'1200px'} onChange={e=>set('designSystem',{...(draft.designSystem||{}),container:e.target.value})} className="border rounded-xl px-3 py-2" placeholder="Container"/><select value={draft.designSystem?.motion||'balanced'} onChange={e=>set('designSystem',{...(draft.designSystem||{}),motion:e.target.value})} className="border rounded-xl px-3 py-2"><option value="reduced">Giảm hiệu ứng</option><option value="balanced">Cân bằng</option><option value="rich">Nhiều hiệu ứng</option></select></div><p className="mt-3 text-xs text-slate-500">Website vẫn tôn trọng prefers-reduced-motion của thiết bị, kể cả khi chọn nhiều hiệu ứng.</p></Card>

    <Card icon={<Menu size={18}/>} title="Thông báo toàn website"><div className="grid md:grid-cols-2 gap-3"><label className="flex items-center gap-2 text-sm font-bold"><input type="checkbox" checked={!!draft.announcement?.enabled} onChange={e=>set('announcement',{...(draft.announcement||{}),enabled:e.target.checked})}/>Bật announcement bar</label><select value={draft.announcement?.tone||'info'} onChange={e=>set('announcement',{...(draft.announcement||{}),tone:e.target.value})} className="border rounded-xl px-3 py-2"><option value="info">Thông tin</option><option value="success">Tích cực</option><option value="warning">Quan trọng</option></select><input value={draft.announcement?.text||''} onChange={e=>set('announcement',{...(draft.announcement||{}),text:e.target.value})} className="md:col-span-2 border rounded-xl px-3 py-2" placeholder="Nội dung thông báo"/><input value={draft.announcement?.buttonLabel||''} onChange={e=>set('announcement',{...(draft.announcement||{}),buttonLabel:e.target.value})} className="border rounded-xl px-3 py-2" placeholder="Tên nút"/><input value={draft.announcement?.buttonUrl||''} onChange={e=>set('announcement',{...(draft.announcement||{}),buttonUrl:e.target.value})} className="border rounded-xl px-3 py-2" placeholder="URL nút"/><input type="datetime-local" value={draft.announcement?.startAt||''} onChange={e=>set('announcement',{...(draft.announcement||{}),startAt:e.target.value})} className="border rounded-xl px-3 py-2"/><input type="datetime-local" value={draft.announcement?.endAt||''} onChange={e=>set('announcement',{...(draft.announcement||{}),endAt:e.target.value})} className="border rounded-xl px-3 py-2"/></div></Card>

    <Card icon={<Gem size={18}/>} title="Thông tin Mạng lưới">
      <p className="mb-4 text-xs leading-5 text-slate-500">Mỗi dòng có thể sửa, thêm, xóa, kéo thứ tự hoặc tạm ẩn. Một trường trống không làm mất cả khối thông tin.</p>
      <EditorList title="Thông tin tổ chức & minh bạch" rows={organization} fields={['label','value','url','visible']} onChange={n=>set('organizationInfo',n)}/>
    </Card>

    <Card icon={<PanelBottom size={18}/>} title="Chân trang">
      <EditorList title="Liên kết nhanh" rows={quick} fields={['label','url']} onChange={n=>set('footerQuickLinks',n)}/>
      <EditorList title="Liên hệ & Kết nối" rows={contacts} fields={['label','value','url','icon']} onChange={n=>set('footerContacts',n)}/>
      <EditorList title="Các cổng Sky First" rows={portals} fields={['label','domain','url','icon']} onChange={n=>set('footerPortals',n)}/>
      <EditorList title="Liên kết pháp lý & hệ thống" rows={legal} fields={['label','url']} onChange={n=>set('footerLegalLinks',n)}/>
      <div className="mt-4"><label className="text-xs font-bold text-slate-700">Dòng bản quyền</label><input value={draft.footerCopyright||''} onChange={e=>set('footerCopyright',e.target.value)} className="mt-1 w-full border rounded-xl px-3 py-2"/></div>
    </Card>
  </div>
}
const Card:React.FC<{title:string;icon:React.ReactNode;children:React.ReactNode}>=({title,icon,children})=><section className="bg-white border border-slate-200 rounded-2xl p-5"><h3 className="font-black text-slate-900 flex items-center gap-2 mb-4">{icon}{title}</h3>{children}</section>;
const EditorList:React.FC<{title:string;rows:any[];fields:string[];onChange:(n:any[])=>void}>=({title,rows,fields,onChange})=><div className="mb-5"><div className="flex items-center justify-between mb-2"><h4 className="text-sm font-bold">{title}</h4><button onClick={()=>onChange([...rows,Object.fromEntries(fields.map(f=>[f,f==='visible'?true:'']))])} className="text-xs font-bold text-sky-700 inline-flex items-center gap-1"><Plus size={14}/>Thêm</button></div><div className="space-y-2">{rows.map((r:any,i:number)=><div key={i} className={`grid gap-2 ${fields.length>=4?'lg:grid-cols-4':'lg:grid-cols-2'} items-center`}>{fields.map(f=>f==='visible'?<label key={f} className="flex h-[42px] items-center gap-2 rounded-lg border bg-white px-3 text-sm font-bold text-slate-700"><input type="checkbox" checked={r[f]!==false} onChange={e=>{const n=[...rows];n[i]={...r,[f]:e.target.checked};onChange(n)}}/>Hiển thị</label>:<input key={f} value={String(r[f]??'')} onChange={e=>{const n=[...rows];n[i]={...r,[f]:e.target.value};onChange(n)}} className="border rounded-lg px-3 py-2 text-sm" placeholder={f}/>) }<div className="lg:col-span-full flex justify-end gap-1"><button onClick={()=>onChange(moveLocal(rows,i,-1))} className="p-1.5 border rounded"><ChevronUp size={14}/></button><button onClick={()=>onChange(moveLocal(rows,i,1))} className="p-1.5 border rounded"><ChevronDown size={14}/></button><button onClick={()=>onChange(rows.filter((_:any,j:number)=>j!==i))} className="p-1.5 border rounded text-rose-600"><Trash2 size={14}/></button></div></div>)}</div></div>;
function moveLocal(arr:any[],i:number,d:number){const n=[...arr],j=i+d;if(j<0||j>=n.length)return arr;[n[i],n[j]]=[n[j],n[i]];return n}
