import { html, parseForm, readCookie, cookie, redirect } from '../core/http.js';
import { cleanText, id, randomToken } from '../core/escape.js';
import { passwordHash, verifyPassword } from '../core/security.js';
import { all, one, run, setSetting, settings } from '../data/db.js';
const page=(title,body)=>`<!doctype html><html lang="vi"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title} | SKY FIRST NETWORK</title><link rel="stylesheet" href="/assets/css/tokens.css"><link rel="stylesheet" href="/assets/css/site.css"><link rel="stylesheet" href="/assets/css/admin.css"></head><body><main class="admin-shell">${body}</main></body></html>`;
async function session(request,env) { const sid=readCookie(request,'sky_admin'); return sid?await one(env.DB,"SELECT s.*,a.role FROM sky_sessions s JOIN sky_admins a ON a.email=s.admin_email WHERE s.id=? AND s.expires_at>CURRENT_TIMESTAMP AND a.active=1",sid):null; }
const input=(key,value,label=key,type='text')=>`<label>${label}<input type="${type}" name="${key}" value="${String(value??'').replaceAll('&','&amp;').replaceAll('"','&quot;')}"></label>`;
export async function adminRoute(request,env) { const path=new URL(request.url).pathname, s=await session(request,env);
 if(path==='/quan-tri/dang-nhap') return login(request,env);
 if(path==='/quan-tri/khoi-tao') return setup(request,env);
 if(path==='/quan-tri/dang-xuat') return new Response(null,{status:303,headers:{location:'/quan-tri/dang-nhap','set-cookie':cookie('sky_admin','',-1)}});
 if(!s) return redirect('/quan-tri/dang-nhap');
 if(path==='/quan-tri/tai-len'&&request.method==='POST') return upload(request,env,s);
 if(path.startsWith('/quan-tri/noi-dung/')&&path.endsWith('/luu')&&request.method==='POST') return saveTopic(request,env,s,path.split('/')[3]);
 if(path.startsWith('/quan-tri/noi-dung/')) return editTopic(request,env,s,path.split('/')[3]);
 if(path==='/quan-tri/luu'&&request.method==='POST') return save(request,env,s);
 const data=await settings(env.DB), topics=await all(env.DB,"SELECT slug,number,question FROM sky_topics WHERE locale='vi' ORDER BY number"), submissions=await all(env.DB,'SELECT * FROM sky_submissions ORDER BY created_at DESC LIMIT 20');
 return html(page('Quản trị',`<header class="admin-head"><div><p>SKY FIRST NETWORK</p><h1>Quản trị nội dung</h1></div><a href="/quan-tri/dang-xuat">Đăng xuất</a></header><p class="admin-note">Thay đổi tại đây được lưu trong hệ thống. Logo dùng URL ảnh đã tải lên hoặc đường dẫn /media/...; không cần sửa mã nguồn cho các mục này.</p><section class="admin-table"><h2>Tải logo, favicon hoặc ảnh lên</h2><form action="/quan-tri/tai-len" method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="${s.csrf_token}"><input type="file" name="file" accept="image/png,image/jpeg,image/webp,image/svg+xml" required><select name="target"><option value="brand_logo_url">Logo website</option><option value="brand_favicon_url">Favicon tab trình duyệt</option></select><button class="button">Tải lên và dùng ngay</button></form></section><form action="/quan-tri/luu" method="post" class="admin-grid"><input type="hidden" name="csrf" value="${s.csrf_token}"><section><h2>Nhận diện & liên hệ</h2>${['organization_name','organization_descriptor','tagline','footer_description','brand_logo_url','brand_favicon_url','theme_sky','theme_blue','theme_navy','theme_soft','card_radius','contact_email','support_email','hotline','facebook_url','instagram_url','tiktok_url'].map(k=>input(k,data[k],k)).join('')}<button class="button">Lưu nhận diện</button></section><section><h2>Tài trợ & đồng hành</h2>${['donation_verified','donation_bank','donation_account','donation_owner','donation_contact_name','donation_contact_phone','donation_contact_email'].map(k=>input(k,data[k],k)).join('')}<p class="admin-note">Đặt donation_verified là 1 chỉ sau khi thông tin được xác minh. Khi đó QR VietQR mới hiển thị công khai.</p><button class="button">Lưu tài trợ</button></section></form><section class="admin-table"><h2>33 nội dung chính thức</h2><p>Mỗi mục có hai bản Việt/Anh và được chỉnh trực tiếp trong quản trị.</p>${topics.map(x=>`<a href="/quan-tri/noi-dung/${x.slug}">${String(x.number).padStart(2,'0')} · ${x.question}</a>`).join('')}</section><section class="admin-table"><h2>Yêu cầu đã tiếp nhận</h2>${submissions.length?`<table><thead><tr><th>Thời gian</th><th>Họ tên</th><th>Đầu mối</th><th>Tiêu đề</th></tr></thead><tbody>${submissions.map(x=>`<tr><td>${x.created_at}</td><td>${x.name}<br>${x.email}</td><td>${x.department}</td><td>${x.subject}</td></tr>`).join('')}</tbody></table>`:'<p>Chưa có yêu cầu.</p>'}</section>`)); }
async function login(request,env) { if(request.method==='GET') return html(page('Đăng nhập',`<section class="login"><p>SKY FIRST NETWORK</p><h1>Đăng nhập quản trị</h1><form method="post"><label>Email<input name="email" type="email" required></label><label>Mật khẩu<input name="password" type="password" required></label><button class="button">Đăng nhập</button></form><p><a href="/quan-tri/khoi-tao">Khởi tạo tài khoản đầu tiên</a></p></section>`)); const f=await parseForm(request), admin=await one(env.DB,'SELECT * FROM sky_admins WHERE email=?',cleanText(f.email,254).toLowerCase()); if(!admin||!admin.active||!await verifyPassword(String(f.password||''),admin.password_hash)) return html(page('Đăng nhập',`<section class="login"><h1>Không thể đăng nhập</h1><p>Email hoặc mật khẩu không đúng.</p><a class="button" href="/quan-tri/dang-nhap">Thử lại</a></section>`),401); const sid=id(), csrf=await randomToken(); await run(env.DB,"INSERT INTO sky_sessions(id,admin_email,csrf_token,expires_at) VALUES(?,?,?,datetime('now','+12 hours'))",sid,admin.email,csrf); return new Response(null,{status:303,headers:{location:'/quan-tri','set-cookie':cookie('sky_admin',sid,43200)}}); }
async function setup(request,env) { const existing=await one(env.DB,'SELECT email FROM sky_admins LIMIT 1'); if(existing) return redirect('/quan-tri/dang-nhap'); if(request.method==='GET') return html(page('Khởi tạo',`<section class="login"><h1>Khởi tạo quản trị</h1><p>Chỉ dùng một lần. Cần mã khởi tạo đã đặt trong biến bí mật SETUP_KEY.</p><form method="post"><label>SETUP_KEY<input name="setup_key" type="password" required></label><label>Email quản trị<input name="email" type="email" required></label><label>Mật khẩu (từ 12 ký tự)<input name="password" type="password" minlength="12" required></label><button class="button">Tạo tài khoản</button></form></section>`)); const f=await parseForm(request); if(!env.SETUP_KEY||f.setup_key!==env.SETUP_KEY||String(f.password||'').length<12) return html(page('Khởi tạo',`<section class="login"><h1>Không thể khởi tạo</h1><p>Kiểm tra SETUP_KEY và mật khẩu.</p></section>`),403); await run(env.DB,'INSERT INTO sky_admins(email,password_hash,role) VALUES(?,?,?)',cleanText(f.email,254).toLowerCase(),await passwordHash(String(f.password)),'owner'); return redirect('/quan-tri/dang-nhap'); }
async function save(request,env,s) { const f=await parseForm(request); if(f.csrf!==s.csrf_token) return new Response('CSRF invalid',{status:403}); const allowed=['organization_name','organization_descriptor','tagline','footer_description','brand_logo_url','brand_favicon_url','theme_sky','theme_blue','theme_navy','theme_soft','card_radius','contact_email','support_email','hotline','facebook_url','instagram_url','tiktok_url','donation_verified','donation_bank','donation_account','donation_owner','donation_contact_name','donation_contact_phone','donation_contact_email']; for(const key of allowed) if(key in f) await setSetting(env.DB,key,cleanText(f[key],2000)); await run(env.DB,'INSERT INTO sky_audit(id,actor,action,target) VALUES(?,?,?,?)',id(),s.admin_email,'settings.update','site'); return redirect('/quan-tri?saved=1'); }
async function upload(request,env,s) { const f=await request.formData(); if(f.get('csrf')!==s.csrf_token)return new Response('CSRF invalid',{status:403}); const file=f.get('file'),target=f.get('target'); if(!file||typeof file==='string'||!['brand_logo_url','brand_favicon_url'].includes(target)||file.size>5_000_000||!['image/png','image/jpeg','image/webp','image/svg+xml'].includes(file.type))return new Response('Invalid upload',{status:400}); const key=`branding/${id()}-${String(file.name).replace(/[^a-z0-9._-]/gi,'-')}`; await env.MEDIA.put(key,file.stream(),{httpMetadata:{contentType:file.type}}); await run(env.DB,'INSERT INTO sky_media(id,r2_key,filename,content_type,bytes) VALUES(?,?,?,?,?)',id(),key,cleanText(file.name,255),file.type,file.size); await setSetting(env.DB,target,`/media/${key}`); await run(env.DB,'INSERT INTO sky_audit(id,actor,action,target) VALUES(?,?,?,?)',id(),s.admin_email,'media.upload',key); return redirect('/quan-tri?uploaded=1'); }
async function editTopic(request,env,s,slug) { const vi=await one(env.DB,'SELECT * FROM sky_topics WHERE slug=? AND locale=?',slug,'vi'), en=await one(env.DB,'SELECT * FROM sky_topics WHERE slug=? AND locale=?',slug,'en'); if(!vi||!en)return new Response('Not found',{status:404}); const safe=v=>String(v||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;'); return html(page('Biên tập nội dung',`<header class="admin-head"><div><p>SKY FIRST NETWORK</p><h1>Biên tập mục ${String(vi.number).padStart(2,'0')}</h1></div><a href="/quan-tri">← Quản trị</a></header><form action="/quan-tri/noi-dung/${slug}/luu" method="post" class="admin-table"><input type="hidden" name="csrf" value="${s.csrf_token}"><h2>Tiếng Việt</h2><label>Câu hỏi<input name="vi_question" value="${safe(vi.question)}"></label><label>Nội dung HTML<textarea name="vi_answer" rows="10">${safe(vi.answer_html)}</textarea></label><h2>English</h2><label>Question<input name="en_question" value="${safe(en.question)}"></label><label>HTML content<textarea name="en_answer" rows="10">${safe(en.answer_html)}</textarea></label><button class="button">Lưu hai ngôn ngữ</button></form>`)); }
async function saveTopic(request,env,s,slug) { const f=await parseForm(request);if(f.csrf!==s.csrf_token)return new Response('CSRF invalid',{status:403});for(const [locale,q,a] of [['vi','vi_question','vi_answer'],['en','en_question','en_answer']])await run(env.DB,'UPDATE sky_topics SET question=?,answer_html=?,updated_at=CURRENT_TIMESTAMP WHERE slug=? AND locale=?',cleanText(f[q],300),cleanText(f[a],12000),slug,locale);await run(env.DB,'INSERT INTO sky_audit(id,actor,action,target) VALUES(?,?,?,?)',id(),s.admin_email,'topic.update',slug);return redirect(`/quan-tri/noi-dung/${slug}`);}
