import { json, parseForm, redirect } from '../core/http.js';
import { cleanText, id } from '../core/escape.js';
import { run } from '../data/db.js';
export async function apiRoute(request, env) {
 const path=new URL(request.url).pathname;
 if(path==='/api/health') return json({ok:true,service:'SKY FIRST NETWORK',time:new Date().toISOString()});
 if(path==='/api/forms'&&request.method==='POST') { const f=await parseForm(request); const required=['name','email','phone','subject','message']; if(required.some(k=>!cleanText(f[k]))) return redirect('/lien-he?error=required'); await run(env.DB,'INSERT INTO sky_submissions(id,form_type,name,email,phone,organisation,subject,department,message) VALUES(?,?,?,?,?,?,?,?,?)',id(),cleanText(f.form_type,32)||'contact',cleanText(f.name,160),cleanText(f.email,254),cleanText(f.phone,48),cleanText(f.organisation,250),cleanText(f.subject,250),cleanText(f.department,80),cleanText(f.message,8000)); return redirect('/lien-he?sent=1'); }
 if(path==='/api/issuer/certificates'&&request.method==='POST') return issuerCertificate(request,env);
 return json({error:'Not found'},404);
}
async function issuerCertificate(request,env) { const key=request.headers.get('x-sky-issuer-key')||'', issuer=await env.DB.prepare('SELECT * FROM sky_issuer_keys WHERE issuer_key=? AND enabled=1').bind(key).first(); if(!issuer) return json({error:'Unauthorized issuer'},401); const body=await request.json().catch(()=>null); if(!body||!body.code||!body.holder_name||!body.achievement||!body.issued_at) return json({error:'Missing required fields'},400); const code=cleanText(body.code,100).toUpperCase(); await run(env.DB,'INSERT INTO sky_certificates(code,holder_name,achievement,issuer_key,issuer_name,issued_at,expires_at,status,public_note,updated_at) VALUES(?,?,?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(code) DO UPDATE SET holder_name=excluded.holder_name,achievement=excluded.achievement,issuer_key=excluded.issuer_key,issuer_name=excluded.issuer_name,issued_at=excluded.issued_at,expires_at=excluded.expires_at,status=excluded.status,public_note=excluded.public_note,updated_at=CURRENT_TIMESTAMP',code,cleanText(body.holder_name,160),cleanText(body.achievement,500),issuer.issuer_key,issuer.issuer_name,cleanText(body.issued_at,32),cleanText(body.expires_at,32)||null,['valid','expired','revoked','pending','test'].includes(body.status)?body.status:'pending',cleanText(body.public_note,1000)); return json({ok:true,code}); }
