import { json } from '../utils/response.js';
import { bodyJson } from '../utils/request.js';
import { rateLimit } from '../middleware/rate-limit.js';

const LANGS = new Set(['en','zh-CN','zh-TW','ja','ko','fr','de','es','pt','it','ru','th','id','ms','fil','hi','ar','tr','nl']);
const MAX_ITEMS = 30, MAX_TEXT = 1800, MAX_TOTAL = 24000;
const MYMEMORY = {'zh-CN':'zh-CN','zh-TW':'zh-TW','fil':'tl'};
function corsHeaders(){return {'access-control-allow-origin':'*','access-control-allow-methods':'POST, OPTIONS','access-control-allow-headers':'content-type','access-control-max-age':'86400','cache-control':'no-store'};}
async function digest(input){const bytes=new TextEncoder().encode(input);const hash=await crypto.subtle.digest('SHA-256',bytes);return [...new Uint8Array(hash)].map(b=>b.toString(16).padStart(2,'0')).join('');}
async function googleTranslate(value,target){const u=new URL('https://translate.googleapis.com/translate_a/single');u.searchParams.set('client','gtx');u.searchParams.set('sl','vi');u.searchParams.set('tl',target);u.searchParams.set('dt','t');u.searchParams.set('q',value);const r=await fetch(u.toString(),{headers:{'user-agent':'SkyFirstNetwork/1.0'}});if(!r.ok)throw new Error(`GOOGLE_${r.status}`);const d=await r.json();const out=(d?.[0]||[]).map(x=>x?.[0]||'').join('');if(!out)throw new Error('GOOGLE_EMPTY');return out;}
async function memoryTranslate(value,target){const tl=MYMEMORY[target]||target;const u=new URL('https://api.mymemory.translated.net/get');u.searchParams.set('q',value);u.searchParams.set('langpair',`vi|${tl}`);const r=await fetch(u.toString(),{headers:{'user-agent':'SkyFirstNetwork/1.0'}});if(!r.ok)throw new Error(`MEMORY_${r.status}`);const d=await r.json();const out=d?.responseData?.translatedText;if(!out||typeof out!=='string')throw new Error('MEMORY_EMPTY');return out;}
async function translateOne(text,target){const value=String(text||'');if(!value.trim())return value;let cache=null,key=null;try{cache=(typeof caches!=='undefined'&&caches.default)?caches.default:null;key=new Request(`https://translation-cache.skyfirst.internal/v2/${encodeURIComponent(target)}/${await digest(value)}`);const hit=cache?await cache.match(key):null;if(hit){const c=await hit.json();if(typeof c.translation==='string')return c.translation;}}catch{}
 let translation;try{translation=await googleTranslate(value,target);}catch(primary){console.warn('SKY_FIRST_TRANSLATION_PRIMARY_FAILED',String(primary));translation=await memoryTranslate(value,target);}if(cache&&key){try{await cache.put(key,new Response(JSON.stringify({translation}),{headers:{'content-type':'application/json; charset=utf-8','cache-control':'public, max-age=2592000'}}));}catch{}}return translation;}
export async function translateApi(request,env,url){if(url.pathname!=='/api/translate')return null;if(request.method==='OPTIONS')return new Response(null,{status:204,headers:corsHeaders()});if(request.method!=='POST')return json({error:'METHOD_NOT_ALLOWED'},405,corsHeaders());if(env.DB){const allowed=await rateLimit(request,env,'translate',{limit:90,windowSeconds:60});if(!allowed)return json({error:'RATE_LIMIT'},429,corsHeaders());}const body=await bodyJson(request);const target=String(body.target||'');const texts=Array.isArray(body.texts)?body.texts.map(v=>String(v??'')):[];if(!LANGS.has(target))return json({error:'UNSUPPORTED_LANGUAGE'},400,corsHeaders());if(!texts.length||texts.length>MAX_ITEMS)return json({error:'INVALID_BATCH'},400,corsHeaders());if(texts.some(v=>v.length>MAX_TEXT)||texts.reduce((n,v)=>n+v.length,0)>MAX_TOTAL)return json({error:'PAYLOAD_TOO_LARGE'},413,corsHeaders());try{const translations=await Promise.all(texts.map(t=>translateOne(t,target)));return json({ok:true,source:'vi',target,translations},200,corsHeaders());}catch(error){console.error('SKY_FIRST_TRANSLATION_ERROR',error);return json({error:'TRANSLATION_UNAVAILABLE'},502,corsHeaders());}}
