import React,{useEffect,useRef,useState} from 'react';
import {ArrowRight,Building2,HeartHandshake,Search,Send,Users,UserRoundPlus,UploadCloud,PenLine,X} from 'lucide-react';
import {useDataContext} from '../context/DataContext';
import {PageRoute} from '../types';
import {RichTextRenderer} from '../components/RichTextRenderer';

type F={id:string;slug:string;title:string;description:string;status?:string;fields?:any[];settings?:any};
interface JoinPageProps{onNavigate:(r:PageRoute)=>void;onShowToast:(m:string)=>void}

const SignatureField:React.FC<{value?:string;onChange:(v:string)=>void}>=({value,onChange})=>{
 const ref=useRef<HTMLCanvasElement|null>(null);const drawing=useRef(false);
 useEffect(()=>{const c=ref.current;if(!c)return;const ratio=Math.max(1,window.devicePixelRatio||1);const rect=c.getBoundingClientRect();c.width=rect.width*ratio;c.height=180*ratio;const ctx=c.getContext('2d');if(!ctx)return;ctx.scale(ratio,ratio);ctx.lineWidth=2;ctx.lineCap='round';ctx.strokeStyle='#0f172a';if(value){const img=new Image();img.onload=()=>ctx.drawImage(img,0,0,rect.width,180);img.src=value}},[]);
 const point=(e:React.PointerEvent<HTMLCanvasElement>)=>{const r=e.currentTarget.getBoundingClientRect();return{x:e.clientX-r.left,y:e.clientY-r.top}};
 const down=(e:React.PointerEvent<HTMLCanvasElement>)=>{drawing.current=true;e.currentTarget.setPointerCapture(e.pointerId);const ctx=e.currentTarget.getContext('2d');const p=point(e);ctx?.beginPath();ctx?.moveTo(p.x,p.y)};
 const move=(e:React.PointerEvent<HTMLCanvasElement>)=>{if(!drawing.current)return;const ctx=e.currentTarget.getContext('2d');const p=point(e);ctx?.lineTo(p.x,p.y);ctx?.stroke()};
 const up=(e:React.PointerEvent<HTMLCanvasElement>)=>{drawing.current=false;try{onChange(e.currentTarget.toDataURL('image/png'))}catch{}};
 const clear=()=>{const c=ref.current;if(!c)return;const ctx=c.getContext('2d');ctx?.clearRect(0,0,c.width,c.height);onChange('')};
 return <div className="rounded-xl border border-slate-200 overflow-hidden"><canvas ref={ref} onPointerDown={down} onPointerMove={move} onPointerUp={up} onPointerCancel={up} className="block h-[180px] w-full touch-none bg-white cursor-crosshair"/><div className="flex items-center justify-between border-t bg-slate-50 px-3 py-2 text-xs"><span className="flex items-center gap-1 text-slate-500"><PenLine size={13}/>Ký trực tiếp bằng chuột hoặc cảm ứng</span><button type="button" onClick={clear} className="font-bold text-rose-600">Xóa chữ ký</button></div></div>
};

export const JoinPage:React.FC<JoinPageProps>=({onNavigate,onShowToast})=>{
 const{customPages}=useDataContext();const p=customPages.find(x=>x.slug==='join'||x.id==='page-join');
 const roles=[1,2,3].map(i=>({title:(p as any)?.[`joinRole${i}Title`],tag:(p as any)?.[`joinRole${i}Tag`],text:(p as any)?.[`joinRole${i}Description`],button:(p as any)?.[`joinRole${i}ButtonLabel`],url:(p as any)?.[`joinRole${i}ButtonUrl`]})).filter(x=>x.title||x.text);
 const icons=[UserRoundPlus,HeartHandshake,Users,Building2];
 const[forms,setForms]=useState<F[]>([]),[selected,setSelected]=useState<F|null>(null),[answers,setAnswers]=useState<Record<string,any>>({}),[code,setCode]=useState(''),[lookup,setLookup]=useState<any>(null),[busy,setBusy]=useState(false),[uploading,setUploading]=useState<string>('');
 const loadForms=()=>fetch('/api/forms').then(r=>r.json()).then(async d=>{const list=d.items||[];setForms(list);const requested=new URLSearchParams(window.location.search).get('form');if(requested){const match=list.find((x:F)=>x.slug===requested);if(match){try{const detail=await fetch(`/api/forms?slug=${encodeURIComponent(match.slug)}`).then(r=>r.json());if(detail?.ok)setSelected(detail.item)}catch{}}}}).catch(()=>{});useEffect(()=>{loadForms()},[]);
 const open=async(f:F)=>{try{const d=await fetch(`/api/forms?slug=${encodeURIComponent(f.slug)}`).then(r=>r.json());if(!d.ok)throw new Error(d.error);setSelected(d.item);setAnswers({})}catch(e:any){onShowToast(e.message||'Không thể mở biểu mẫu.')}};
 const uploadField=async(field:any,file:File)=>{if(!selected)return;setUploading(field.id);try{const fd=new FormData();fd.append('file',file);const r=await fetch(`/api/forms?upload=1&formId=${encodeURIComponent(selected.id)}&fieldId=${encodeURIComponent(field.id)}`,{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error);setAnswers(a=>({...a,[field.id]:d.url}));onShowToast('Đã tải tệp lên.')}catch(e:any){onShowToast(e.message||'Không thể tải tệp.')}finally{setUploading('')}};
 const uploadSignature=async(field:any,dataUrl:string)=>{if(!selected){return}if(!dataUrl){setAnswers(a=>({...a,[field.id]:''}));return}try{const blob=await(await fetch(dataUrl)).blob();const fd=new FormData();fd.append('file',new File([blob],'signature.png',{type:'image/png'}));setUploading(field.id);const r=await fetch(`/api/forms?upload=1&formId=${encodeURIComponent(selected.id)}&fieldId=${encodeURIComponent(field.id)}`,{method:'POST',body:fd});const d=await r.json();if(!r.ok)throw new Error(d.error);setAnswers(a=>({...a,[field.id]:d.url}));}catch(e:any){onShowToast(e.message||'Không thể lưu chữ ký.')}finally{setUploading('')}};
 const submit=async()=>{if(!selected)return;setBusy(true);try{const r=await fetch('/api/forms',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({formId:selected.id,answers})});const d=await r.json();if(!r.ok)throw new Error(d.error);setCode(d.applicationCode);setSelected(null);onShowToast(d.message||`Đã nhận hồ sơ. Mã: ${d.applicationCode}`)}catch(e:any){onShowToast(e.message||'Không thể gửi hồ sơ.')}finally{setBusy(false)}};
 const doLookup=async()=>{const q=code.trim();if(!q)return onShowToast('Vui lòng nhập mã hồ sơ.');setBusy(true);try{const r=await fetch(`/api/forms?lookup=${encodeURIComponent(q)}`);const d=await r.json();if(!r.ok)throw new Error(d.error);setLookup(d.item)}catch(e:any){setLookup(null);onShowToast(e.message)}finally{setBusy(false)}};
 const update=(id:string,value:any)=>setAnswers(a=>({...a,[id]:value}));
 return <main className="bg-white"><section className="bg-[#071B3A] text-white py-20"><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-xs uppercase tracking-[.18em] text-sky-200 font-black">{p?.badge||'Tham gia'}</div><h1 className="mt-4 text-5xl lg:text-6xl font-black tracking-[-.045em]">{p?.title||'Tham gia Sky First Network'}</h1><p className="mt-5 max-w-3xl text-slate-300 leading-8">{p?.summary||''}</p></div></section>
 <section className="py-16"><div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">{(p?.contentFormatted||p?.content)&&<div className="mb-10"><RichTextRenderer content={p?.contentFormatted||p?.content||''}/></div>}<div className="grid md:grid-cols-2 gap-5">{roles.map((r,i)=>{const Icon=icons[i]||HeartHandshake;return <article key={i} className="rounded-2xl border p-6"><Icon/><h2 className="mt-3 text-2xl font-extrabold">{r.title}</h2><p className="mt-3 text-slate-600">{r.text}</p>{r.button&&<a href={r.url||'/contact'} className="mt-5 inline-flex gap-2 font-bold text-[#0B5FB4]">{r.button}<ArrowRight size={16}/></a>}</article>})}</div>
 <div className="mt-12"><h2 className="text-3xl font-black">Biểu mẫu đang mở</h2><div className="mt-5 grid md:grid-cols-2 gap-4">{forms.length?forms.map(f=><button key={f.id} onClick={()=>void open(f)} className="text-left rounded-2xl border p-5 hover:border-sky-400"><div className="font-black text-lg">{f.title}</div><p className="mt-2 text-sm text-slate-600">{f.description}</p><span className="mt-4 inline-flex font-bold text-sky-700">Đăng ký ngay →</span></button>):<p className="text-slate-500">Hiện chưa có biểu mẫu công khai.</p>}</div></div>
 <div className="mt-12 rounded-3xl bg-slate-50 border p-6"><h2 className="text-2xl font-black">Tra cứu hồ sơ</h2><p className="text-sm text-slate-600 mt-2">Nhập mã hồ sơ được cấp sau khi gửi biểu mẫu.</p><div className="mt-4 flex gap-2"><input value={code} onChange={e=>setCode(e.target.value)} className="flex-1 border rounded-xl px-4 py-3" placeholder="VD: SFN-20261006-ABC123"/><button onClick={()=>void doLookup()} className="bg-[#0F2B5B] text-white rounded-xl px-5 font-bold flex items-center gap-2"><Search size={17}/>Tra cứu</button></div>{lookup&&<div className="mt-4 rounded-xl bg-white border p-4"><b>{lookup.form_title}</b><div className="mt-1 text-sm">Mã: {lookup.application_code}</div><div className="text-sm">Trạng thái: <b>{lookup.status}</b></div></div>}</div></div></section>
 {selected&&<div className="fixed inset-0 z-[120] bg-slate-950/60 p-3 flex items-center justify-center"><div className="bg-white rounded-2xl max-w-3xl w-full max-h-[94vh] overflow-hidden flex flex-col"><header className="p-5 border-b flex justify-between gap-4"><div><h2 className="text-2xl font-black">{selected.title}</h2><p className="text-sm text-slate-600 mt-2">{selected.description}</p></div><button onClick={()=>setSelected(null)}><X/></button></header><div className="p-6 overflow-y-auto space-y-4">{(selected.fields||[]).map((f:any)=>{
   if(f.type==='section')return <h3 key={f.id} className="font-black text-lg pt-3">{f.label}</h3>;
   if(f.type==='consent')return <label key={f.id} className="flex gap-2 text-sm"><input type="checkbox" checked={!!answers[f.id]} onChange={e=>update(f.id,e.target.checked)}/><span>{f.label}{f.required?' *':''}</span></label>;
   if(f.type==='signature')return <div key={f.id}><div className="text-sm font-bold mb-2">{f.label}{f.required?' *':''}</div><SignatureField onChange={v=>void uploadSignature(f,v)}/>{uploading===f.id&&<div className="mt-1 text-xs text-sky-700">Đang lưu chữ ký...</div>}{answers[f.id]&&<div className="mt-1 text-xs text-emerald-700">Đã lưu chữ ký an toàn.</div>}</div>;
   if(['file','image'].includes(f.type))return <label key={f.id} className="block"><span className="text-sm font-bold">{f.label}{f.required?' *':''}</span><div className="mt-2 rounded-xl border border-dashed p-4"><span className="inline-flex items-center gap-2 text-sm font-bold"><UploadCloud size={16}/>{uploading===f.id?'Đang tải...':'Chọn tệp tải lên'}</span><input type="file" accept={f.type==='image'?'image/jpeg,image/png,image/webp':'image/jpeg,image/png,image/webp,application/pdf'} className="block mt-2 text-xs" onChange={e=>{const file=e.target.files?.[0];if(file)void uploadField(f,file)}}/>{answers[f.id]&&<div className="mt-2 text-xs text-emerald-700">Đã tải tệp thành công.</div>}</div></label>;
   if(['select','radio'].includes(f.type))return <label key={f.id} className="block"><span className="text-sm font-bold">{f.label}{f.required?' *':''}</span><select className="mt-1 w-full border rounded-xl p-3" value={answers[f.id]||''} onChange={e=>update(f.id,e.target.value)}><option value="">Chọn...</option>{(f.options||[]).map((o:string)=><option key={o}>{o}</option>)}</select></label>;
   if(f.type==='checkbox')return <div key={f.id}><div className="text-sm font-bold">{f.label}{f.required?' *':''}</div><div className="mt-2 grid sm:grid-cols-2 gap-2">{(f.options||[]).map((o:string)=>{const arr=Array.isArray(answers[f.id])?answers[f.id]:[];return <label key={o} className="flex gap-2 rounded-lg border p-2 text-sm"><input type="checkbox" checked={arr.includes(o)} onChange={e=>update(f.id,e.target.checked?[...arr,o]:arr.filter((x:string)=>x!==o))}/>{o}</label>})}</div></div>;
   const htmlType=['email','date','time','number'].includes(f.type)?f.type:f.type==='datetime'?'datetime-local':f.type==='url'?'url':f.type==='phone'?'tel':'text';
   return <label key={f.id} className="block"><span className="text-sm font-bold">{f.label}{f.required?' *':''}</span>{f.type==='textarea'?<textarea className="mt-1 w-full border rounded-xl p-3" placeholder={f.placeholder||''} value={answers[f.id]||''} onChange={e=>update(f.id,e.target.value)}/>:<input className="mt-1 w-full border rounded-xl p-3" type={htmlType} placeholder={f.placeholder||''} value={answers[f.id]||''} onChange={e=>update(f.id,e.target.value)}/>}</label>})}</div><footer className="p-4 border-t"><button disabled={busy||!!uploading} onClick={()=>void submit()} className="w-full rounded-xl bg-[#0F2B5B] disabled:opacity-60 text-white p-3 font-black flex justify-center gap-2"><Send size={18}/>Gửi hồ sơ</button></footer></div></div>}</main>
}
