INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('vi','Vietnamese','Tiếng Việt','ltr',1,1,1);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('en','English','English','ltr',1,0,2);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('zh-cn','Chinese Simplified','简体中文','ltr',1,0,3);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('zh-tw','Chinese Traditional','繁體中文','ltr',1,0,4);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('ja','Japanese','日本語','ltr',1,0,5);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('ko','Korean','한국어','ltr',1,0,6);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('fr','French','Français','ltr',1,0,7);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('de','German','Deutsch','ltr',1,0,8);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('es','Spanish','Español','ltr',1,0,9);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('pt','Portuguese','Português','ltr',1,0,10);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('ru','Russian','Русский','ltr',1,0,11);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('ar','Arabic','العربية','rtl',1,0,12);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('hi','Hindi','हिन्दी','ltr',1,0,13);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('th','Thai','ไทย','ltr',1,0,14);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('id','Indonesian','Bahasa Indonesia','ltr',1,0,15);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('it','Italian','Italiano','ltr',1,0,16);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('tr','Turkish','Türkçe','ltr',1,0,17);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('fil','Filipino','Filipino','ltr',1,0,18);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('nl','Dutch','Nederlands','ltr',1,0,19);
INSERT OR IGNORE INTO site_languages(code,name,native_name,direction,enabled,is_default,sort_order) VALUES('ms','Malay','Bahasa Melayu','ltr',1,0,20);
INSERT OR IGNORE INTO site_settings(key,value,group_name,value_type,is_public) VALUES('site_name','SKY FIRST NETWORK','general','text',1);
INSERT OR IGNORE INTO site_settings(key,value,group_name,value_type,is_public) VALUES('organization_name','Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First','general','text',1);
INSERT OR IGNORE INTO site_settings(key,value,group_name,value_type,is_public) VALUES('tagline','Giáo dục · Phát triển người trẻ · Cộng đồng','general','text',1);
INSERT OR IGNORE INTO site_settings(key,value,group_name,value_type,is_public) VALUES('email_main','skyfirst.ec@gmail.com','contact','text',1);
INSERT OR IGNORE INTO site_settings(key,value,group_name,value_type,is_public) VALUES('email_support','hotro.sfn@gmail.com','contact','text',1);
INSERT OR IGNORE INTO site_settings(key,value,group_name,value_type,is_public) VALUES('hotline','0924 910 210','contact','text',1);
INSERT OR IGNORE INTO site_settings(key,value,group_name,value_type,is_public) VALUES('facebook_url','https://www.facebook.com/skyfirstnetwork','contact','text',1);
INSERT OR IGNORE INTO site_settings(key,value,group_name,value_type,is_public) VALUES('instagram_url','https://www.instagram.com/sfn.network.vn','contact','text',1);
INSERT OR IGNORE INTO site_settings(key,value,group_name,value_type,is_public) VALUES('tiktok_url','https://www.tiktok.com/@sfn.network','contact','text',1);
INSERT OR IGNORE INTO site_settings(key,value,group_name,value_type,is_public) VALUES('default_meta_description','Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First kết nối giáo dục, phát triển người trẻ và cộng đồng.','seo','text',1);
INSERT OR IGNORE INTO site_settings(key,value,group_name,value_type,is_public) VALUES('legal_status','Sky First hiện được tổ chức và vận hành như một mạng lưới độc lập về tổ chức và định hướng hoạt động, nhưng chưa phải là một pháp nhân độc lập.','general','text',1);
INSERT OR IGNORE INTO site_units(code,name,official_name,english_name,description,logo_url,status,public,sort_order) VALUES('SFEC','Câu lạc bộ Tiếng Anh The Sky First','Câu lạc bộ Tiếng Anh The Sky First (SFEC)','The Sky First English Club','Đơn vị trực thuộc tập trung vào tiếng Anh, giáo dục cộng đồng, lớp học, học liệu và hoạt động hỗ trợ người học.','/assets/branding/sfec-logo.png','active',1,1);
INSERT OR IGNORE INTO site_units(code,name,official_name,english_name,description,logo_url,status,public,sort_order) VALUES('NHN','Nhà Hán Ngữ – 中文语言之家','Nhà Hán Ngữ – 中文语言之家 (NHN)','Chinese Language House','Đơn vị trực thuộc tập trung vào tiếng Trung, chia sẻ tri thức ngôn ngữ và xây dựng cộng đồng học tập.','/assets/branding/nhn-logo.jpg','active',1,2);
INSERT OR IGNORE INTO site_portals(code,name,subtitle,url,description,status,public,show_footer,sort_order) VALUES('academic','Cổng Học liệu & Học thuật','Sky First Academic Hub','https://academic.skyfirst.io.vn','Học liệu, tài liệu học thuật và tài nguyên giáo dục.','active',1,1,1);
INSERT OR IGNORE INTO site_portals(code,name,subtitle,url,description,status,public,show_footer,sort_order) VALUES('member','Cổng Thành viên','Sky First Member Portal','https://member.skyfirst.io.vn','Không gian dành cho thành viên của Sky First.','active',1,1,2);
INSERT OR IGNORE INTO site_portals(code,name,subtitle,url,description,status,public,show_footer,sort_order) VALUES('volunteer','Cổng Tình nguyện viên','Sky First Volunteer Portal','https://tnv.skyfirst.io.vn','Đăng ký và theo dõi hoạt động tình nguyện.','active',1,1,3);
INSERT OR IGNORE INTO site_portals(code,name,subtitle,url,description,status,public,show_footer,sort_order) VALUES('information','Cổng Thông tin','Sky First Information Portal','https://ctt.skyfirst.io.vn','Thông tin dành cho thành viên và tình nguyện viên.','active',1,1,4);
INSERT OR IGNORE INTO categories(name,slug,description,public,sort_order) VALUES('Tin tức','tin-tuc','Thông tin và cập nhật từ Sky First.',1,1);
INSERT OR IGNORE INTO categories(name,slug,description,public,sort_order) VALUES('Hoạt động','hoat-dong','Các hoạt động giáo dục và cộng đồng.',1,2);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:home','vi','','Trang chủ','Nội dung chính thức của Trang chủ.','<section class="hero"><div class="container hero-grid"><div><span class="kicker">SKY FIRST NETWORK</span><h1>Giáo dục để phát triển.<br/>Kết nối để tạo giá trị.</h1><p class="lead">Mạng lưới Giáo dục &amp; Phát triển Cộng đồng Sky First kết nối người trẻ, người học, tình nguyện viên và các nguồn lực để phát triển những cơ hội học tập, trải nghiệm và đóng góp có ý nghĩa.</p><div class="actions"><a class="btn primary" href="/gioi-thieu">Khám phá Sky First</a><a class="btn" href="/tham-gia">Tham gia cùng Sky First</a></div></div><div class="hero-card"><img alt="Sky First Network" src="/assets/branding/sky-first-main-logo.png"/><div class="hero-note"><b>SKY FIRST NETWORK</b><span>Education &amp; Community Development</span></div></div></div></section>
<section class="section"><div class="container"><div class="eyebrow">VỀ SKY FIRST NETWORK</div><h2>Một mạng lưới đang xây nền cho những cơ hội phát triển bền vững</h2><p class="intro">Sky First Network được phát triển từ các hoạt động giáo dục cộng đồng của Sky First. Mạng lưới tạo một không gian chung để người trẻ học tập, thử sức trong công việc thực tế, đóng góp cho cộng đồng và kết nối với những nguồn lực phù hợp.</p><div class="cards three"><a class="card linkcard" href="/gioi-thieu"><span>01</span><h3>Sky First Network là ai?</h3><p>Tìm hiểu bản chất, câu chuyện hình thành và ý nghĩa của Sky First.</p></a><a class="card linkcard" href="/tam-nhin-su-menh"><span>02</span><h3>Sky First Network hướng đến điều gì?</h3><p>Tầm nhìn, sứ mệnh, giá trị cốt lõi và định hướng phát triển.</p></a><a class="card linkcard" href="/tham-gia"><span>03</span><h3>Bạn có thể tham gia thế nào?</h3><p>Core Team, tình nguyện viên, người học và đồng hành chuyên môn.</p></a></div></div></section>
<section class="section tint"><div class="container"><div class="eyebrow">LĨNH VỰC HOẠT ĐỘNG</div><h2>Năm trụ cột kết nối với nhau</h2><div class="cards five"><a class="mini" href="/linh-vuc"><b>Giáo dục</b><span>Lớp học, học liệu, học thuật và hỗ trợ người học.</span></a><a class="mini" href="/linh-vuc"><b>Phát triển người trẻ</b><span>Học qua trải nghiệm, trách nhiệm và công việc thực tế.</span></a><a class="mini" href="/linh-vuc"><b>Tình nguyện &amp; Cộng đồng</b><span>Kết nối năng lực đóng góp với nhu cầu phù hợp.</span></a><a class="mini" href="/hop-tac"><b>Kết nối &amp; Hợp tác</b><span>Phối hợp chuyên môn, nguồn lực và chương trình.</span></a><a class="mini" href="/tin-tuc"><b>Truyền thông</b><span>Lan tỏa tri thức, cơ hội và câu chuyện hoạt động.</span></a></div></div></section>

<section class="section tint"><div class="container"><div class="eyebrow">HÀNH TRÌNH</div><h2>Từ hoạt động giáo dục cộng đồng đến Sky First Network</h2><div class="timeline"><div><b>Khởi nguồn</b><p>Các hoạt động giáo dục cộng đồng mang tên Sky First hình thành từ nhu cầu tạo cơ hội học tập và trải nghiệm.</p></div><div><b>Phát triển SFEC</b><p>Lớp học, học liệu và mạng lưới tình nguyện viên tạo nền tảng thực tế cho mô hình.</p></div><div><b>Mở rộng thành Sky First Network</b><p>Sky First phát triển thành cấp Mạng lưới để quản trị chung, kết nối nguồn lực và tạo không gian cho nhiều chương trình, đơn vị.</p></div><div><b>2026 · Chuẩn hóa hệ thống</b><p>Tập trung cơ cấu, Core Team, quy trình, dữ liệu và nền tảng số để tăng khả năng duy trì và kế thừa.</p></div></div><a class="textlink" href="/hanh-trinh">Xem hành trình Sky First →</a></div></section>

<section class="section tint"><div class="container"><div class="eyebrow">DÀNH CHO BẠN</div><h2>Chọn đúng hành trình của bạn</h2><div class="cards four"><a class="role" href="/core-team"><b>Core Team</b><p>Tham gia đội ngũ nòng cốt vận hành Mạng lưới.</p></a><a class="role" href="/tinh-nguyen-vien"><b>Tình nguyện viên</b><p>Đóng góp theo chương trình, chuyên môn hoặc hoạt động.</p></a><a class="role" href="/nguoi-hoc"><b>Người học</b><p>Tham gia lớp học, workshop và chương trình giáo dục.</p></a><a class="role" href="/hop-tac"><b>Đối tác &amp; Chuyên môn</b><p>Kết nối chuyên gia, đơn vị và nguồn lực phù hợp.</p></a></div></div></section>
<section class="section"><div class="container"><div class="cta"><div><small>HỢP TÁC CÙNG SKY FIRST NETWORK</small><h2>Kết nối nguồn lực để cùng tạo ra giá trị cho giáo dục và cộng đồng.</h2></div><a class="btn white" href="/hop-tac">Khám phá hình thức hợp tác</a></div></div></section>
<section class="section tint"><div class="container"><div class="section-head"><div><div class="eyebrow">THƯ VIỆN</div><h2>Những câu chuyện được lưu lại bằng hình ảnh</h2></div><a class="textlink" href="/thu-vien-anh">Mở thư viện →</a></div><div class="gallery"><div>Lớp học &amp; Giáo dục</div><div>Đội ngũ &amp; TNV</div><div>Chương trình &amp; Cộng đồng</div><div>Sự kiện</div><div>Ấn phẩm &amp; Truyền thông</div></div></div></section>
','published',1,'Trang chủ | Sky First Network','Thông tin Trang chủ của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:gioi-thieu','vi','gioi-thieu','Giới thiệu Sky First Network','Nội dung chính thức của Giới thiệu Sky First Network.','<div class="eyebrow">GIỚI THIỆU</div><h1>Sky First Network là gì?</h1><p class="lead">Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First là một mạng lưới hoạt động theo định hướng giáo dục, phát triển con người và kết nối cộng đồng.</p><h2>Một không gian chung để học tập, trải nghiệm và đóng góp</h2><p>Sky First Network được xây dựng để người trẻ có thể học tập, phát triển năng lực, tham gia hoạt động xã hội, thử sức trong các vai trò tổ chức và sử dụng kiến thức, kỹ năng của mình để tạo giá trị tích cực. Mạng lưới không giới hạn trong một môn học, một câu lạc bộ hay một dự án đơn lẻ.</p><div class="quote">Điểm cốt lõi của Sky First Network là kết nối: người học với cơ hội học tập; tình nguyện viên với môi trường đóng góp; người trẻ với cơ hội trải nghiệm; các đơn vị và đối tác với nguồn lực có thể bổ trợ cho nhau.</div><h2>Định danh chính thức</h2><p><b>Tên tiếng Việt:</b> Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.<br><b>Tên tiếng Anh:</b> Sky First Education & Community Development Network.<br><b>Tên thương hiệu:</b> Sky First Network / Sky First.</p><p>Sky First Network hoạt động theo định hướng tự nguyện và phi lợi nhuận, đặt giá trị giáo dục và cộng đồng làm trọng tâm.</p>','published',1,'Giới thiệu Sky First Network | Sky First Network','Thông tin Giới thiệu Sky First Network của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:hinh-thanh','vi','hinh-thanh','Câu chuyện hình thành','Nội dung chính thức của Câu chuyện hình thành.','<div class="eyebrow">CÂU CHUYỆN SKY FIRST</div><h1>Từ nhu cầu học tập đến một mạng lưới chung</h1><p>Sky First Network được hình thành từ quá trình phát triển các hoạt động giáo dục cộng đồng của Sky First. Nền tảng nổi bật ban đầu là Câu lạc bộ Tiếng Anh The Sky First (SFEC), với lớp học trực tuyến miễn phí, học liệu và đội ngũ tình nguyện viên hỗ trợ người học.</p><h2>Vì sao cần một cấp Mạng lưới?</h2><p>Khi hoạt động mở rộng, nhu cầu quản lý nhân sự, truyền thông, đối ngoại, chương trình và dữ liệu vượt ra ngoài phạm vi của một câu lạc bộ tiếng Anh. Từ đó Sky First được định hướng thành Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.</p><p>Việc hình thành Sky First Network không loại bỏ SFEC. SFEC tiếp tục là đơn vị trực thuộc chuyên về tiếng Anh, trong khi Sky First Network đảm nhận định hướng, quản trị chung và kết nối nguồn lực.</p><div class="timeline"><div><b>Nhu cầu thực tế</b><p>Tạo cơ hội học tập và phát triển cho người trẻ.</p></div><div><b>Hoạt động giáo dục cộng đồng</b><p>Hình thành các hoạt động Sky First và phát triển SFEC.</p></div><div><b>Mở rộng phạm vi</b><p>Nhận thấy nhu cầu quản trị và kết nối vượt khỏi một CLB.</p></div><div><b>Sky First Network</b><p>Xây dựng cấp Mạng lưới có khả năng duy trì, kế thừa và mở rộng.</p></div></div>','published',1,'Câu chuyện hình thành | Sky First Network','Thông tin Câu chuyện hình thành của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:y-nghia-sky-first','vi','y-nghia-sky-first','Ý nghĩa Sky First','Nội dung chính thức của Ý nghĩa Sky First.','<div class="eyebrow">THƯƠNG HIỆU</div><h1>“Sky First” — bầu trời là điểm bắt đầu</h1><p class="lead">Tên gọi thể hiện tinh thần không tự giới hạn khả năng phát triển của con người.</p><p>Hình ảnh bầu trời gợi đến không gian rộng mở, sự khám phá và những khả năng chưa được xác định trước. Một người có thể đến với Sky First từ vai trò rất đơn giản, rồi từng bước học hỏi, nhận trách nhiệm và phát triển.</p><div class="quote">Sky is not the limit – it’s just the beginning.</div><p>Thông điệp của Sky First không phải lời tuyên bố phóng đại về thành công. Tinh thần phù hợp nhất là dám bắt đầu, chủ động học hỏi, phát triển từng bước và dùng sự trưởng thành của mình để tạo thêm cơ hội cho cộng đồng.</p>','published',1,'Ý nghĩa Sky First | Sky First Network','Thông tin Ý nghĩa Sky First của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:tam-nhin-su-menh','vi','tam-nhin-su-menh','Tầm nhìn & Sứ mệnh','Nội dung chính thức của Tầm nhìn & Sứ mệnh.','<div class="eyebrow">ĐỊNH HƯỚNG</div><h1>Tầm nhìn & Sứ mệnh</h1><div class="cards two"><div class="card"><span>TẦM NHÌN</span><h2>Một hệ sinh thái kết nối cơ hội</h2><p>Sky First Network hướng đến một hệ sinh thái giáo dục và phát triển cộng đồng có khả năng kết nối người trẻ, người học, tình nguyện viên, đội ngũ chuyên môn và các nguồn lực xã hội để cùng tạo ra cơ hội học tập, trải nghiệm và đóng góp có ý nghĩa.</p><p>Ưu tiên không phải mở thật nhiều đơn vị trong thời gian ngắn mà xây dựng những mô hình có người chịu trách nhiệm, có quy trình và có khả năng kế thừa.</p></div><div class="card"><span>SỨ MỆNH</span><h2>Biến cơ hội thành hành trình phát triển</h2><p>Mở rộng cơ hội học tập; tạo môi trường trải nghiệm cho người trẻ; kết nối con người và nguồn lực; khuyến khích vòng tuần hoàn tích cực, nơi người được nhận cơ hội hôm nay có thể tạo cơ hội cho người khác trong tương lai.</p></div></div>','published',1,'Tầm nhìn & Sứ mệnh | Sky First Network','Thông tin Tầm nhìn & Sứ mệnh của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:gia-tri','vi','gia-tri','Giá trị cốt lõi','Nội dung chính thức của Giá trị cốt lõi.','<div class="eyebrow">GIÁ TRỊ CỐT LÕI</div><h1>Sáu giá trị định hướng cách Sky First Network hoạt động</h1><div class="cards three"><div class="card"><b>Giáo dục</b><p>Tri thức, kỹ năng và khả năng tự học là nền tảng phát triển.</p></div><div class="card"><b>Cộng đồng</b><p>Hoạt động cần tạo giá trị thực cho con người hoặc nhu cầu thực tế.</p></div><div class="card"><b>Trách nhiệm</b><p>Trao quyền đi cùng trách nhiệm với nhiệm vụ, dữ liệu và nguồn lực.</p></div><div class="card"><b>Chủ động & Phát triển</b><p>Khuyến khích đề xuất, thử sức, học từ thực hành và tiến bộ.</p></div><div class="card"><b>Kết nối & Hợp tác</b><p>Kết nối đúng cách giúp tri thức và nguồn lực tạo giá trị lớn hơn.</p></div><div class="card"><b>Bền vững</b><p>Ưu tiên mô hình có khả năng duy trì, kế thừa và cải tiến.</p></div></div>','published',1,'Giá trị cốt lõi | Sky First Network','Thông tin Giá trị cốt lõi của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:nguyen-tac','vi','nguyen-tac','Nguyên tắc hoạt động','Nội dung chính thức của Nguyên tắc hoạt động.','<div class="eyebrow">05 NGUYÊN TẮC HOẠT ĐỘNG</div><h1>Những nguyên tắc Sky First Network cam kết theo đuổi</h1><div class="principles"><div><span>01</span><h3>Tự nguyện</h3><p>Thành viên tham gia trên tinh thần tự nguyện, phù hợp khả năng và điều kiện cá nhân.</p></div><div><span>02</span><h3>Phi lợi nhuận</h3><p>Hoạt động hướng đến giáo dục và cộng đồng, không đặt mục tiêu phân chia lợi nhuận.</p></div><div><span>03</span><h3>Minh bạch</h3><p>Thông tin, hoạt động và các nội dung cần công khai được thực hiện rõ ràng theo phạm vi phù hợp.</p></div><div><span>04</span><h3>Bình đẳng & Tôn trọng</h3><p>Tôn trọng sự khác biệt, không phân biệt đối xử và tạo môi trường tham gia lành mạnh.</p></div><div><span>05</span><h3>Trách nhiệm với cộng đồng</h3><p>Hoạt động phải hướng đến giá trị thực tế cho giáo dục, người học và cộng đồng.</p></div></div>','published',1,'Nguyên tắc hoạt động | Sky First Network','Thông tin Nguyên tắc hoạt động của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:dinh-huong','vi','dinh-huong','Định hướng phát triển','Nội dung chính thức của Định hướng phát triển.','<div class="eyebrow">2026 & NHỮNG NĂM TIẾP THEO</div><h1>Xây nền trước, mở rộng có chọn lọc</h1><h2>Giai đoạn 2026 · Chuẩn hóa nền móng</h2><p>Sky First Network tập trung hoàn thiện cơ cấu, trách nhiệm của các bộ phận, tuyển chọn Core Team, chuẩn hóa biểu mẫu, dữ liệu, quy trình phối hợp, cơ chế phê duyệt và nguyên tắc quản trị.</p><h2>Củng cố hoạt động giáo dục có nền tảng</h2><p>Các lớp học, học liệu và quy trình quản lý người học/tình nguyện viên là môi trường thực tế để kiểm nghiệm mô hình giáo dục cộng đồng có hệ thống.</p><h2>Mở rộng có chọn lọc</h2><p>Các chương trình kỹ năng, tình nguyện, cộng đồng, sự kiện hoặc đơn vị mới chỉ được phát triển khi có nhu cầu, nguồn lực, người phụ trách và khả năng duy trì.</p><h2>Phát triển mạng lưới hợp tác</h2><p>Kết nối trường học, câu lạc bộ, dự án, tổ chức, doanh nghiệp và cá nhân chuyên môn theo phạm vi phù hợp.</p>','published',1,'Định hướng phát triển | Sky First Network','Thông tin Định hướng phát triển của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:linh-vuc','vi','linh-vuc','Lĩnh vực hoạt động','Nội dung chính thức của Lĩnh vực hoạt động.','<div class="eyebrow">HOẠT ĐỘNG</div><h1>Năm lĩnh vực trọng tâm</h1><div class="cards two"><div class="card"><h3>01 · Giáo dục & Học tập cộng đồng</h3><p>Lớp học, hoạt động học thuật, hỗ trợ người học, học liệu và chia sẻ kiến thức.</p></div><div class="card"><h3>02 · Phát triển người trẻ</h3><p>Thực hành giao tiếp, làm việc nhóm, quản lý công việc, truyền thông, nhân sự, đối ngoại và công cụ số.</p></div><div class="card"><h3>03 · Tình nguyện & Phát triển cộng đồng</h3><p>Kết nối người có khả năng đóng góp với nhu cầu phù hợp, có tổ chức và đánh giá.</p></div><div class="card"><h3>04 · Kết nối & Hợp tác</h3><p>Phối hợp với cá nhân, dự án, cơ sở giáo dục, tổ chức hoặc doanh nghiệp.</p></div><div class="card"><h3>05 · Truyền thông giáo dục & Cộng đồng</h3><p>Phổ biến kiến thức, giới thiệu cơ hội, kể lại hoạt động và kết nối người quan tâm.</p></div></div>','published',1,'Lĩnh vực hoạt động | Sky First Network','Thông tin Lĩnh vực hoạt động của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:doi-tuong','vi','doi-tuong','Đối tượng Sky First hướng đến','Nội dung chính thức của Đối tượng Sky First hướng đến.','<div class="eyebrow">DÀNH CHO AI?</div><h1>Người trẻ là trung tâm, nhưng mỗi chương trình có đối tượng riêng</h1><div class="cards four"><div class="card"><b>Người học</b><p>Tham gia lớp học, chương trình giáo dục, chia sẻ kiến thức và phát triển kỹ năng.</p></div><div class="card"><b>TNV & Thành viên tổ chức</b><p>Đóng góp vào giảng dạy, nội dung, truyền thông, nhân sự, đối ngoại, sự kiện.</p></div><div class="card"><b>Chuyên gia & Cố vấn</b><p>Đồng hành theo chuyên môn hoặc chia sẻ nguồn lực tri thức.</p></div><div class="card"><b>Đơn vị bên ngoài</b><p>Trường học, CLB, dự án, tổ chức và doanh nghiệp có nhu cầu phối hợp.</p></div></div>','published',1,'Đối tượng Sky First hướng đến | Sky First Network','Thông tin Đối tượng Sky First hướng đến của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:chuong-trinh','vi','chuong-trinh','Chương trình & Lớp học','Nội dung chính thức của Chương trình & Lớp học.','<div class="eyebrow">CHƯƠNG TRÌNH</div><h1>Hoạt động được trình bày theo trạng thái thực tế</h1><p class="lead">Chương trình có thể ở trạng thái đang triển khai, đang tuyển, đã kết thúc hoặc dự kiến. Website không trình bày kế hoạch tương lai như thể đã diễn ra.</p><div class="cards two"><div class="card"><span>GIÁO DỤC CỘNG ĐỒNG</span><h3>Lớp học tiếng Anh trực tuyến</h3><p>Được triển khai chủ yếu qua Câu lạc bộ Tiếng Anh The Sky First (SFEC), hướng đến nhiều nhóm người học và có TNV dạy học hỗ trợ.</p><a href="/sfec">Xem SFEC →</a></div><div class="card"><span>PHÁT TRIỂN MẠNG LƯỚI</span><h3>Xây dựng Core Team & hệ thống quản trị</h3><p>Tuyển chọn nhân sự nòng cốt, chuẩn hóa biểu mẫu, quy trình và nền tảng số. Chỉ các nội dung phù hợp mới được công khai.</p><a href="/core-team">Tìm hiểu Core Team →</a></div></div><h2>Thông tin lớp học cần rõ ràng</h2><p>Mỗi lớp/chương trình khi công bố cần thể hiện tên, đối tượng, mục tiêu, hình thức, lịch dự kiến, thời lượng, trạng thái, đơn vị phụ trách và hướng đăng ký.</p>','published',1,'Chương trình & Lớp học | Sky First Network','Thông tin Chương trình & Lớp học của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:hanh-trinh','vi','hanh-trinh','Dấu mốc & Hành trình','Nội dung chính thức của Dấu mốc & Hành trình.','<div class="eyebrow">HÀNH TRÌNH SKY FIRST</div><h1>Những dấu mốc được kể bằng quá trình phát triển</h1><div class="timeline"><div><b>Hoạt động giáo dục cộng đồng</b><p>Khởi nguồn từ nhu cầu hỗ trợ học tập và tạo cơ hội để người trẻ tham gia.</p></div><div><b>Phát triển Câu lạc bộ Tiếng Anh The Sky First</b><p>Lớp học, học liệu, TNV và quản lý người học tạo nền tảng thực tế.</p></div><div><b>Chuyển sang mô hình Mạng lưới</b><p>Tạo cấp quản trị rộng hơn và tách hoạt động toàn Mạng lưới khỏi chuyên môn từng đơn vị.</p></div><div><b>2026 · Tái cấu trúc & Chuẩn hóa</b><p>Xây dựng bộ máy lâm thời, Core Team, hệ thống quản trị, biểu mẫu và nền tảng số.</p></div></div><p class="note">Website không tự tạo ngày tháng, số lượng chương trình hoặc số người hưởng lợi khi chưa có hồ sơ xác nhận.</p>','published',1,'Dấu mốc & Hành trình | Sky First Network','Thông tin Dấu mốc & Hành trình của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:co-cau','vi','co-cau','Cơ cấu tổ chức','Nội dung chính thức của Cơ cấu tổ chức.','<div class="eyebrow">TỔ CHỨC</div><h1>Cơ cấu tinh gọn, phân cấp rõ và có khả năng mở rộng</h1><div class="org"><div class="org-top">BAN CHẤP HÀNH / CẤP MẠNG LƯỚI</div><div class="org-row"><div>Văn phòng Sky First Network</div><div>Ban Nhân sự</div><div>Ban Truyền thông</div><div>Ban Đối ngoại & Sự kiện</div></div><div class="org-note">CORE TEAM · Đội ngũ nòng cốt tham gia vận hành các đơn vị trên, không đồng nghĩa với Ban Chấp hành.</div><div class="org-row two"><div>Câu lạc bộ Tiếng Anh The Sky First (SFEC)</div><div>Nhà Hán Ngữ – 中文语言之家 (NHN)</div></div></div><p>Website chỉ công khai cấu trúc đang thực sự vận hành và nhân sự đã được phép công khai thông tin.</p>','published',1,'Cơ cấu tổ chức | Sky First Network','Thông tin Cơ cấu tổ chức của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:don-vi','vi','don-vi','Đơn vị trực thuộc','Nội dung chính thức của Đơn vị trực thuộc.','<div class="eyebrow">ĐƠN VỊ TRỰC THUỘC</div><h1>Các đơn vị chuyên môn trong hệ sinh thái Sky First Network</h1><p class="lead">Đơn vị trực thuộc có phạm vi chuyên môn riêng nhưng hoạt động trong hệ sinh thái và tuân theo cơ chế phối hợp chung.</p><div class="cards two"><a class="unit" href="/sfec"><img src="/assets/branding/sfec-logo.png"><div><small>ĐƠN VỊ TRỰC THUỘC</small><h3>Câu lạc bộ Tiếng Anh The Sky First (SFEC)</h3><p>Tiếng Anh, giáo dục cộng đồng, lớp học trực tuyến, học liệu và TNV dạy học.</p><b>Xem hồ sơ đơn vị →</b></div></a><a class="unit" href="/nhn"><img src="/assets/branding/nhn-logo.jpg"><div><small>ĐƠN VỊ TRỰC THUỘC</small><h3>Nhà Hán Ngữ – 中文语言之家 (NHN)</h3><p>Tiếng Trung, giáo dục ngôn ngữ, học tập và hoạt động cộng đồng.</p><b>Xem hồ sơ đơn vị →</b></div></a></div><p class="note">Một sáng kiến mới chỉ được đưa vào danh sách đơn vị trực thuộc khi tên, phạm vi, người phụ trách và cơ chế vận hành đã được xác nhận.</p>','published',1,'Đơn vị trực thuộc | Sky First Network','Thông tin Đơn vị trực thuộc của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:sfec','vi','sfec','Câu lạc bộ Tiếng Anh The Sky First (SFEC)','Nội dung chính thức của Câu lạc bộ Tiếng Anh The Sky First (SFEC).','<div class="unit-hero"><img src="/assets/branding/sfec-logo.png" alt="SFEC"><div><div class="eyebrow">ĐƠN VỊ TRỰC THUỘC SKY FIRST NETWORK</div><h1>Câu lạc bộ Tiếng Anh The Sky First (SFEC)</h1><p class="lead">Đơn vị trực thuộc tập trung vào tiếng Anh và giáo dục cộng đồng.</p></div></div><p>SFEC triển khai các hoạt động chuyên môn mà cấp Mạng lưới không trực tiếp thực hiện thay, đặc biệt là lớp học, học liệu, quản lý học viên và đội ngũ TNV dạy học.</p><h2>Vai trò trong hành trình Sky First</h2><p>SFEC là một trong những nền tảng hình thành hệ sinh thái Sky First. Kinh nghiệm từ lớp học trực tuyến miễn phí, tuyển TNV, xây dựng giáo trình và quản lý hoạt động góp phần cho thấy nhu cầu về một hệ thống quản trị rộng hơn.</p><div class="actions"><a class="btn primary" target="_blank" rel="noopener" href="https://ctt.skyfirst.io.vn">Đến Cổng Thông tin</a><a class="btn" target="_blank" rel="noopener" href="https://tnv.skyfirst.io.vn">Cơ hội TNV</a></div>','published',1,'Câu lạc bộ Tiếng Anh The Sky First (SFEC) | Sky First Network','Thông tin Câu lạc bộ Tiếng Anh The Sky First (SFEC) của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:nhn','vi','nhn','Nhà Hán Ngữ – 中文语言之家 (NHN)','Nội dung chính thức của Nhà Hán Ngữ – 中文语言之家 (NHN).','<div class="unit-hero"><img src="/assets/branding/nhn-logo.jpg" alt="Nhà Hán Ngữ"><div><div class="eyebrow">ĐƠN VỊ TRỰC THUỘC SKY FIRST NETWORK</div><h1>Nhà Hán Ngữ – 中文语言之家 (NHN)</h1><p class="lead">Đơn vị trực thuộc hoạt động trong lĩnh vực tiếng Trung, giáo dục ngôn ngữ và cộng đồng học tập.</p></div></div><p>Nhà Hán Ngữ có nhận diện và phạm vi chuyên môn riêng, đồng thời được giới thiệu rõ quan hệ trực thuộc Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.</p><h2>Định hướng nội dung công khai</h2><p>Website Sky First Network giới thiệu tổng quan về đơn vị, lĩnh vực, hoạt động chính và đường dẫn chính thức. Nội dung vận hành nội bộ của NHN không được tự động công khai trên website Mạng lưới.</p>','published',1,'Nhà Hán Ngữ – 中文语言之家 (NHN) | Sky First Network','Thông tin Nhà Hán Ngữ – 中文语言之家 (NHN) của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:doi-ngu','vi','doi-ngu','Đội ngũ công khai','Nội dung chính thức của Đội ngũ công khai.','<div class="eyebrow">ĐỘI NGŨ</div><h1>Minh bạch ở mức cần thiết, tôn trọng quyền riêng tư</h1><p>Website có thể công khai người đứng đầu Sky First Network và các chức danh lãnh đạo đã được xác nhận. Theo nguồn nội dung website hiện hành, Bùi Tấn Lộc là người sáng lập và Chủ tịch Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.</p><p>Với Core Team, chỉ nên công khai người phụ trách/đầu mối đã được bổ nhiệm và đồng ý sử dụng thông tin. Hồ sơ công khai tối giản gồm họ tên, chức danh, đơn vị, ảnh được phép sử dụng và giới thiệu ngắn.</p><div class="note">Không công khai ngày sinh đầy đủ, địa chỉ, số điện thoại cá nhân, email cá nhân, giấy tờ định danh, tài khoản nội bộ hoặc hồ sơ không phục vụ mục đích giới thiệu.</div>','published',1,'Đội ngũ công khai | Sky First Network','Thông tin Đội ngũ công khai của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:so-lieu','vi','so-lieu','Số liệu công khai','Nội dung chính thức của Số liệu công khai.','<div class="eyebrow">MINH BẠCH DỮ LIỆU</div><h1>Chỉ công khai số liệu có thể kiểm tra</h1><p>Sky First Network không dùng những bộ đếm lớn chỉ để tạo cảm giác quy mô. Chỉ số chương trình, lớp học, lượt đăng ký, người hoàn thành, TNV, giờ hoạt động hoặc đơn vị trực thuộc chỉ nên xuất hiện khi có nguồn dữ liệu rõ ràng và mốc cập nhật.</p><div class="note">Bản công khai này cố ý không đặt các con số như “hàng nghìn người”, “phủ sóng toàn quốc” hoặc thành tích chưa được xác minh.</div>','published',1,'Số liệu công khai | Sky First Network','Thông tin Số liệu công khai của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:doi-tac','vi','doi-tac','Đối tác & Đơn vị đồng hành','Nội dung chính thức của Đối tác & Đơn vị đồng hành.','<div class="eyebrow">ĐỐI TÁC</div><h1>Chỉ công khai quan hệ đã được xác nhận</h1><p>Tên và logo đối tác chỉ xuất hiện khi Sky First Network có căn cứ xác nhận mối quan hệ và quyền sử dụng nhận diện. Không lấy logo trên Internet để lấp đầy giao diện.</p><p>Module đối tác có thể quản lý trạng thái đang trao đổi, đã thống nhất phối hợp, đang triển khai, đã kết thúc hoặc đồng hành lâu dài. Khi chưa có danh sách được duyệt, khu vực logo có thể ẩn hoàn toàn.</p>','published',1,'Đối tác & Đơn vị đồng hành | Sky First Network','Thông tin Đối tác & Đơn vị đồng hành của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:tham-gia','vi','tham-gia','Tham gia cùng Sky First','Nội dung chính thức của Tham gia cùng Sky First.','<div class="eyebrow">THAM GIA</div><h1>Mỗi người có một cách đồng hành khác nhau</h1><p class="lead">Trang này giúp bạn chọn đúng hướng trước khi mở biểu mẫu hoặc cổng tương ứng.</p><div class="cards two"><a class="card linkcard" href="/core-team"><span>01</span><h3>Tham gia Core Team</h3><p>Đội ngũ nòng cốt đảm nhận công việc vận hành tại Văn phòng và các ban.</p></a><a class="card linkcard" href="/tinh-nguyen-vien"><span>02</span><h3>Trở thành Tình nguyện viên</h3><p>Tham gia theo chương trình hoặc chuyên môn: giảng dạy, truyền thông, sự kiện, cộng đồng...</p></a><a class="card linkcard" href="/nguoi-hoc"><span>03</span><h3>Tham gia với vai trò Người học</h3><p>Đăng ký lớp học, workshop, sự kiện hoặc chương trình giáo dục và cộng đồng.</p></a><a class="card linkcard" href="/dong-hanh-chuyen-mon"><span>04</span><h3>Đồng hành chuyên môn</h3><p>Chuyên gia, cố vấn hoặc cá nhân có chuyên môn hỗ trợ theo từng chương trình.</p></a></div>','published',1,'Tham gia cùng Sky First | Sky First Network','Thông tin Tham gia cùng Sky First của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:core-team','vi','core-team','Core Team','Nội dung chính thức của Core Team.','<div class="eyebrow">THAM GIA · CORE TEAM</div><h1>Đội ngũ nòng cốt vận hành Sky First Network</h1><p>Core Team có yêu cầu về mức độ cam kết, trách nhiệm và quy trình tuyển chọn cao hơn so với việc tham gia một hoạt động ngắn hạn. Khi có đợt tuyển, website cần hiển thị vị trí, yêu cầu, quy trình, trạng thái và hướng đăng ký.</p><div class="note">Core Team không đồng nghĩa với Ban Chấp hành và không mặc nhiên bao gồm các chức danh lãnh đạo cấp Mạng lưới.</div><a class="btn primary" target="_blank" rel="noopener" href="https://member.skyfirst.io.vn">Đến Cổng Thành viên</a>','published',1,'Core Team | Sky First Network','Thông tin Core Team của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:tinh-nguyen-vien','vi','tinh-nguyen-vien','Tình nguyện viên','Nội dung chính thức của Tình nguyện viên.','<div class="eyebrow">THAM GIA · TÌNH NGUYỆN</div><h1>Đóng góp theo chương trình và năng lực phù hợp</h1><p>TNV có thể tham gia giảng dạy, hỗ trợ lớp học, truyền thông, sự kiện hoặc hoạt động cộng đồng. Điều kiện và thời gian đồng hành được quy định theo từng chương trình; không dùng một biểu mẫu dài cho mọi loại TNV.</p><a class="btn primary" target="_blank" rel="noopener" href="https://tnv.skyfirst.io.vn">Đến Cổng Tình nguyện viên</a>','published',1,'Tình nguyện viên | Sky First Network','Thông tin Tình nguyện viên của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:nguoi-hoc','vi','nguoi-hoc','Người học','Nội dung chính thức của Người học.','<div class="eyebrow">THAM GIA · NGƯỜI HỌC</div><h1>Tiếp cận cơ hội học tập phù hợp</h1><p>Người học có thể tham gia lớp học, workshop, hoạt động chia sẻ kiến thức hoặc chương trình phát triển kỹ năng. Mỗi chương trình cần nêu rõ đối tượng, hình thức, lịch và trạng thái đăng ký.</p><div class="actions"><a class="btn primary" href="/chuong-trinh">Xem chương trình</a><a class="btn" target="_blank" rel="noopener" href="https://academic.skyfirst.io.vn">Mở Cổng Học liệu & Học thuật</a></div>','published',1,'Người học | Sky First Network','Thông tin Người học của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:dong-hanh-chuyen-mon','vi','dong-hanh-chuyen-mon','Đồng hành chuyên môn','Nội dung chính thức của Đồng hành chuyên môn.','<div class="eyebrow">THAM GIA · CHUYÊN MÔN</div><h1>Chia sẻ tri thức và kinh nghiệm</h1><p>Chuyên gia, cố vấn, giáo viên, giảng viên hoặc cá nhân có chuyên môn có thể đồng hành theo từng chương trình mà không nhất thiết tham gia vận hành thường xuyên.</p><a class="btn primary" href="/hop-tac">Kết nối với Sky First</a>','published',1,'Đồng hành chuyên môn | Sky First Network','Thông tin Đồng hành chuyên môn của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:hop-tac','vi','hop-tac','Hợp tác cùng Sky First','Nội dung chính thức của Hợp tác cùng Sky First.','<div class="eyebrow">HỢP TÁC</div><h1>Kết nối để cùng tạo ra giá trị</h1><p class="lead">Sky First Network tiếp nhận các đề xuất phù hợp với định hướng giáo dục và phát triển cộng đồng.</p><div class="cards two"><div class="card"><h3>Phối hợp chương trình</h3><p>Cùng xây dựng nội dung, phân công nguồn lực và triển khai lớp học, workshop, sự kiện hoặc hoạt động cộng đồng.</p></div><div class="card"><h3>Đồng hành chuyên môn</h3><p>Hỗ trợ nội dung, đào tạo đội ngũ, phản biện học liệu hoặc chia sẻ kiến thức.</p></div><div class="card"><h3>Truyền thông & Kết nối</h3><p>Lan tỏa thông tin phù hợp, kết nối người tham gia và phối hợp nội dung.</p></div><div class="card"><h3>Hỗ trợ nguồn lực</h3><p>Không gian, công cụ, học liệu, dịch vụ, chuyên môn hoặc nguồn lực hợp pháp khác.</p></div></div><h2>Quy trình liên hệ</h2><ol class="steps"><li>Tìm hiểu định hướng và lĩnh vực hoạt động của Sky First Network.</li><li>Gửi đề xuất qua biểu mẫu liên hệ hoặc email chính thức.</li><li>Sky First Network xem xét mức độ phù hợp, nguồn lực và phạm vi.</li><li>Hai bên trao đổi và xác lập nội dung phù hợp khi cần.</li></ol><p><b>Email chính thức:</b> skyfirst.ec@gmail.com</p><a class="btn primary" href="/lien-he">Gửi đề nghị hợp tác</a>','published',1,'Hợp tác cùng Sky First | Sky First Network','Thông tin Hợp tác cùng Sky First của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:tin-tuc','vi','tin-tuc','Tin tức & Hoạt động','Nội dung chính thức của Tin tức & Hoạt động.','<div class="eyebrow">TIN TỨC & HOẠT ĐỘNG</div><h1>Kênh thông tin chính thức của Sky First Network</h1><div class="filterbar"><button class="active">Tất cả</button><button>Tin Sky First</button><button>Giáo dục</button><button>Cộng đồng</button><button>Tình nguyện</button><button>Sự kiện</button><button>Thông báo</button><button>Đơn vị trực thuộc</button></div><div class="cards three"><article class="news"><span>GIÁO DỤC</span><h3>Chương trình và lớp học</h3><p>Các thông tin về lớp học được quản lý theo trạng thái để tránh nhầm lẫn giữa đợt đang mở và đã kết thúc.</p></article><article class="news"><span>SKY FIRST</span><h3>Dấu mốc phát triển</h3><p>Hành trình từ hoạt động giáo dục cộng đồng đến quá trình xây dựng Mạng lưới.</p></article><article class="news"><span>THAM GIA</span><h3>Cơ hội dành cho người trẻ</h3><p>Thông tin Core Team, TNV, người học và các hình thức đồng hành được phân luồng rõ ràng.</p></article></div><p class="note">Trong website vận hành thật, bài viết đã được duyệt/xuất bản sẽ xuất hiện tại đây. Bản công khai không giả lập tin tức hoặc đối tác chưa được xác nhận.</p>','published',1,'Tin tức & Hoạt động | Sky First Network','Thông tin Tin tức & Hoạt động của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:thu-vien','vi','thu-vien','Thư viện','Nội dung chính thức của Thư viện.','<div class="eyebrow">THƯ VIỆN</div><h1>Hình ảnh, tài liệu và dấu ấn hoạt động</h1><div class="cards two"><a class="card linkcard" href="/thu-vien-anh"><h3>Thư viện hình ảnh</h3><p>Lớp học, đội ngũ, cộng đồng, sự kiện và ấn phẩm truyền thông.</p></a><a class="card linkcard" href="/tai-lieu"><h3>Tài liệu công khai</h3><p>Hồ sơ giới thiệu, hướng dẫn, biểu mẫu và tài liệu đã được phê duyệt để chia sẻ.</p></a></div>','published',1,'Thư viện | Sky First Network','Thông tin Thư viện của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:thu-vien-anh','vi','thu-vien-anh','Thư viện hình ảnh','Nội dung chính thức của Thư viện hình ảnh.','<div class="eyebrow">THƯ VIỆN HÌNH ẢNH</div><h1>Ảnh được tổ chức theo câu chuyện hoạt động</h1><div class="gallery large"><div>Lớp học & Giáo dục</div><div>Đội ngũ & Tình nguyện viên</div><div>Chương trình & Cộng đồng</div><div>Sự kiện</div><div>Ấn phẩm & Truyền thông</div></div><p class="note">Ảnh công khai cần được kiểm tra quyền riêng tư, tối ưu dung lượng và có mô tả/alt text phù hợp.</p>','published',1,'Thư viện hình ảnh | Sky First Network','Thông tin Thư viện hình ảnh của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:tai-lieu','vi','tai-lieu','Tài liệu công khai','Nội dung chính thức của Tài liệu công khai.','<div class="eyebrow">TÀI LIỆU</div><h1>Tài liệu dành cho cộng đồng</h1><p>Chỉ các tài liệu đã được xác định là tài liệu bên ngoài mới được công khai: hồ sơ giới thiệu, hướng dẫn tham gia, biểu mẫu công khai, tài liệu truyền thông, báo cáo/tổng kết được duyệt và học liệu được phép chia sẻ.</p><div class="docrow"><b>Hồ sơ giới thiệu Sky First Network</b><span>Chưa phát hành trong Bản công khai</span></div><div class="docrow"><b>Hướng dẫn tham gia chương trình</b><span>Cập nhật theo từng đợt</span></div><div class="note">Không công khai hồ sơ ứng viên, dữ liệu học viên, đánh giá nhân sự, tài liệu nội bộ hoặc tài liệu chứa dữ liệu cá nhân.</div>','published',1,'Tài liệu công khai | Sky First Network','Thông tin Tài liệu công khai của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:tra-cuu','vi','tra-cuu','Tra cứu Giấy chứng nhận','Nội dung chính thức của Tra cứu Giấy chứng nhận.','<div class="eyebrow">XÁC THỰC SKY FIRST</div><h1>Tra cứu Giấy chứng nhận</h1><p class="lead">Nhập mã Giấy chứng nhận hoặc mã xác thực để kiểm tra trạng thái trên nguồn dữ liệu trung tâm của Sky First.</p>','published',1,'Tra cứu Giấy chứng nhận | Sky First Network','Thông tin Tra cứu Giấy chứng nhận của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:he-thong','vi','he-thong','Hệ thống Sky First','Nội dung chính thức của Hệ thống Sky First.','<div class="eyebrow">HỆ THỐNG SKY FIRST</div><h1>Các cổng số hỗ trợ vận hành hệ sinh thái</h1><p class="lead">Các cổng dưới đây là hệ thống nghiệp vụ, không phải đơn vị trực thuộc. Nhấn vào từng thẻ để mở cổng tương ứng trong tab mới.</p><div class="systems big"><a target="_blank" rel="noopener" href="https://academic.skyfirst.io.vn"><small>CỔNG HỌC LIỆU & HỌC THUẬT</small><h3>Sky First Academic Hub</h3><p>Không gian học liệu và học thuật.</p><b>Mở cổng →</b></a><a target="_blank" rel="noopener" href="https://member.skyfirst.io.vn"><small>CỔNG THÀNH VIÊN</small><h3>Sky First Member Portal</h3><p>Hệ thống dành cho thành viên.</p><b>Mở cổng →</b></a><a target="_blank" rel="noopener" href="https://tnv.skyfirst.io.vn"><small>CỔNG TÌNH NGUYỆN VIÊN</small><h3>Sky First Volunteer Portal</h3><p>Hệ thống dành cho tình nguyện viên.</p><b>Mở cổng →</b></a><a target="_blank" rel="noopener" href="https://ctt.skyfirst.io.vn"><small>CỔNG THÔNG TIN</small><h3>Sky First Information Portal</h3><p>Cổng thông tin theo phạm vi triển khai.</p><b>Mở cổng →</b></a></div>','published',1,'Hệ thống Sky First | Sky First Network','Thông tin Hệ thống Sky First của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:lien-he','vi','lien-he','Liên hệ','Nội dung chính thức của Liên hệ.','<div class="eyebrow">LIÊN HỆ</div><h1>Kết nối với Sky First Network</h1><p class="lead">Các kênh dưới đây là đầu mối chính thức của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.</p><div class="contact-grid"><div class="card"><h2>Kênh liên hệ</h2><p><b>Email chính:</b> <a class="textlink" href="mailto:skyfirst.ec@gmail.com">skyfirst.ec@gmail.com</a></p><p><b>Email hỗ trợ:</b> <a class="textlink" href="mailto:hotro.sfn@gmail.com">hotro.sfn@gmail.com</a></p><p><b>Hotline/Zalo:</b> 0924 910 210</p></div><div class="card"><h2>Mạng xã hội</h2><p><a class="textlink" href="https://www.facebook.com/skyfirstnetwork" target="_blank" rel="noopener">Facebook/Fanpage</a></p><p><a class="textlink" href="https://www.instagram.com/sfn.network.vn" target="_blank" rel="noopener">Instagram</a></p><p><a class="textlink" href="https://www.tiktok.com/@sfn.network" target="_blank" rel="noopener">TikTok</a></p></div></div><div class="note">Sky First không yêu cầu cung cấp mật khẩu, mã OTP hoặc thông tin đăng nhập qua email, biểu mẫu công khai hay tin nhắn.</div>','published',1,'Liên hệ | Sky First Network','Thông tin Liên hệ của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:phap-ly','vi','phap-ly','Tư cách & Minh bạch tổ chức','Nội dung chính thức của Tư cách & Minh bạch tổ chức.','<div class="eyebrow">MINH BẠCH TỔ CHỨC</div><h1>Sky First Network có phải là pháp nhân độc lập?</h1><p>Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First hiện được xây dựng và vận hành như một mạng lưới hoạt động độc lập về tổ chức và định hướng hoạt động. Tuy nhiên, “hoạt động độc lập” không đồng nghĩa với “có tư cách pháp nhân độc lập”.</p><p><b>Ở thời điểm hiện tại, Sky First Network chưa phải là một pháp nhân độc lập.</b> Tên, logo, website, cơ cấu, chức danh nội bộ, đơn vị trực thuộc và hệ thống quản trị phục vụ nhận diện và vận hành; không được hiểu là bằng chứng Mạng lưới đã được cơ quan nhà nước công nhận hoặc cấp tư cách pháp nhân.</p><p>Với công việc pháp luật hoặc đối tác yêu cầu một chủ thể có tư cách pháp lý phù hợp, Sky First Network không sử dụng danh nghĩa Mạng lưới để thay thế tư cách pháp lý mà mình chưa có; phương án thực hiện phải phù hợp từng trường hợp.</p><p>Thông tin này được công khai để thành viên, TNV, người học, đối tác và cộng đồng hiểu đúng bản chất tổ chức.</p>','published',1,'Tư cách & Minh bạch tổ chức | Sky First Network','Thông tin Tư cách & Minh bạch tổ chức của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:bao-mat-cong-khai','vi','bao-mat-cong-khai','Nguyên tắc công khai & An toàn thông tin','Nội dung chính thức của Nguyên tắc công khai & An toàn thông tin.','<div class="eyebrow">AN TOÀN THÔNG TIN</div><h1>Những nội dung không được công khai</h1><ul class="clean"><li>Mật khẩu, khóa API, token, secret, cấu hình hệ thống, backup hoặc thông tin cơ sở dữ liệu.</li><li>CCCD/giấy tờ định danh, địa chỉ nhà, số điện thoại/email cá nhân, hồ sơ ứng viên, danh sách học viên, đánh giá nội bộ khi không có mục đích công khai phù hợp.</li><li>Chức danh chưa bổ nhiệm, đơn vị/chương trình chưa xác nhận, số liệu ước tính, thành tích chưa kiểm chứng hoặc đối tác chưa đồng ý công khai.</li><li>Tài sản không có quyền sử dụng, logo bên thứ ba lấy tùy tiện, ảnh hoặc nội dung có vấn đề về quyền sử dụng.</li><li>Dữ liệu test xuất hiện như dữ liệu thật.</li></ul><div class="quote">Khi chưa chắc một thông tin có được phép công khai hay không, ưu tiên để ẩn và xác nhận trước.</div>','published',1,'Nguyên tắc công khai & An toàn thông tin | Sky First Network','Thông tin Nguyên tắc công khai & An toàn thông tin của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES('page:nhan-dien','vi','nhan-dien','Nhận diện thương hiệu','Nội dung chính thức của Nhận diện thương hiệu.','<div class="eyebrow">NHẬN DIỆN</div><h1>Quy tắc logo Sky First Network</h1><div class="brand-demo"><img src="/assets/branding/sky-first-main-logo.png"><div><h2>Logo nhận diện chính</h2><p>Logo S + SKY FIRST + EDUCATION & COMMUNITY DEVELOPMENT là logo mặc định của website và hệ thống truyền thông. Giữ nguyên tỷ lệ, màu sắc và cấu trúc.</p></div></div><h2>Logo GCN / Logo thương hiệu “Sky First Network · SKY FIRST NETWORK”</h2><p>Phiên bản chữ Sky First Network được ưu tiên cho Giấy chứng nhận, xác thực GCN và những ngữ cảnh cần nhấn mạnh tên viết tắt. Không dùng nó thay hoàn toàn logo nhận diện chính của website.</p><p>Logo đơn vị trực thuộc chỉ sử dụng trong phạm vi nội dung của đơn vị. Không tự vẽ lại, đổi màu, bóp méo hoặc tạo biến thể khi chưa được xác nhận.</p>','published',1,'Nhận diện thương hiệu | Sky First Network','Thông tin Nhận diện thương hiệu của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.',CURRENT_TIMESTAMP);
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(1,'header','Trang chủ','/',NULL,10,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(2,'header','Giới thiệu','/gioi-thieu',NULL,20,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(3,'header','Hoạt động','/linh-vuc',NULL,30,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(4,'header','Đơn vị trực thuộc','/don-vi',NULL,40,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(5,'header','Tham gia','/tham-gia',NULL,50,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(6,'header','Hợp tác','/hop-tac',NULL,60,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(7,'header','Tin tức','/tin-tuc',NULL,70,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(8,'header','Thư viện','/thu-vien',NULL,80,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(9,'header','Tra cứu','/tra-cuu',NULL,90,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(10,'header','Liên hệ','/lien-he',NULL,100,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(101,'header','Tổng quan Sky First Network','/gioi-thieu',2,1,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(102,'header','Câu chuyện hình thành','/hinh-thanh',2,2,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(103,'header','Ý nghĩa Sky First','/y-nghia-sky-first',2,3,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(104,'header','Tầm nhìn & Sứ mệnh','/tam-nhin-su-menh',2,4,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(105,'header','Giá trị cốt lõi','/gia-tri',2,5,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(106,'header','Nguyên tắc hoạt động','/nguyen-tac',2,6,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(107,'header','Định hướng phát triển','/dinh-huong',2,7,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(108,'header','Cơ cấu tổ chức','/co-cau',2,8,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(109,'header','Đội ngũ công khai','/doi-ngu',2,9,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(110,'header','Tư cách & Minh bạch','/phap-ly',2,10,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(111,'header','Lĩnh vực hoạt động','/linh-vuc',3,1,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(112,'header','Đối tượng hướng đến','/doi-tuong',3,2,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(113,'header','Chương trình & Lớp học','/chuong-trinh',3,3,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(114,'header','Dấu mốc & Hành trình','/hanh-trinh',3,4,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(115,'header','Tổng quan đơn vị','/don-vi',4,1,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(116,'header','Câu lạc bộ Tiếng Anh The Sky First (SFEC)','/sfec',4,2,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(117,'header','Nhà Hán Ngữ – 中文语言之家 (NHN)','/nhn',4,3,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(118,'header','Tham gia cùng Sky First','/tham-gia',5,1,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(119,'header','Core Team','/core-team',5,2,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(120,'header','Tình nguyện viên','/tinh-nguyen-vien',5,3,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(121,'header','Người học','/nguoi-hoc',5,4,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(122,'header','Đồng hành chuyên môn','/dong-hanh-chuyen-mon',5,5,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(123,'header','Tổng quan thư viện','/thu-vien',8,1,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(124,'header','Thư viện hình ảnh','/thu-vien-anh',8,2,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(125,'header','Tài liệu công khai','/tai-lieu',8,3,1,0,'vi');

-- Footer/Cài đặt/SEO mở rộng cho Production V2
INSERT OR IGNORE INTO site_settings(key,value,group_name,value_type,is_public) VALUES('footer_description','Kết nối giáo dục, phát triển người trẻ và các hoạt động hướng đến cộng đồng.','footer','text',1);
INSERT OR IGNORE INTO site_settings(key,value,group_name,value_type,is_public) VALUES('default_og_image','https://skyfirst.io.vn/assets/branding/sky-first-main-logo.png','seo','url',1);
INSERT OR IGNORE INTO site_settings(key,value,group_name,value_type,is_public) VALUES('site_name_browser','SKY FIRST NETWORK','seo','text',1);

INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(201,'footer_quick','Giới thiệu','/gioi-thieu',NULL,10,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(202,'footer_quick','Hoạt động','/linh-vuc',NULL,20,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(203,'footer_quick','Đơn vị trực thuộc','/don-vi',NULL,30,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(204,'footer_quick','Tin tức','/tin-tuc',NULL,40,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(205,'footer_quick','Thư viện','/thu-vien',NULL,50,1,0,'vi');

INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(211,'footer_join','Core Team','/core-team',NULL,10,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(212,'footer_join','Tình nguyện viên','/tinh-nguyen-vien',NULL,20,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(213,'footer_join','Người học','/nguoi-hoc',NULL,30,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(214,'footer_join','Hợp tác','/hop-tac',NULL,40,1,0,'vi');

INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(221,'footer_policy','Tư cách & Minh bạch','/phap-ly',NULL,10,1,0,'vi');
INSERT OR IGNORE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES(222,'footer_policy','Công khai & An toàn thông tin','/bao-mat-cong-khai',NULL,20,1,0,'vi');
INSERT OR IGNORE INTO site_settings(key,value,group_name,value_type,is_public) VALUES('fallback_language','vi','i18n','text',1);
