INSERT INTO languages(code,name,native_name,enabled,is_default) VALUES
('vi','Vietnamese','Tiếng Việt',1,1),
('en','English','English',1,0);

INSERT INTO settings(key,value,group_name,is_public) VALUES
('site_name','SKY FIRST NETWORK','identity',1),
('organization_name','Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First','identity',1),
('tagline','Giáo dục · Văn hóa · Cộng đồng','identity',1),
('footer_description','Khởi nguồn từ giáo dục miễn phí 2025 · Phát triển từ tri thức, văn hóa và cộng đồng.','identity',1),
('email_main','skyfirst.ec@gmail.com','contact',1),
('email_support','hotro.sfn@gmail.com','contact',1),
('hotline','0924 910 210','contact',1),
('facebook_url','https://www.facebook.com/skyfirstnetwork','contact',1),
('instagram_url','https://www.instagram.com/sfn.network','contact',1),
('tiktok_url','https://www.tiktok.com/@sfn.network','contact',1),
('default_og_image','https://skyfirst.io.vn/assets/branding/sky-first-main-logo.png','seo',1),
('brand_primary','#159BFF','appearance',1),
('brand_deep','#0648B8','appearance',1),
('brand_navy','#062A67','appearance',1),
('radius','16','appearance',1),
('donation_bank_name','','sponsorship',0),
('donation_bank_bin','','sponsorship',0),
('donation_account_number','','sponsorship',0),
('donation_account_name','','sponsorship',0),
('donation_transfer_note','[Họ tên / Tên đơn vị] + [Số điện thoại] + [Nội dung đồng hành]','sponsorship',1);

INSERT INTO portals(code,name,url,audience,description,status,show_header,show_footer,sort_order) VALUES
('academic','Sky First Academic Hub','https://academic.skyfirst.io.vn/','Người học & học thuật','Cổng học liệu và học thuật của Sky First.','ready',0,1,10),
('member','Sky First Member Portal','https://member.skyfirst.io.vn/','Thành viên','Không gian dành cho thành viên theo phạm vi được cấp quyền.','ready',0,1,20),
('volunteer','Cổng Tình nguyện viên Sky First','https://v.skyfirst.io.vn/','Tình nguyện viên','Cổng nghiệp vụ dành cho tình nguyện viên.','ready',0,1,30),
('information','Sky First Network — Cổng Thành viên & Tình nguyện viên','https://ctt.skyfirst.io.vn/','Thành viên & tình nguyện viên','Cổng thông tin dành cho thành viên và tình nguyện viên.','ready',1,1,40);

INSERT INTO menu_items(id,lang,location,parent_id,label,url,sort_order,visible,new_tab) VALUES
(1,'vi','header',NULL,'Trang chủ','/home',10,1,0),(2,'vi','header',NULL,'Giới thiệu','/gioi-thieu',20,1,0),(3,'vi','header',NULL,'Hoạt động','/hoat-dong',30,1,0),(4,'vi','header',NULL,'Đơn vị trực thuộc','/don-vi',40,1,0),(5,'vi','header',NULL,'Tham gia','/tham-gia',50,1,0),(6,'vi','header',NULL,'Hợp tác','/hop-tac',60,1,0),(7,'vi','header',NULL,'Tin tức','/tin-tuc',70,1,0),(8,'vi','header',NULL,'Thư viện','/thu-vien',80,1,0),(9,'vi','header',NULL,'Tra cứu','/tra-cuu',90,1,0),(10,'vi','header',NULL,'Liên hệ','/lien-he',100,1,0),
(21,'vi','header',2,'Sky First Network là gì?','/gioi-thieu',1,1,0),(22,'vi','header',2,'Câu chuyện hình thành','/gioi-thieu#hinh-thanh',2,1,0),(23,'vi','header',2,'Tầm nhìn & Sứ mệnh','/gioi-thieu#tam-nhin',3,1,0),(24,'vi','header',2,'Giá trị & Nguyên tắc','/gioi-thieu#nguyen-tac',4,1,0),(25,'vi','header',2,'Cơ cấu & Minh bạch','/gioi-thieu#minh-bach',5,1,0),
(31,'vi','header',3,'Lĩnh vực hoạt động','/hoat-dong',1,1,0),(32,'vi','header',3,'Chương trình & Lớp học','/hoat-dong#chuong-trinh',2,1,0),(33,'vi','header',3,'Hành trình Sky First','/hoat-dong#hanh-trinh',3,1,0),
(41,'vi','header',4,'Tổng quan đơn vị','/don-vi',1,1,0),(42,'vi','header',4,'Câu lạc bộ Tiếng Anh The Sky First','/don-vi#english-club',2,1,0),
(51,'vi','header',5,'Core Team','/tham-gia#core-team',1,1,0),(52,'vi','header',5,'Tình nguyện viên','/tham-gia#tinh-nguyen',2,1,0),(53,'vi','header',5,'Người học','/tham-gia#nguoi-hoc',3,1,0),
(81,'vi','header',8,'Thư viện hình ảnh','/thu-vien#hinh-anh',1,1,0),(82,'vi','header',8,'Tài liệu công khai','/thu-vien#tai-lieu',2,1,0),
(101,'en','header',NULL,'Home','/home',10,1,0),(102,'en','header',NULL,'About','/gioi-thieu',20,1,0),(103,'en','header',NULL,'Activities','/hoat-dong',30,1,0),(104,'en','header',NULL,'Affiliated unit','/don-vi',40,1,0),(105,'en','header',NULL,'Participate','/tham-gia',50,1,0),(106,'en','header',NULL,'Collaboration','/hop-tac',60,1,0),(107,'en','header',NULL,'News','/tin-tuc',70,1,0),(108,'en','header',NULL,'Library','/thu-vien',80,1,0),(109,'en','header',NULL,'Verification','/tra-cuu',90,1,0),(110,'en','header',NULL,'Contact','/lien-he',100,1,0),
(121,'en','header',102,'What is Sky First Network?','/gioi-thieu',1,1,0),(122,'en','header',102,'Origin story','/gioi-thieu#origin',2,1,0),(123,'en','header',102,'Vision & mission','/gioi-thieu#vision',3,1,0),(124,'en','header',102,'Values & principles','/gioi-thieu#principles',4,1,0),(125,'en','header',102,'Transparency','/gioi-thieu#transparency',5,1,0),
(131,'en','header',103,'Areas of activity','/hoat-dong',1,1,0),(132,'en','header',103,'Programmes & classes','/hoat-dong#programmes',2,1,0),(133,'en','header',103,'Sky First journey','/hoat-dong#journey',3,1,0),
(141,'en','header',104,'Unit overview','/don-vi',1,1,0),(142,'en','header',104,'The Sky First English Club','/don-vi#english-club',2,1,0),
(151,'en','header',105,'Core Team','/tham-gia#core-team',1,1,0),(152,'en','header',105,'Volunteer','/tham-gia#volunteer',2,1,0),(153,'en','header',105,'Learner','/tham-gia#learner',3,1,0),
(181,'en','header',108,'Image library','/thu-vien#images',1,1,0),(182,'en','header',108,'Public documents','/thu-vien#documents',2,1,0);

INSERT INTO pages(translation_key,lang,slug,title,summary,body_html,seo_title,seo_description,status,is_public,published_at) VALUES
('home','vi','home','Trang chủ','Cổng thông tin chính thức của Sky First Network.','<p>Sky First là không gian chung để người trẻ học tập, phát triển năng lực, tham gia hoạt động xã hội và tạo giá trị tích cực cho cộng đồng.</p>','SKY FIRST NETWORK | Giáo dục · Văn hóa · Cộng đồng','Website chính thức của Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.','published',1,CURRENT_TIMESTAMP),
('about','vi','gioi-thieu','Giới thiệu về Sky First Network','Nội dung chính thức về định danh, hành trình, tầm nhìn, sứ mệnh và nguyên tắc hoạt động.','<section id="hinh-thanh"><h2>Sky First Network là gì?</h2><p>Mạng lưới Giáo dục &amp; Phát triển Cộng đồng Sky First là một không gian kết nối giáo dục, phát triển con người và cộng đồng. Mạng lưới tạo điều kiện để người học, người trẻ, tình nguyện viên, đơn vị và nguồn lực xã hội gặp nhau trong những hoạt động có ý nghĩa.</p><p>Sky First hoạt động theo định hướng tự nguyện và phi lợi nhuận, không tự nhận là cơ quan nhà nước, doanh nghiệp hay pháp nhân độc lập. Trọng tâm là xây nền móng vận hành bền vững, minh bạch và có khả năng kế thừa.</p></section><section id="tam-nhin"><h2>Tầm nhìn &amp; Sứ mệnh</h2><p>Sky First hướng đến hệ sinh thái có khả năng kết nối cơ hội học tập, trải nghiệm và đóng góp. Sứ mệnh là mở rộng cơ hội học tập, tạo môi trường thực hành cho người trẻ và kết nối con người với nguồn lực phù hợp.</p><p>Quá trình hình thành bắt đầu từ các hoạt động giáo dục cộng đồng, đặc biệt là Câu lạc bộ Tiếng Anh The Sky First. Khi phạm vi hoạt động cần thêm điều phối, truyền thông, đối ngoại và quản trị dữ liệu, Sky First Network được xây dựng để đảm nhận vai trò định hướng và kết nối chung.</p></section><section id="nguyen-tac"><h2>Năm nguyên tắc hoạt động</h2><div class="principles"><article><b>01 · Tự nguyện</b><p>Tham gia phù hợp với điều kiện và năng lực cá nhân.</p></article><article><b>02 · Phi lợi nhuận</b><p>Ưu tiên giá trị giáo dục và cộng đồng.</p></article><article><b>03 · Minh bạch</b><p>Thông tin công khai được thể hiện rõ trong phạm vi phù hợp.</p></article><article><b>04 · Bình đẳng &amp; tôn trọng</b><p>Tôn trọng khác biệt và tạo môi trường lành mạnh.</p></article><article><b>05 · Trách nhiệm cộng đồng</b><p>Hướng đến giá trị thực tế cho người học và cộng đồng.</p></article></div></section><section id="minh-bach"><h2>Minh bạch tổ chức</h2><p>Sky First hiện được vận hành như một mạng lưới có định hướng, cơ cấu và quy trình riêng; điều này không đồng nghĩa với tư cách pháp nhân độc lập. Khi một hoạt động cần chủ thể pháp lý phù hợp, mạng lưới sẽ không dùng danh nghĩa của mình để thay thế tư cách chưa có.</p></section>','Giới thiệu | SKY FIRST NETWORK','Định danh, tầm nhìn, sứ mệnh, nguyên tắc và minh bạch của Sky First Network.','published',1,CURRENT_TIMESTAMP),
('activities','vi','hoat-dong','Chương trình & Hoạt động','Năm lĩnh vực hoạt động, chương trình, lớp học và hành trình phát triển của Sky First.','<section><h2>Năm lĩnh vực kết nối</h2><div class="card-grid"><article><h3>Giáo dục &amp; học tập cộng đồng</h3><p>Lớp học, học liệu, hoạt động học thuật và hỗ trợ người học.</p></article><article><h3>Phát triển người trẻ</h3><p>Trải nghiệm quản lý công việc, giao tiếp, tổ chức và trách nhiệm thực tế.</p></article><article><h3>Tình nguyện &amp; cộng đồng</h3><p>Kết nối năng lực đóng góp với nhu cầu phù hợp, có tổ chức và đánh giá.</p></article><article><h3>Kết nối &amp; hợp tác</h3><p>Phối hợp với cá nhân, dự án, cơ sở giáo dục, tổ chức và doanh nghiệp phù hợp.</p></article><article><h3>Truyền thông tri thức</h3><p>Lan tỏa kiến thức, cơ hội và câu chuyện hoạt động đã xác nhận.</p></article></div></section><section id="chuong-trinh"><h2>Chương trình &amp; lớp học</h2><p>Thông tin chỉ xuất hiện khi có trạng thái, đầu mối và nội dung được xác nhận. Chương trình đã hết hạn không tiếp tục hiển thị nút đăng ký như đang mở.</p></section><section id="hanh-trinh"><h2>Hành trình Sky First</h2><p>Hành trình được kể qua các dấu mốc đã xác nhận: khởi nguồn từ giáo dục miễn phí năm 2025, phát triển hoạt động giáo dục cộng đồng và xây nền tảng mạng lưới. Không tự tạo mốc hoặc số liệu chưa có căn cứ.</p></section>','Hoạt động | SKY FIRST NETWORK','Lĩnh vực, chương trình và hành trình hoạt động của Sky First.','published',1,CURRENT_TIMESTAMP),
('units','vi','don-vi','Các đơn vị trực thuộc','Không gian chuyên môn hoạt động dưới định hướng chung của Sky First Network.','<section id="english-club"><p class="eyebrow">ĐƠN VỊ TRỰC THUỘC</p><div class="unit-profile"><img src="/assets/branding/sfec-logo.png" alt="Câu lạc bộ Tiếng Anh The Sky First"><div><h2>Câu lạc bộ Tiếng Anh The Sky First</h2><p>Đơn vị tập trung vào giáo dục tiếng Anh cộng đồng, lớp học, học liệu, hỗ trợ người học và kết nối tình nguyện viên dạy học.</p><p>Đơn vị có phạm vi chuyên môn riêng, đồng thời tuân theo định hướng phối hợp chung của Sky First Network.</p></div></div></section><p>Đơn vị mới chỉ được công bố khi tên, phạm vi hoạt động, đầu mối phụ trách và khả năng vận hành đã được xác nhận.</p>','Đơn vị trực thuộc | SKY FIRST NETWORK','Thông tin đơn vị trực thuộc đã được xác nhận.','published',1,CURRENT_TIMESTAMP),
('participate','vi','tham-gia','Tham gia cùng Sky First','Chọn đúng hướng tham gia trước khi gửi thông tin đến đầu mối phù hợp.','<section id="core-team"><h2>Core Team</h2><p>Dành cho đội ngũ nòng cốt tham gia vận hành, xây hệ thống và phát triển chương trình. Đợt tuyển chỉ hiển thị khi có thông tin chính thức.</p></section><section id="tinh-nguyen"><h2>Tình nguyện viên</h2><p>Mỗi chương trình có điều kiện và biểu mẫu riêng; hệ thống không dùng một biểu mẫu dài cho mọi loại tình nguyện.</p></section><section id="nguoi-hoc"><h2>Người học</h2><p>Người học đăng ký tại trang chương trình tương ứng khi trạng thái còn nhận đăng ký.</p></section><section><h2>Gửi thông tin quan tâm</h2><form class="public-form" data-form-type="participation"><label>Họ và tên<input name="name" required maxlength="120"></label><label>Email<input name="email" type="email" required maxlength="160"></label><label>Số điện thoại<input name="phone" maxlength="40"></label><label>Nhu cầu / lời nhắn<textarea name="message" required maxlength="3000"></textarea></label><label class="check"><input name="consent" type="checkbox" required> Tôi đồng ý để Sky First sử dụng thông tin này nhằm tiếp nhận và phản hồi đề nghị.</label><button class="button primary">Gửi thông tin</button><p class="form-status" aria-live="polite"></p></form></section>','Tham gia | SKY FIRST NETWORK','Các hướng tham gia chính thức tại Sky First.','published',1,CURRENT_TIMESTAMP),
('collaboration','vi','hop-tac','Hợp tác & Đồng hành','Kết nối chuyên môn, chương trình, truyền thông và nguồn lực phù hợp.','<p>Sky First tiếp nhận đề xuất hợp tác theo các hướng: đồng tổ chức chương trình, đồng hành chuyên môn, truyền thông/kết nối cộng đồng và hỗ trợ nguồn lực phù hợp. Nội dung cụ thể được xem xét theo định hướng, nguồn lực và phạm vi triển khai.</p><p>Đề xuất nên nêu rõ đơn vị, đầu mối, mục tiêu, hình thức mong muốn, thời gian dự kiến và tài liệu liên quan. Sky First chỉ làm việc qua các kênh chính thức.</p><form class="public-form" data-form-type="collaboration"><label>Họ và tên<input name="name" required maxlength="120"></label><label>Email<input name="email" type="email" required maxlength="160"></label><label>Tổ chức / đơn vị<input name="organisation" maxlength="180"></label><label>Tiêu đề đề xuất<input name="subject" maxlength="180"></label><label>Nội dung đề xuất<textarea name="message" required maxlength="3000"></textarea></label><label class="check"><input name="consent" type="checkbox" required> Tôi đồng ý để Sky First sử dụng thông tin này nhằm xử lý đề xuất.</label><button class="button primary">Gửi đề xuất</button><p class="form-status" aria-live="polite"></p></form>','Hợp tác | SKY FIRST NETWORK','Kết nối hợp tác và đồng hành với Sky First.','published',1,CURRENT_TIMESTAMP),
('library','vi','thu-vien','Thư viện','Hình ảnh, tài liệu và tư liệu được phép công khai.','<section id="hinh-anh"><h2>Thư viện hình ảnh</h2><p>Ảnh hoạt động được tổ chức theo lớp học &amp; giáo dục, đội ngũ &amp; tình nguyện viên, chương trình &amp; cộng đồng, sự kiện, ấn phẩm &amp; truyền thông. Chỉ ảnh có quyền sử dụng và phù hợp công khai mới xuất hiện.</p></section><section id="tai-lieu"><h2>Tài liệu công khai</h2><p>Chỉ hồ sơ giới thiệu, hướng dẫn tham gia, biểu mẫu công khai, tài liệu truyền thông, báo cáo đã duyệt và học liệu được phép chia sẻ mới được đưa lên. Không công khai dữ liệu học viên, hồ sơ ứng viên, đánh giá nội bộ hay tài liệu chứa dữ liệu cá nhân.</p></section>','Thư viện | SKY FIRST NETWORK','Hình ảnh và tài liệu công khai của Sky First.','published',1,CURRENT_TIMESTAMP),
('systems','vi','he-thong','Hệ thống Sky First','Các cổng nghiệp vụ kết nối với website trung tâm.','<p>Các cổng số hỗ trợ vận hành hệ sinh thái, không phải đơn vị trực thuộc. Mỗi cổng mở ở tab mới và có mục đích, đối tượng sử dụng rõ ràng.</p>','Hệ thống | SKY FIRST NETWORK','Các cổng hệ thống Sky First.','published',1,CURRENT_TIMESTAMP),
('contact','vi','lien-he','Liên hệ & Văn phòng','Gửi yêu cầu đến đúng đầu mối chính thức của Sky First.','<div class="contact-cards"><article><h2>Kênh liên hệ chính thức</h2><p><a href="mailto:skyfirst.ec@gmail.com">skyfirst.ec@gmail.com</a><br><a href="mailto:hotro.sfn@gmail.com">hotro.sfn@gmail.com</a><br>Hotline/Zalo: 0924 910 210</p></article><article><h2>Lưu ý an toàn</h2><p>Sky First không yêu cầu mật khẩu, mã OTP hoặc thông tin đăng nhập qua email, biểu mẫu công khai hay tin nhắn.</p></article></div><form class="public-form" data-form-type="contact"><label>Họ và tên<input name="name" required maxlength="120"></label><label>Email liên hệ<input name="email" type="email" required maxlength="160"></label><label>Số điện thoại<input name="phone" maxlength="40"></label><label>Đơn vị / tổ chức<input name="organisation" maxlength="180"></label><label>Tiêu đề<input name="subject" maxlength="180"></label><label>Nội dung chi tiết<textarea name="message" required maxlength="3000"></textarea></label><label class="check"><input name="consent" type="checkbox" required> Tôi đồng ý để Sky First sử dụng thông tin này nhằm liên hệ và xử lý yêu cầu.</label><button class="button primary">Gửi yêu cầu</button><p class="form-status" aria-live="polite"></p></form>','Liên hệ | SKY FIRST NETWORK','Kênh liên hệ chính thức của Sky First.','published',1,CURRENT_TIMESTAMP),
('sponsorship','vi','tai-tro-dong-hanh','Tài trợ & Đồng hành','Kênh tiếp nhận nguồn lực chỉ công bố thông tin sau khi xác minh chính thức.','<p>Sky First chỉ công bố tài khoản, QR và đầu mối tiếp nhận sau khi đã hoàn tất xác minh. Không sử dụng tài khoản hoặc mã QR ngoài kênh này.</p><div class="notice"><strong>Đang chờ công bố sau xác minh.</strong><br>Thông tin tài khoản sẽ được quản trị viên cập nhật trong phần Tài trợ &amp; Đồng hành; khi đủ tên ngân hàng, BIN, số tài khoản và chủ tài khoản, hệ thống tạo VietQR từ dữ liệu đó.</div>','Tài trợ & Đồng hành | SKY FIRST NETWORK','Kênh tiếp nhận đồng hành chính thức.','published',1,CURRENT_TIMESTAMP),
('home','en','home','Home','Official information portal of Sky First Network.','<p>Sky First is a shared space for young people to learn, develop capability, take part in social activity and create positive value for community.</p>','SKY FIRST NETWORK | Education · Culture · Community','Official website of Sky First Education & Community Development Network.','published',1,CURRENT_TIMESTAMP),
('about','en','gioi-thieu','About Sky First Network','Official information on identity, origin, vision, mission and operating principles.','<section id="origin"><h2>What is Sky First Network?</h2><p>Sky First Education &amp; Community Development Network connects education, human development and community. It creates conditions for learners, young people, volunteers, organisations and social resources to meet through meaningful activity.</p><p>Sky First is voluntary and non-profit. It does not present itself as a government agency, a business or an independent legal entity.</p></section><section id="vision"><h2>Vision &amp; mission</h2><p>Sky First aims to build an ecosystem that connects opportunities to learn, experience and contribute. Its mission is to expand learning opportunities, create practical experience for young people and connect people with appropriate resources.</p></section><section id="principles"><h2>Five operating principles</h2><div class="principles"><article><b>01 · Voluntary</b><p>Participation fits each person’s circumstances and capacity.</p></article><article><b>02 · Non-profit</b><p>Education and community value come first.</p></article><article><b>03 · Transparency</b><p>Relevant public information is communicated clearly.</p></article><article><b>04 · Equality &amp; respect</b><p>We respect difference and foster a healthy environment.</p></article><article><b>05 · Community responsibility</b><p>Activities should create practical value for learners and community.</p></article></div></section><section id="transparency"><h2>Organisational transparency</h2><p>Sky First operates as a network with its own direction and processes; this does not mean it is an independent legal entity. Where an activity needs an appropriate legal party, the Network does not substitute a status it does not hold.</p></section>','About | SKY FIRST NETWORK','Identity, vision, mission, principles and transparency of Sky First Network.','published',1,CURRENT_TIMESTAMP),
('activities','en','hoat-dong','Programmes & Activities','Five connected areas of activity, programmes, classes and the Sky First journey.','<section><h2>Five connected areas</h2><div class="card-grid"><article><h3>Education &amp; community learning</h3><p>Classes, learning resources, academic activities and learner support.</p></article><article><h3>Youth development</h3><p>Practical experience in communication, organisation and responsibility.</p></article><article><h3>Volunteering &amp; community</h3><p>Connecting capacity for contribution with appropriate community needs.</p></article><article><h3>Connection &amp; collaboration</h3><p>Working with people, projects, education organisations and businesses where appropriate.</p></article><article><h3>Knowledge communication</h3><p>Sharing verified knowledge, opportunity and activity stories.</p></article></div></section><section id="programmes"><h2>Programmes &amp; classes</h2><p>Information appears only after its status, contact point and content have been confirmed.</p></section><section id="journey"><h2>Sky First journey</h2><p>The journey is presented through confirmed milestones only. It began with free community education in 2025 and continues by building a sustainable network foundation.</p></section>','Activities | SKY FIRST NETWORK','Areas, programmes and journey of Sky First.','published',1,CURRENT_TIMESTAMP),
('units','en','don-vi','Affiliated Unit','Specialist space operating under the shared direction of Sky First Network.','<section id="english-club"><p class="eyebrow">AFFILIATED UNIT</p><div class="unit-profile"><img src="/assets/branding/sfec-logo.png" alt="The Sky First English Club"><div><h2>The Sky First English Club</h2><p>This confirmed unit focuses on community English education, classes, learning materials, learner support and volunteer teaching.</p><p>It has its own specialist scope while following the shared coordination direction of Sky First Network.</p></div></div></section>','Affiliated Unit | SKY FIRST NETWORK','Confirmed affiliated unit of Sky First Network.','published',1,CURRENT_TIMESTAMP),
('participate','en','tham-gia','Participate with Sky First','Choose the right route before sending information to the appropriate contact point.','<section id="core-team"><h2>Core Team</h2><p>For core people who support operations, systems and programme development. Recruitment only appears when officially open.</p></section><section id="volunteer"><h2>Volunteer</h2><p>Each programme has its own requirements and form; there is no one oversized form for every volunteer role.</p></section><section id="learner"><h2>Learner</h2><p>Learners register through the relevant programme when registration is open.</p></section>','Participate | SKY FIRST NETWORK','Official ways to participate with Sky First.','published',1,CURRENT_TIMESTAMP),
('collaboration','en','hop-tac','Collaboration & Partnership','Connect expertise, programmes, communication and suitable resources.','<p>Sky First receives collaboration proposals for co-organised programmes, professional support, communication/community connection and suitable resource support. Each proposal is considered according to direction, resources and practical scope.</p>','Collaboration | SKY FIRST NETWORK','Collaboration and partnership with Sky First.','published',1,CURRENT_TIMESTAMP),
('library','en','thu-vien','Library','Images, documents and materials approved for public access.','<section id="images"><h2>Image library</h2><p>Activity images are organised by education, team and volunteering, programmes and community, events, and communications. Only images with appropriate rights may appear.</p></section><section id="documents"><h2>Public documents</h2><p>Only approved public profiles, guides, forms, communications materials, reports and shareable learning materials are published.</p></section>','Library | SKY FIRST NETWORK','Public images and documents from Sky First.','published',1,CURRENT_TIMESTAMP),
('systems','en','he-thong','Sky First Systems','Operational portals connected to the central website.','<p>Digital portals support the ecosystem and are not affiliated units. Each opens in a new tab and has a clear purpose and audience.</p>','Systems | SKY FIRST NETWORK','Sky First system portals.','published',1,CURRENT_TIMESTAMP),
('contact','en','lien-he','Contact & Office','Send an enquiry to the right official Sky First contact point.','<div class="contact-cards"><article><h2>Official contact channels</h2><p><a href="mailto:skyfirst.ec@gmail.com">skyfirst.ec@gmail.com</a><br><a href="mailto:hotro.sfn@gmail.com">hotro.sfn@gmail.com</a><br>Hotline/Zalo: 0924 910 210</p></article><article><h2>Safety notice</h2><p>Sky First never asks for passwords, OTP codes or sign-in details by email, public form or message.</p></article></div>','Contact | SKY FIRST NETWORK','Official Sky First contact channels.','published',1,CURRENT_TIMESTAMP),
('sponsorship','en','tai-tro-dong-hanh','Sponsorship & Partnership','Resource-receiving information is published only after official verification.','<p>Sky First publishes receiving accounts, QR codes and contact points only after verification. Do not use an account or QR outside this channel.</p><div class="notice"><strong>Awaiting verified publication.</strong><br>When bank, BIN, account number and account holder have all been confirmed, the CMS creates a VietQR from those details.</div>','Sponsorship | SKY FIRST NETWORK','Official sponsorship channel.','published',1,CURRENT_TIMESTAMP);
