CREATE INDEX IF NOT EXISTS idx_pages_public ON pages(lang,status,public,slug);
CREATE INDEX IF NOT EXISTS idx_posts_public ON posts(lang,status,public,published_at);
CREATE INDEX IF NOT EXISTS idx_programs_public ON programs(status,public,sort_order);
CREATE INDEX IF NOT EXISTS idx_classes_public ON classes(status,public);
CREATE INDEX IF NOT EXISTS idx_activities_public ON activities(status,public,start_at);
CREATE INDEX IF NOT EXISTS idx_units_public ON site_units(status,public,sort_order);
CREATE INDEX IF NOT EXISTS idx_team_public ON team_members(status,public,sort_order);
CREATE INDEX IF NOT EXISTS idx_partners_public ON site_partners(relationship_status,public,sort_order);
CREATE INDEX IF NOT EXISTS idx_albums_public ON albums(status,public,created_at);
CREATE INDEX IF NOT EXISTS idx_media_album ON site_media(album_id,public,created_at);
CREATE INDEX IF NOT EXISTS idx_documents_public ON documents(status,public,published_at);
CREATE INDEX IF NOT EXISTS idx_menus_location ON site_menus(location,lang,visible,parent_id,sort_order);
CREATE INDEX IF NOT EXISTS idx_forms_status ON site_forms(status,form_type,created_at);
CREATE INDEX IF NOT EXISTS idx_audit_created ON site_audit_log(created_at,admin_id);
CREATE INDEX IF NOT EXISTS idx_sessions_expiry ON site_sessions(expires_at,admin_id);
CREATE INDEX IF NOT EXISTS idx_cert_status ON site_certificates(status,issue_date);
CREATE INDEX IF NOT EXISTS idx_rate_window ON rate_limits(window_started_at);
CREATE UNIQUE INDEX IF NOT EXISTS idx_languages_one_default ON site_languages(is_default) WHERE is_default=1;
