CREATE TABLE IF NOT EXISTS site_ui_strings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  lang TEXT NOT NULL,
  key TEXT NOT NULL,
  value TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published','hidden','archived')),
  created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(lang,key),
  FOREIGN KEY(lang) REFERENCES site_languages(code)
);
CREATE INDEX IF NOT EXISTS idx_ui_strings_lang ON site_ui_strings(lang,status,key);

INSERT OR IGNORE INTO site_ui_strings(lang,key,value,status) VALUES
('vi','footer.explore','Khám phá','published'),
('vi','footer.join','Tham gia','published'),
('vi','footer.systems','Hệ thống Sky First','published'),
('vi','footer.contact','Liên hệ','published'),
('vi','news.eyebrow','Tin tức & Hoạt động','published'),
('vi','news.title','Cập nhật từ Sky First','published'),
('vi','news.read_more','Đọc tiếp →','published'),
('vi','news.empty','Chưa có bài viết công khai.','published'),
('vi','home.updates','Cập nhật','published'),
('vi','home.latest_news','Tin tức & hoạt động mới','published'),
('vi','home.view_all','Xem tất cả →','published'),
('vi','home.news_empty','Tin tức sẽ xuất hiện tự động khi được xuất bản từ Sky First Admin.','published'),
('vi','home.units','Đơn vị trực thuộc','published'),
('vi','home.units_title','Không gian chuyên môn của Sky First','published'),
('vi','home.learn_more','Tìm hiểu →','published'),
('vi','home.systems','Hệ thống Sky First','published'),
('vi','home.systems_title','Các cổng số đang vận hành','published'),
('vi','common.home','Về Trang chủ','published'),
('vi','common.not_found_title','Không tìm thấy nội dung','published'),
('vi','common.not_found_body','Trang bạn yêu cầu không tồn tại hoặc chưa được công khai.','published'),
('vi','certificate.eyebrow','Xác thực Sky First','published'),
('vi','certificate.title','Tra cứu Giấy chứng nhận','published'),
('vi','certificate.lead','Nguồn tra cứu tập trung cho Giấy chứng nhận trong hệ sinh thái Sky First.','published'),
('vi','certificate.query_label','Mã GCN hoặc mã xác thực','published'),
('vi','certificate.query_placeholder','Nhập mã cần tra cứu','published'),
('vi','certificate.search','Tra cứu','published'),
('vi','certificate.not_found','Không tìm thấy Giấy chứng nhận phù hợp. Kiểm tra lại mã đã nhập.','published'),
('vi','contact.eyebrow','Gửi liên hệ','published'),
('vi','contact.title','Liên hệ với Sky First','published'),
('vi','contact.name','Họ và tên','published'),
('vi','contact.email','Email','published'),
('vi','contact.phone','Số điện thoại','published'),
('vi','contact.organization','Tổ chức/Đơn vị','published'),
('vi','contact.message','Nội dung','published'),
('vi','contact.consent','Tôi đồng ý để Sky First sử dụng thông tin này nhằm liên hệ và xử lý đề nghị.','published'),
('vi','contact.submit','Gửi liên hệ','published'),
('vi','translation.fallback','Bản dịch tương ứng chưa được xuất bản; hệ thống đang hiển thị nội dung ở ngôn ngữ dự phòng.','published');
