-- Published English CMS content for the two-language production website.
INSERT OR REPLACE INTO pages(translation_group,lang,slug,title,excerpt,body_html,status,public,seo_title,seo_description,published_at) VALUES
('page:home','en','','Home','Official information portal of Sky First Network.','<section class="hero"><div class="container hero-grid"><div><span class="kicker">SKY FIRST NETWORK</span><h1>Education for growth.<br/>Connection for impact.</h1><p class="lead">Sky First Education &amp; Community Development Network connects learners, young people, volunteers and social resources to create meaningful opportunities for learning, experience and contribution.</p><div class="actions"><a class="btn primary" href="/en/gioi-thieu">Explore Sky First</a><a class="btn" href="/en/tham-gia">Participate with Sky First</a></div></div><div class="hero-card"><img alt="Sky First Network" src="/assets/branding/sky-first-main-logo.png"/><div class="hero-note"><b>SKY FIRST NETWORK</b><span>Education &amp; Community Development</span></div></div></div></section>','published',1,'Sky First Network | Education · Culture · Community','Official information portal of Sky First Network.',CURRENT_TIMESTAMP),
('page:gioi-thieu','en','gioi-thieu','About Sky First Network','About Sky First Network.','<div class="eyebrow">ABOUT</div><h1>What is Sky First Network?</h1><p class="lead">Sky First Education &amp; Community Development Network is a network for education, human development and community connection.</p><h2>A shared space to learn, experience and contribute</h2><p>Sky First Network helps young people learn, build capability, take organisational roles and use their knowledge and skills to create positive value for the community.</p><div class="quote">The core of Sky First Network is connection: learners with learning opportunities; volunteers with meaningful contribution; young people with experience; and organisations with complementary resources.</div>','published',1,'About Sky First Network','About Sky First Education & Community Development Network.',CURRENT_TIMESTAMP),
('page:linh-vuc','en','linh-vuc','Areas of Activity','Five connected areas of activity.','<div class="eyebrow">ACTIVITIES</div><h1>Five priority areas</h1><div class="cards two"><div class="card"><h3>Education &amp; community learning</h3><p>Classes, academic activities, learner support, learning resources and knowledge sharing.</p></div><div class="card"><h3>Youth development</h3><p>Learning through teamwork, communication, organising and practical responsibility.</p></div><div class="card"><h3>Volunteering &amp; community</h3><p>Connecting people who can contribute with appropriate community needs.</p></div><div class="card"><h3>Connection &amp; collaboration</h3><p>Appropriate collaboration with individuals, groups and organisations.</p></div><div class="card"><h3>Knowledge communication</h3><p>Sharing knowledge, opportunities and verified stories of activity.</p></div></div>','published',1,'Areas of Activity | Sky First Network','Priority areas of Sky First Network.',CURRENT_TIMESTAMP),
('page:don-vi','en','don-vi','Affiliated Unit','Confirmed affiliated unit of Sky First Network.','<div class="eyebrow">AFFILIATED UNIT</div><h1>Specialist space of Sky First Network</h1><p class="lead">An affiliated unit operates within its specialist scope under the shared direction of Sky First Network.</p><div class="cards two"><a class="unit" href="/en/sfec"><img src="/assets/branding/sfec-logo.png" alt="The Sky First English Club"><div><small>AFFILIATED UNIT</small><h3>The Sky First English Club</h3><p>English, community education, classes, learning materials and learner support.</p><b>View unit profile →</b></div></a></div>','published',1,'Affiliated Unit | Sky First Network','Confirmed affiliated unit of Sky First Network.',CURRENT_TIMESTAMP),
('page:tham-gia','en','tham-gia','Participate with Sky First','Choose the appropriate way to participate.','<div class="eyebrow">PARTICIPATE</div><h1>Everyone has a way to contribute</h1><p class="lead">Choose the right direction before opening the relevant form or portal.</p><div class="cards two"><a class="card linkcard" href="/en/core-team"><h3>Core Team</h3><p>Core people supporting operations and programmes.</p></a><a class="card linkcard" href="/en/tinh-nguyen-vien"><h3>Volunteer</h3><p>Contribute to programmes or with relevant expertise.</p></a><a class="card linkcard" href="/en/nguoi-hoc"><h3>Learner</h3><p>Join classes, workshops and educational programmes.</p></a><a class="card linkcard" href="/en/hop-tac"><h3>Professional collaboration</h3><p>Experts and organisations can connect with relevant programmes.</p></a></div>','published',1,'Participate | Sky First Network','Ways to participate with Sky First Network.',CURRENT_TIMESTAMP),
('page:tin-tuc','en','tin-tuc','News & Activities','Official news and activity updates.','<div class="eyebrow">NEWS &amp; ACTIVITIES</div><h1>Official information channel</h1><p>Only verified articles, images, partners and documents are published. Information that is not confirmed is not presented as an accomplished activity.</p>','published',1,'News & Activities | Sky First Network','Official updates from Sky First Network.',CURRENT_TIMESTAMP),
('page:tra-cuu','en','tra-cuu','Verification','Verify published records.','<div class="eyebrow">SKY FIRST VERIFICATION</div><h1>Certificate and achievement verification</h1><p class="lead">Enter a certificate or reference code to check its status in the central Sky First Network data source.</p>','published',1,'Verification | Sky First Network','Certificate and achievement verification.',CURRENT_TIMESTAMP),
('page:lien-he','en','lien-he','Contact','Official contacts of Sky First Network.','<div class="eyebrow">CONTACT</div><h1>Connect with Sky First Network</h1><p class="lead">The following channels are official contact points for Sky First Education &amp; Community Development Network.</p><div class="note">Sky First Network never requests passwords, OTP codes or sign-in details by email, public form or message.</div>','published',1,'Contact | Sky First Network','Official contact information.',CURRENT_TIMESTAMP);

INSERT OR REPLACE INTO site_menus(id,location,label,url,parent_id,sort_order,visible,new_tab,lang) VALUES
(301,'header','Home','/home',NULL,10,1,0,'en'),
(302,'header','About','/gioi-thieu',NULL,20,1,0,'en'),
(303,'header','Activities','/linh-vuc',NULL,30,1,0,'en'),
(304,'header','Affiliated Unit','/don-vi',NULL,40,1,0,'en'),
(305,'header','Participate','/tham-gia',NULL,50,1,0,'en'),
(307,'header','News','/tin-tuc',NULL,70,1,0,'en'),
(309,'header','Verification','/tra-cuu',NULL,90,1,0,'en'),
(310,'header','Contact','/lien-he',NULL,100,1,0,'en'),
(401,'footer_quick','Home','/home',NULL,10,1,0,'en'),
(402,'footer_quick','About Sky First Network','/gioi-thieu',NULL,20,1,0,'en'),
(403,'footer_quick','Activities','/linh-vuc',NULL,30,1,0,'en'),
(404,'footer_quick','News','/tin-tuc',NULL,40,1,0,'en'),
(411,'footer_join','Verification','/tra-cuu',NULL,10,1,0,'en'),
(412,'footer_join','Sponsorship & Partnership','/tai-tro-dong-hanh',NULL,20,1,0,'en'),
(413,'footer_join','Participate','/tham-gia',NULL,30,1,0,'en');
