-- Complete public interface strings for the two supported languages.
INSERT OR REPLACE INTO site_ui_strings(lang,key,value,status) VALUES
('en','footer.explore','Explore','published'),
('en','footer.join','Join','published'),
('en','footer.systems','Sky First systems','published'),
('en','footer.contact','Contact','published'),
('en','home.updates','Updates','published'),
('en','home.latest_news','Latest news & activities','published'),
('en','home.view_all','View all →','published'),
('en','home.news_empty','Official news will appear here after publication.','published'),
('en','home.units','Affiliated unit','published'),
('en','home.units_title','Sky First professional space','published'),
('en','home.learn_more','Learn more →','published'),
('en','home.systems','Sky First systems','published'),
('en','home.systems_title','Digital portals in operation','published'),
('en','news.eyebrow','News & activities','published'),
('en','news.title','Updates from Sky First','published'),
('en','news.read_more','Read more →','published'),
('en','news.empty','No public article has been published yet.','published'),
('en','common.home','Back to home','published'),
('en','common.not_found_title','Content not found','published'),
('en','common.not_found_body','The requested page does not exist or is not public.','published'),
('en','certificate.eyebrow','Sky First system verification','published'),
('en','certificate.title','Achievements & certificates lookup','published'),
('en','certificate.lead','The central lookup at skyfirst.io.vn for published achievements and certificates issued by every Sky First website, portal and application.','published'),
('en','certificate.query_label','Achievement, certificate or verification code','published'),
('en','certificate.query_placeholder','Enter a code issued by a Sky First system','published'),
('en','certificate.search','Look up','published'),
('en','certificate.not_found','No matching published record was found. Please check the code.','published'),
('en','translation.fallback','The corresponding translation is not published; a fallback language is being displayed.','published');
