import React,{useMemo,useState} from 'react';
import {Plus,Trash2,Save,Search} from 'lucide-react';

type Row={id:string;title:string;subtitle?:string;status?:string;note?:string};
const defaults:Record<string,Row[]>={
 comments:[],registrations:[],contacts:[],
 partners:[{id:'partner-sample',title:'[Nhập tên đơn vị]',subtitle:'Đối tác / Đơn vị đồng hành / Đơn vị phối hợp / Nhà tài trợ',status:'Ẩn',note:'Bản ghi mẫu. Chỉ bật công khai khi đã xác nhận và được phép sử dụng tên/logo.'}],
 contributions:[{id:'contribution-sample',title:'Chương trình đóng góp mẫu',subtitle:'Tài trợ / Đóng góp / Quyên góp',status:'Tắt',note:'Không công khai số tài khoản, QR hoặc lời kêu gọi chuyển tiền cho tới khi thông tin tiếp nhận được xác nhận.'}],
 media:[{id:'logo-main',title:'Logo Sky First Network',subtitle:'/brand/sky-first-network-web.png',status:'Công khai'},{id:'logo-sfec',title:'Logo Câu lạc bộ Tiếng Anh The Sky First',subtitle:'/brand/the-sky-first-english-club-web.png',status:'Công khai'},{id:'logo-nhn',title:'Logo Nhà Hán Ngữ',subtitle:'/brand/nha-han-ngu-web.jpg',status:'Công khai'}],
 menus:[{id:'m1',title:'Giới thiệu',subtitle:'Menu cha • có thể thêm menu con',status:'Hiển thị'},{id:'m2',title:'Chương trình',status:'Hiển thị'},{id:'m3',title:'Đơn vị trực thuộc',status:'Hiển thị'},{id:'m4',title:'Tin tức & Hoạt động',status:'Hiển thị'},{id:'m5',title:'Tra cứu Giấy chứng nhận',status:'Hiển thị'},{id:'m6',title:'Tham gia',status:'Hiển thị'},{id:'m7',title:'Hợp tác',status:'Hiển thị'},{id:'m8',title:'Liên hệ',status:'Hiển thị'}],
 certificates:[{id:'cert-info',title:'Kho Giấy chứng nhận trung tâm',subtitle:'Nhận dữ liệu từ các hệ thống/website cấp và phục vụ tra cứu tập trung.',status:'Sẵn sàng cấu hình',note:'Website trung tâm không trực tiếp cấp mặc định. Trung tâm có quyền thu hồi, khóa và quản lý trạng thái; bản ghi thu hồi không bị xóa khỏi lịch sử.'}],
 logs:[]
};
const labels:Record<string,string>={comments:'Bình luận bài viết',registrations:'Đăng ký',contacts:'Liên hệ & đề xuất hợp tác',partners:'Đối tác & Đơn vị đồng hành',contributions:'Tài trợ, Đóng góp & Quyên góp',media:'Thư viện Media',menus:'Menu website',certificates:'Giấy chứng nhận trung tâm',logs:'Nhật ký hoạt động'};
export const AdminRecordsManager:React.FC<{kind:string,onShowToast:(m:string)=>void}>=({kind,onShowToast})=>{
 const key=`sfn_admin_records_${kind}`; const [rows,setRows]=useState<Row[]>(()=>{try{return JSON.parse(localStorage.getItem(key)||'null')||defaults[kind]||[]}catch{return defaults[kind]||[]}}); const [q,setQ]=useState(''); const [edit,setEdit]=useState<Row|null>(null);
 const persist=(n:Row[])=>{setRows(n);localStorage.setItem(key,JSON.stringify(n))}; const filtered=useMemo(()=>rows.filter(r=>(r.title+' '+(r.subtitle||'')).toLowerCase().includes(q.toLowerCase())),[rows,q]);
 const save=()=>{if(!edit||!edit.title.trim())return; const n=rows.some(r=>r.id===edit.id)?rows.map(r=>r.id===edit.id?edit:r):[edit,...rows];persist(n);setEdit(null);onShowToast('Đã lưu thay đổi.');};
 return <div className="space-y-4"><div className="flex flex-col sm:flex-row gap-3 justify-between"><div><h2 className="text-xl font-black text-slate-900">{labels[kind]||'Quản lý dữ liệu'}</h2><p className="text-xs text-slate-500 mt-1">Dữ liệu có thể thêm, sửa, xóa, ẩn/hiện và cập nhật khi cần.</p></div><button onClick={()=>setEdit({id:`${kind}-${Date.now()}`,title:'',status:'Bản nháp'})} className="px-4 py-2 bg-[#0F2B5B] text-white rounded-xl text-sm font-bold flex items-center gap-2"><Plus size={16}/>Thêm mới</button></div>
 <div className="bg-white border rounded-2xl overflow-hidden"><div className="p-3 border-b flex items-center gap-2"><Search size={16} className="text-slate-400"/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Tìm kiếm..." className="w-full outline-none text-sm"/></div>{filtered.length===0?<div className="p-10 text-center text-sm text-slate-500">Chưa có dữ liệu.</div>:<div className="divide-y">{filtered.map(r=><div key={r.id} className="p-4 flex gap-3 items-start"><div className="flex-1"><button onClick={()=>setEdit(r)} className="font-bold text-slate-900 hover:text-sky-700 text-left">{r.title}</button>{r.subtitle&&<div className="text-xs text-slate-500 mt-1">{r.subtitle}</div>}{r.note&&<div className="text-xs text-slate-600 mt-2">{r.note}</div>}</div><span className="text-[11px] px-2 py-1 rounded-lg bg-slate-100 text-slate-600">{r.status||'—'}</span><button onClick={()=>{persist(rows.filter(x=>x.id!==r.id));onShowToast('Đã xóa bản ghi.')}} className="p-2 text-slate-400 hover:text-rose-600"><Trash2 size={16}/></button></div>)}</div>}</div>
 {edit&&<div className="fixed inset-0 bg-slate-950/50 z-50 flex items-center justify-center p-4"><div className="bg-white rounded-2xl p-6 w-full max-w-xl"><h3 className="font-black text-lg mb-4">Chỉnh sửa</h3><div className="space-y-3"><input value={edit.title} onChange={e=>setEdit({...edit,title:e.target.value})} className="w-full border rounded-xl p-3" placeholder="Tên / Tiêu đề"/><input value={edit.subtitle||''} onChange={e=>setEdit({...edit,subtitle:e.target.value})} className="w-full border rounded-xl p-3" placeholder="Mô tả ngắn / Phân loại"/><input value={edit.status||''} onChange={e=>setEdit({...edit,status:e.target.value})} className="w-full border rounded-xl p-3" placeholder="Trạng thái"/><textarea value={edit.note||''} onChange={e=>setEdit({...edit,note:e.target.value})} rows={5} className="w-full border rounded-xl p-3" placeholder="Nội dung / Ghi chú"/></div><div className="mt-5 flex justify-end gap-2"><button onClick={()=>setEdit(null)} className="px-4 py-2 border rounded-xl">Hủy</button><button onClick={save} className="px-4 py-2 bg-[#0F2B5B] text-white rounded-xl font-bold flex items-center gap-2"><Save size={16}/>Lưu</button></div></div></div>}
 </div>
}
