import React, { useState } from 'react';
import { ArrowLeft, Mail, Lock, X } from 'lucide-react';
import { AdminUser } from '../../types';
import { signInWithGoogleReal, signInWithEmailPasswordReal, logoutFirebase, isFirebaseConfigured } from '../../lib/firebaseAuth';

interface Props { adminUsers: AdminUser[]; onLoginSuccess:(u:AdminUser)=>void; onNavigateHome:()=>void; onShowToast:(m:string)=>void; }
export const AdminLogin: React.FC<Props> = ({adminUsers,onLoginSuccess,onNavigateHome,onShowToast}) => {
 const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [loading,setLoading]=useState(false); const [error,setError]=useState(''); const [forgot,setForgot]=useState(false);
 const authorize=async (fb:any) => { const e=(fb.email||'').toLowerCase().trim(); const matched=adminUsers.find(u=>u.email.toLowerCase().trim()===e&&u.status==='active'); const bootstrap=(import.meta.env.VITE_INITIAL_ADMIN_EMAIL||'').toLowerCase().trim(); if(!matched && e!==bootstrap){await logoutFirebase(); throw new Error('Tài khoản này chưa được cấp quyền quản trị website Sky First Network.');} const u:AdminUser=matched||{id:fb.uid||'initial-admin',name:fb.displayName||'Quản trị viên ban đầu',email:e,role:'developer',status:'active',createdAt:new Date().toISOString(),lastLogin:new Date().toISOString()}; localStorage.setItem('sfn_admin_session',JSON.stringify(u)); onLoginSuccess(u); onShowToast('Đăng nhập quản trị thành công.'); };
 const google=async()=>{setLoading(true);setError('');try{if(!isFirebaseConfigured)throw new Error('Chưa cấu hình Firebase Authentication.');await authorize(await signInWithGoogleReal());}catch(e:any){setError(e.message||'Không thể đăng nhập.');}finally{setLoading(false)}};
 const login=async(e:React.FormEvent)=>{e.preventDefault();setLoading(true);setError('');try{await authorize(await signInWithEmailPasswordReal(email,password));}catch(err:any){setError(err?.code==='auth/invalid-credential'?'Email hoặc mật khẩu không chính xác.':err.message||'Không thể đăng nhập.');}finally{setLoading(false)}};
 return <div className="min-h-screen bg-slate-50 flex items-center justify-center p-4"><div className="w-full max-w-md">
  <div className="bg-white border border-slate-200 rounded-3xl shadow-xl p-8">
   <div className="flex justify-center mb-5"><div className="bg-white rounded-2xl p-2 border border-slate-100"><img src="/brand/sky-first-network.png" className="h-20 w-auto object-contain" alt="Sky First Network"/></div></div>
   <h1 className="text-2xl font-black text-center text-slate-900">Đăng nhập quản trị</h1><p className="text-sm text-slate-500 text-center mt-2 mb-6">Sky First Network</p>
   {error&&<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}
   <form onSubmit={login} className="space-y-4"><label className="block text-sm font-semibold">Email<div className="mt-1 flex items-center border rounded-xl px-3"><Mail size={17} className="text-slate-400"/><input value={email} onChange={e=>setEmail(e.target.value)} type="email" required className="w-full p-3 outline-none" placeholder="ten@gmail.com"/></div></label><label className="block text-sm font-semibold">Mật khẩu<div className="mt-1 flex items-center border rounded-xl px-3"><Lock size={17} className="text-slate-400"/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" required className="w-full p-3 outline-none"/></div></label><button disabled={loading} className="w-full rounded-xl bg-[#0F2B5B] text-white py-3 font-bold">{loading?'Đang đăng nhập...':'Đăng nhập'}</button></form>
   <button onClick={()=>setForgot(true)} className="w-full mt-3 text-sm font-semibold text-sky-700">Quên mật khẩu?</button><div className="my-5 flex items-center gap-3 text-xs text-slate-400"><span className="h-px bg-slate-200 flex-1"/>hoặc<span className="h-px bg-slate-200 flex-1"/></div><button onClick={google} disabled={loading} className="w-full rounded-xl border border-slate-300 py-3 font-bold text-sm">Tiếp tục với Google</button>
  </div><button onClick={onNavigateHome} className="mx-auto mt-5 flex items-center gap-2 text-sm text-slate-500"><ArrowLeft size={15}/>Quay lại website</button>
  {forgot&&<div className="fixed inset-0 bg-slate-950/50 flex items-center justify-center p-4 z-50"><div className="bg-white max-w-md rounded-2xl p-6 relative"><button onClick={()=>setForgot(false)} className="absolute right-4 top-4"><X size={18}/></button><h2 className="text-xl font-black mb-3">Quên mật khẩu?</h2><p className="text-sm text-slate-600 leading-6">Nếu bạn quên mật khẩu hoặc không thể truy cập tài khoản quản trị, vui lòng liên hệ Sky First Network để được xác minh và hỗ trợ cấp lại quyền truy cập. Vì lý do bảo mật, mật khẩu tài khoản quản trị không được khôi phục tự động.</p><div className="mt-4 text-sm"><b>Email hỗ trợ:</b> hotro.sfn@gmail.com<br/><b>Zalo:</b> 0924 910 210</div><button onClick={()=>setForgot(false)} className="mt-5 w-full rounded-xl bg-[#0F2B5B] text-white py-2.5 font-bold">Đóng</button></div></div>}
 </div></div>
}
