import React,{useState} from 'react';
import {ArrowLeft,Mail,Lock,X} from 'lucide-react';
import {AdminUser} from '../../types';
import {getAdminProfile,logoutFirebase,signInWithEmailPasswordReal} from '../../lib/firebaseAuth';
interface Props{adminUsers:AdminUser[];addAdminUser:(u:AdminUser)=>void;onLoginSuccess:(u:AdminUser)=>void;onNavigateHome:()=>void;onShowToast:(m:string)=>void;}
export const AdminLogin:React.FC<Props>=({onLoginSuccess,onNavigateHome,onShowToast})=>{
 const[email,setEmail]=useState('');const[password,setPassword]=useState('');const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[forgot,setForgot]=useState(false);
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(loading)return;setLoading(true);setError('');try{const fb=await signInWithEmailPasswordReal(email,password);const profile=await getAdminProfile(fb.uid) as AdminUser|null;if(!profile||profile.status!=='active'){await logoutFirebase();throw new Error('Tài khoản này chưa được cấp quyền quản trị website.')}onLoginSuccess({...profile,lastLogin:new Date().toISOString()});onShowToast('Đăng nhập quản trị thành công.')}catch(err:any){const code=err?.code||'';setError(code==='auth/invalid-credential'?'Email hoặc mật khẩu không chính xác.':String(err?.message||'Không thể đăng nhập.'))}finally{setLoading(false)}};
 return <div className="min-h-screen bg-slate-50 flex items-center justify-center p-4"><div className="w-full max-w-md"><div className="bg-white border border-slate-200 rounded-3xl shadow-xl p-8"><div className="flex justify-center mb-5"><img src="/brand/sky-first-network-web.png" className="h-20 w-auto object-contain" alt="Sky First Network"/></div><h1 className="text-2xl font-black text-center text-slate-900">Đăng nhập quản trị</h1><p className="text-sm text-slate-500 text-center mt-2 mb-6">Sky First Network</p>{error&&<div className="mb-4 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</div>}<form onSubmit={submit} className="space-y-4"><label className="block text-sm font-semibold">Email<div className="mt-1 flex items-center border rounded-xl px-3"><Mail size={17}/><input value={email} onChange={e=>setEmail(e.target.value)} type="email" autoComplete="username" required className="w-full p-3 outline-none"/></div></label><label className="block text-sm font-semibold">Mật khẩu<div className="mt-1 flex items-center border rounded-xl px-3"><Lock size={17}/><input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="current-password" required className="w-full p-3 outline-none"/></div></label><button disabled={loading} className="w-full rounded-xl bg-[#0F2B5B] text-white py-3 font-bold disabled:opacity-60">{loading?'Đang đăng nhập...':'Đăng nhập'}</button></form><button onClick={()=>setForgot(true)} className="w-full mt-3 text-sm font-semibold text-sky-700">Quên mật khẩu?</button></div><button onClick={onNavigateHome} className="mx-auto mt-5 flex items-center gap-2 text-sm text-slate-500"><ArrowLeft size={15}/>Quay lại website</button>{forgot&&<div className="fixed inset-0 bg-slate-950/50 flex items-center justify-center p-4 z-50"><div className="bg-white max-w-md rounded-2xl p-6 relative"><button onClick={()=>setForgot(false)} className="absolute right-4 top-4"><X size={18}/></button><h2 className="text-xl font-black mb-3">Quên mật khẩu?</h2><p className="text-sm text-slate-600">Vui lòng liên hệ Sky First Network để được xác minh và hỗ trợ tài khoản quản trị.</p><button onClick={()=>setForgot(false)} className="mt-5 w-full rounded-xl bg-[#0F2B5B] text-white py-2.5 font-bold">Đóng</button></div></div>}</div></div>
}
