import { esc } from '../core/escape.js';
import { href, panel } from './layout.js';
const T = (l,a,b) => l==='en'?b:a;
const btn = (l,url,label) => `<a class="button" href="${href(url,l)}">${label}</a>`;
export function home(locale, posts=[]) { const t=(a,b)=>T(locale,a,b); return `
<section class="hero"><div><p class="eyebrow">SKY FIRST NETWORK</p><h1>${t('Giáo dục để phát triển cùng cộng đồng.','Education for development with community.')}</h1><p class="lead">${t('Một không gian kết nối học tập, văn hóa, trải nghiệm và đóng góp có trách nhiệm.','A space connecting learning, culture, experience and responsible contribution.')}</p><div class="actions">${btn(locale,'/gioi-thieu',t('Tìm hiểu Sky First','Discover Sky First'))}${btn(locale,'/tra-cuu',t('Tra cứu tại Sky First','Verify at Sky First'))}</div></div><aside class="hero-card"><p>${t('Định hướng chung','Shared direction')}</p><strong>${t('Phát triển từ tri thức, văn hóa và cộng đồng.','Developed through knowledge, culture and community.')}</strong><span>${t('Thông tin chỉ được công bố khi đã xác nhận.','Information is published only when confirmed.')}</span></aside></section>
<section class="section"><p class="eyebrow">${t('LĨNH VỰC HOẠT ĐỘNG','ACTIVITY FIELDS')}</p><div class="section-heading"><h2>${t('Năm trụ cột kết nối với nhau','Five connected pillars')}</h2><p>${t('Định hướng cho các chương trình và hoạt động của Mạng lưới.','Directions for Network programmes and activities.')}</p></div><div class="grid five">${[['01',t('Giáo dục','Education'),t('Lớp học, học liệu, học thuật và hỗ trợ người học.','Classes, learning resources, academic activity and learner support.')],['02',t('Phát triển người trẻ','Youth development'),t('Học qua trải nghiệm, trách nhiệm và công việc thực tế.','Learning through experience, responsibility and real work.')],['03',t('Tình nguyện & Cộng đồng','Volunteering & community'),t('Kết nối năng lực đóng góp với nhu cầu phù hợp.','Connecting contribution capacity with relevant needs.')],['04',t('Kết nối & Hợp tác','Connection & partnership'),t('Phối hợp chuyên môn, nguồn lực và chương trình.','Coordinating expertise, resources and programmes.')],['05',t('Truyền thông','Communication'),t('Lan tỏa tri thức, cơ hội và câu chuyện hoạt động.','Sharing knowledge, opportunities and activity stories.')]].map(x=>`<article class="card pillar"><b>${x[0]}</b><h3>${x[1]}</h3><p>${x[2]}</p></article>`).join('')}</div></section>
<section class="section soft"><p class="eyebrow">${t('NGUYÊN TẮC HOẠT ĐỘNG','OPERATING PRINCIPLES')}</p><h2>${t('Năm nguyên tắc để cùng phát triển','Five principles for growing together')}</h2><div class="grid principles">${[[t('Tôn trọng','Respect'),t('Lắng nghe và tôn trọng sự khác biệt.','Listen to and respect differences.')],[t('Minh bạch','Transparency'),t('Rõ về phạm vi, đầu mối và thông tin công khai.','Clear on scope, contacts and public information.')],[t('Trách nhiệm','Responsibility'),t('Làm việc có quy trình và cam kết.','Work with process and commitment.')],[t('Hợp tác','Cooperation'),t('Kết nối đúng năng lực và nhu cầu.','Connect relevant capacity and needs.')],[t('Bền vững','Sustainability'),t('Ưu tiên mô hình có thể duy trì và kế thừa.','Prioritise models that can be sustained and continued.')]].map((x,i)=>`<article class="card principle p${i+1}"><span>0${i+1}</span><h3>${x[0]}</h3><p>${x[1]}</p></article>`).join('')}</div></section>
<section class="section split"><div><p class="eyebrow">${t('CÁC ĐƠN VỊ TRỰC THUỘC','MEMBER UNITS')}</p><h2>${t('Không gian chuyên môn của Sky First','Specialist spaces of Sky First')}</h2><p>${t('Mỗi đơn vị hoạt động trong lĩnh vực riêng, dưới định hướng chung và chỉ công bố thông tin đã xác nhận.','Each unit works in its own field under a shared direction and only confirmed information is published.')}</p></div><article class="unit-card" id="sfec"><img src="/assets/branding/sfec-logo.png" alt="The Sky First English Club"><h3>${t('Câu lạc bộ Tiếng Anh The Sky First','The Sky First English Club')}</h3><p>${t('Tiếng Anh, giáo dục cộng đồng, lớp học, học liệu và hỗ trợ người học.','English, community education, classes, learning resources and learner support.')}</p>${btn(locale,'/don-vi',t('Tìm hiểu đơn vị','Explore the unit'))}</article></section>
<section class="verify-banner"><div><p class="eyebrow">${t('XÁC THỰC SKY FIRST','SKY FIRST VERIFICATION')}</p><h2>${t('Tra cứu thành tích và giấy chứng nhận','Verify achievements and certificates')}</h2><p>${t('Tra cứu tập trung cho kết quả đã được công bố từ các website và ứng dụng của Sky First Network.','A central lookup for published results from Sky First Network websites and applications.')}</p></div>${btn(locale,'/tra-cuu',t('Tra cứu','Verify'))}</section>
<section class="section"><p class="eyebrow">${t('TIN TỨC & HOẠT ĐỘNG','NEWS & ACTIVITY')}</p><div class="section-heading"><h2>${t('Thông tin chính thức','Official information')}</h2><p>${t('Không có bài viết chưa được duyệt hoặc dữ liệu minh họa giả.','No unreviewed posts or fabricated activity data.')}</p></div>${posts.length?`<div class="grid three">${posts.map(p=>`<article class="card"><p class="meta">${esc(p.published_at||'')}</p><h3>${esc(p.title)}</h3><p>${esc(p.excerpt)}</p><a href="${href('/tin-tuc/'+p.id,locale)}">${t('Đọc bài viết','Read article')} →</a></article>`).join('')}</div>`:`<div class="empty"><strong>${t('Chưa có bài viết đã công bố','No published articles yet')}</strong><p>${t('Các tin tức sẽ xuất hiện ở đây sau khi được duyệt trong hệ thống quản trị.','News will appear here after approval in the administration system.')}</p></div>`}</section>
<section class="section split contact-strip"><div><p class="eyebrow">${t('LIÊN HỆ & ĐẦU MỐI','CONTACT & ROUTING')}</p><h2>${t('Gửi yêu cầu đến đúng ban, đơn vị','Send a request to the right team or unit')}</h2><p>${t('Biểu mẫu sẽ điều phối thư đến theo mục đích và đầu mối phụ trách.','The form routes each request by purpose and responsible contact.')}</p></div>${btn(locale,'/lien-he',t('Mở biểu mẫu liên hệ','Open contact form'))}</section>`; }
export function standard(locale,page) { return panel(T(locale,'THÔNG TIN CHÍNH THỨC','OFFICIAL INFORMATION'),esc(page.title),`<p class="lead">${esc(page.summary)}</p><article class="prose">${page.body_html}</article>`); }
export function units(locale) { return panel(T(locale,'CÁC ĐƠN VỊ TRỰC THUỘC','MEMBER UNITS'),T(locale,'Không gian chuyên môn của Sky First','Specialist spaces of Sky First'),`<p class="lead">${T(locale,'Mỗi đơn vị hoạt động trong lĩnh vực riêng, dưới định hướng chung của Sky First Network.','Each unit works in its own field under Sky First Network’s shared direction.')}</p><div class="grid two"><article class="unit-card" id="sfec"><img src="/assets/branding/sfec-logo.png" alt="The Sky First English Club"><h2>${T(locale,'Câu lạc bộ Tiếng Anh The Sky First','The Sky First English Club')}</h2><p>${T(locale,'Tiếng Anh, giáo dục cộng đồng, lớp học, học liệu và hỗ trợ người học.','English, community education, classes, learning resources and learner support.')}</p><a href="${href('/noi-dung/sfec',locale)}">${T(locale,'Xem thông tin chính thức','View official information')} →</a></article></div>`); }
export function topics(locale, topics, selected) { const title=selected?selected.question:T(locale,'Nội dung chính thức','Official content'); const body=selected?`<article class="prose topic-answer">${selected.answer_html}</article><p><a class="button" href="${href('/noi-dung',locale)}">${T(locale,'Xem toàn bộ câu hỏi','View all questions')}</a></p>`:`<div class="topic-list">${topics.map(x=>`<a href="${href('/noi-dung/'+x.slug,locale)}"><span>${String(x.number).padStart(2,'0')}</span><strong>${esc(x.question)}</strong><b>→</b></a>`).join('')}</div>`; return panel(T(locale,'HỒ SƠ NỘI DUNG','OFFICIAL CONTENT LIBRARY'),esc(title),body); }
