import React from 'react';
import { ArrowRight, GraduationCap, Users, HeartHandshake, Network, Megaphone, Award, Building2, Newspaper, ShieldCheck } from 'lucide-react';
import { PageRoute } from '../types';
import { useDataContext } from '../context/DataContext';

interface HomePageProps { onNavigate: (page: PageRoute) => void; }

export const HomePage: React.FC<HomePageProps> = ({ onNavigate }) => {
  const { programs, networkUnits, newsArticles } = useDataContext();
  const publishedPrograms = programs.filter(p=>p.isPublished!==false).slice(0,3);
  const publishedUnits = networkUnits.filter(u=>u.isPublished!==false).slice(0,2);
  const publishedNews = newsArticles.filter(n=>n.isPublished!==false).slice(0,3);
  const pillars = [
    ['Giáo dục & Đào tạo','Phát triển các hoạt động học tập, ngoại ngữ, kỹ năng và trải nghiệm giáo dục phù hợp với người trẻ.', GraduationCap],
    ['Phát triển Người trẻ','Tạo môi trường để người trẻ chủ động trải nghiệm, rèn luyện và phát triển năng lực.', Users],
    ['Tình nguyện & Cộng đồng','Thực hiện các hoạt động cộng đồng thiết thực, có định hướng và giá trị xã hội rõ ràng.', HeartHandshake],
    ['Kết nối & Hợp tác','Mở rộng kết nối giữa cá nhân, nhóm, đơn vị và các sáng kiến phù hợp.', Network],
    ['Truyền thông & Lan tỏa','Lan tỏa tri thức, câu chuyện tích cực và các hoạt động có giá trị cho cộng đồng.', Megaphone],
  ];
  const values=['Giáo dục','Cộng đồng','Trách nhiệm','Chủ động và phát triển','Kết nối và hợp tác','Bền vững'];
  return <main className="bg-white">
    <section className="relative overflow-hidden bg-[#071B3A] text-white">
      <div className="absolute inset-0 opacity-20" style={{backgroundImage:'radial-gradient(circle at 15% 20%, #30b6ff 0, transparent 28%), radial-gradient(circle at 80% 15%, #2563eb 0, transparent 24%)'}}/>
      <div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 lg:py-28 grid lg:grid-cols-[1.35fr_.65fr] gap-12 items-end">
        <div>
          <div className="inline-flex items-center gap-2 rounded-full border border-sky-300/25 bg-white/5 px-4 py-2 text-xs font-bold uppercase tracking-[.16em] text-sky-200">Mạng lưới Giáo dục & Phát triển Cộng đồng</div>
          <h1 className="mt-6 text-5xl sm:text-6xl lg:text-7xl font-black tracking-[-.05em] leading-[.98] max-w-4xl">Kết nối tri thức.<br/><span className="text-sky-300">Phát triển người trẻ.</span><br/>Lan tỏa giá trị cộng đồng.</h1>
          <p className="mt-7 max-w-2xl text-base sm:text-lg leading-8 text-slate-300">Sky First Network được xây dựng như một không gian kết nối các hoạt động giáo dục, phát triển người trẻ, tình nguyện, hợp tác và truyền thông cộng đồng.</p>
          <div className="mt-8 flex flex-wrap gap-3"><button onClick={()=>onNavigate('about')} className="px-5 py-3 rounded-xl bg-white text-[#071B3A] font-bold flex items-center gap-2">Khám phá mạng lưới <ArrowRight size={17}/></button><button onClick={()=>onNavigate('join')} className="px-5 py-3 rounded-xl border border-white/20 bg-white/5 font-bold">Tham gia cùng chúng tôi</button></div>
        </div>
        <div className="rounded-[28px] border border-white/15 bg-white/7 backdrop-blur p-6">
          <div className="text-xs uppercase tracking-[.18em] text-sky-200 font-bold">Định hướng 2026</div>
          <div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/8 p-5"><div className="text-3xl font-black">05</div><div className="text-xs text-slate-300 mt-1">Trụ cột hoạt động</div></div><div className="rounded-2xl bg-white/8 p-5"><div className="text-3xl font-black">06</div><div className="text-xs text-slate-300 mt-1">Giá trị cốt lõi</div></div></div>
          <div className="mt-4 text-sm leading-7 text-slate-300">Tập trung tái cấu trúc, chuẩn hóa hệ thống quản trị, phát triển Core Team và củng cố nền tảng số.</div>
        </div>
      </div>
    </section>

    <section className="py-20 lg:py-24"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid lg:grid-cols-[.6fr_1.4fr] gap-10 mb-10"><div className="text-xs font-black tracking-[.18em] uppercase text-[#0B5FB4]">05 trụ cột hoạt động</div><h2 className="text-4xl lg:text-5xl font-black tracking-[-.04em] text-slate-950">Năm hướng hoạt động, cùng phục vụ một mục tiêu phát triển con người và cộng đồng.</h2></div><div className="grid md:grid-cols-2 xl:grid-cols-5 border border-slate-200 rounded-[28px] overflow-hidden">{pillars.map(([title,desc,Icon],i)=><div key={String(title)} className="p-6 min-h-[270px] flex flex-col border-b xl:border-b-0 xl:border-r last:border-r-0 border-slate-200"><div className="flex justify-between text-xs text-slate-400"><span>0{i+1}</span><span className="w-10 h-10 rounded-xl bg-sky-50 text-[#0B5FB4] grid place-items-center"><Icon size={20}/></span></div><div className="mt-auto"><h3 className="font-extrabold text-lg">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{desc}</p></div></div>)}</div></div></section>

    <section className="py-20 bg-[#F5F8FC]"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex flex-col sm:flex-row sm:items-end justify-between gap-5 mb-8"><div><div className="text-xs font-black tracking-[.18em] uppercase text-[#0B5FB4]">Chương trình & hoạt động</div><h2 className="mt-3 text-4xl font-black tracking-[-.035em]">Những hoạt động đang được cập nhật</h2></div><button onClick={()=>onNavigate('programs')} className="font-bold text-[#0B5FB4] flex items-center gap-2">Xem tất cả <ArrowRight size={16}/></button></div><div className="grid lg:grid-cols-3 gap-5">{(publishedPrograms.length?publishedPrograms:[{id:'p1',title:'Giáo dục & Đào tạo',summary:'Các hoạt động học tập và phát triển năng lực.',categoryLabel:'Chương trình',imageUrl:''},{id:'p2',title:'Phát triển Người trẻ',summary:'Không gian trải nghiệm và rèn luyện cho người trẻ.',categoryLabel:'Hoạt động',imageUrl:''},{id:'p3',title:'Tình nguyện & Cộng đồng',summary:'Các hoạt động cộng đồng thiết thực.',categoryLabel:'Cộng đồng',imageUrl:''}] as any[]).map((p:any)=><article key={p.id} className="rounded-[26px] overflow-hidden bg-white border border-slate-200"><div className="h-48 bg-gradient-to-br from-sky-100 via-blue-50 to-slate-100">{p.imageUrl&&<img src={p.imageUrl} alt="" className="w-full h-full object-cover"/>}</div><div className="p-6"><div className="text-[11px] uppercase tracking-[.14em] font-black text-[#0B5FB4]">{p.categoryLabel||'Hoạt động'}</div><h3 className="mt-3 text-xl font-extrabold">{p.title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{p.summary}</p></div></article>)}</div></div></section>

    <section className="py-20 lg:py-24"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid lg:grid-cols-2 gap-8 items-start"><div><div className="text-xs font-black tracking-[.18em] uppercase text-[#0B5FB4]">Đơn vị trực thuộc</div><h2 className="mt-3 text-4xl font-black tracking-[-.04em]">Hệ sinh thái hoạt động chuyên môn</h2><p className="mt-4 text-slate-500 leading-7">Các đơn vị trực thuộc được giới thiệu bằng tên, logo, lĩnh vực, hoạt động và thông tin liên hệ riêng.</p></div><div className="space-y-4">{publishedUnits.map((u:any)=><article key={u.id} className="rounded-2xl border border-slate-200 p-5 flex gap-4 items-center"><div className="w-16 h-16 rounded-2xl bg-white border border-slate-200 grid place-items-center overflow-hidden">{u.code==='SFEC'?<img src="/brand/the-sky-first-english-club.png" className="w-full h-full object-contain"/>:u.code==='NHN'?<img src="/brand/nha-han-ngu.jpg" className="w-full h-full object-contain"/>:<Building2/>}</div><div><h3 className="font-extrabold text-lg">{u.name}</h3><p className="text-sm text-slate-500 mt-1">{u.tagline}</p></div></article>)}</div></div></div></section>

    <section className="py-6"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="rounded-[30px] bg-[#0B5FB4] text-white p-8 lg:p-10 grid lg:grid-cols-[1fr_.8fr] gap-8 items-center"><div><div className="text-xs uppercase tracking-[.18em] text-sky-200 font-black">Xác thực thông tin</div><h2 className="mt-3 text-4xl font-black">Tra cứu Giấy chứng nhận</h2><p className="mt-4 text-sky-100 leading-7">Kiểm tra thông tin giấy chứng nhận được ghi nhận trong hệ thống Sky First Network.</p></div><button onClick={()=>onNavigate('certificate')} className="justify-self-start lg:justify-self-end px-5 py-3 rounded-xl bg-white text-[#071B3A] font-bold flex items-center gap-2"><Award size={18}/> Mở trang tra cứu</button></div></div></section>

    <section className="py-20"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid lg:grid-cols-[.7fr_1.3fr] gap-10"><div><div className="text-xs font-black tracking-[.18em] uppercase text-[#0B5FB4]">06 giá trị cốt lõi</div><h2 className="mt-3 text-4xl font-black tracking-[-.04em]">Nguyên tắc định hướng cách mạng lưới vận hành.</h2></div><div className="grid sm:grid-cols-2 gap-3">{values.map((v,i)=><div key={v} className="rounded-2xl border border-slate-200 p-5"><div className="text-xs font-black text-[#0B5FB4]">0{i+1}</div><h3 className="mt-5 font-extrabold text-lg">{v}</h3></div>)}</div></div></div></section>

    <section className="py-20 bg-[#F5F8FC]"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex justify-between items-end gap-5 mb-8"><div><div className="text-xs font-black tracking-[.18em] uppercase text-[#0B5FB4]">Tin tức & hoạt động</div><h2 className="mt-3 text-4xl font-black">Cập nhật từ mạng lưới</h2></div><button onClick={()=>onNavigate('news')} className="font-bold text-[#0B5FB4]">Xem tin tức</button></div><div className="grid lg:grid-cols-3 gap-5">{publishedNews.length?publishedNews.map((n:any)=><article key={n.id} className="rounded-2xl bg-white border border-slate-200 overflow-hidden"><div className="h-40 bg-slate-200">{n.imageUrl&&<img src={n.imageUrl} alt="" className="w-full h-full object-cover"/>}</div><div className="p-5"><div className="text-xs text-slate-400">{n.date}</div><h3 className="mt-2 font-extrabold text-lg">{n.title}</h3><p className="mt-2 text-sm text-slate-500 leading-6">{n.summary}</p></div></article>):<div className="lg:col-span-3 rounded-2xl border border-dashed border-slate-300 p-8 text-slate-500">Chưa có bài viết công khai. Nội dung mới sẽ hiển thị tại đây sau khi được xuất bản.</div>}</div></div></section>

    <section className="py-16"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="rounded-[30px] border border-slate-200 p-8 lg:p-10 flex flex-col lg:flex-row lg:items-center justify-between gap-8"><div className="flex gap-4"><ShieldCheck className="text-[#0B5FB4] shrink-0"/><div><h2 className="text-2xl font-black">Thông tin minh bạch</h2><p className="mt-2 text-slate-500 max-w-3xl leading-7">Sky First Network hiện được vận hành như một mạng lưới độc lập về tổ chức và định hướng hoạt động, nhưng hiện chưa có tư cách pháp lý độc lập.</p></div></div><button onClick={()=>onNavigate('about')} className="shrink-0 px-5 py-3 rounded-xl border border-slate-200 font-bold">Tìm hiểu thêm</button></div></div></section>
  </main>;
};
