import React from 'react';
import { ArrowRight, GraduationCap, Users, HeartHandshake, Network, Megaphone, Building2, ShieldCheck } from 'lucide-react';
import { PageRoute } from '../types';
import { useDataContext } from '../context/DataContext';

interface HomePageProps { onNavigate: (page: PageRoute) => void; }
type Key='hero'|'direction'|'pillars'|'programs'|'units'|'certificate'|'values'|'news'|'transparency';
const DEFAULT_ORDER:Key[]=['hero','direction','pillars','programs','units','certificate','values','news','transparency'];

export const HomePage: React.FC<HomePageProps> = ({ onNavigate }) => {
  const { programs, networkUnits, newsArticles, siteConfig, corePillars } = useDataContext();
  const publishedPrograms=programs.filter(p=>p.isPublished!==false).slice(0,3);
  const publishedUnits=networkUnits.filter(u=>u.isPublished!==false).slice(0,2);
  const publishedNews=newsArticles.filter(n=>n.isPublished!==false).slice(0,3);
  const visible=siteConfig.homeSections||{};
  const saved=(siteConfig.homeSectionOrder||[]).filter((x):x is Key=>DEFAULT_ORDER.includes(x as Key));
  const order=[...saved,...DEFAULT_ORDER.filter(x=>!saved.includes(x))];
  const pillarIcons=[GraduationCap,Users,HeartHandshake,Network,Megaphone];
  const pillars=corePillars.slice(0,5).map((p,i)=>[p.title,p.shortDesc,pillarIcons[i]||GraduationCap] as const);
  const values=siteConfig.coreValues||[];

  const section:Record<Key,React.ReactNode>={
    hero:<section className="relative overflow-hidden bg-[#071B3A] text-white"><div className="absolute inset-0 opacity-20" style={{backgroundImage:'radial-gradient(circle at 15% 20%, #30b6ff 0, transparent 28%), radial-gradient(circle at 80% 15%, #2563eb 0, transparent 24%)'}}/><div className="relative max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-20 lg:py-28"><div className="max-w-4xl"><div className="inline-flex rounded-full border border-sky-300/25 bg-white/5 px-4 py-2 text-xs font-bold uppercase tracking-[.16em] text-sky-200">{siteConfig.heroBadge}</div><h1 className="mt-6 text-5xl sm:text-6xl lg:text-7xl font-black tracking-[-.05em] leading-[1.02]">{siteConfig.heroHeading}</h1><p className="mt-7 max-w-2xl text-base sm:text-lg leading-8 text-slate-300">{siteConfig.heroSubtext}</p><div className="mt-8 flex flex-wrap gap-3"><button onClick={()=>navigateUrl(siteConfig.heroButton1Url||'/about',onNavigate)} className="px-5 py-3 rounded-xl bg-white text-[#071B3A] font-bold flex items-center gap-2">{siteConfig.heroButton1Text||'Khám phá mạng lưới'} <ArrowRight size={17}/></button><button onClick={()=>navigateUrl(siteConfig.heroButton2Url||'/join',onNavigate)} className="px-5 py-3 rounded-xl border border-white/20 bg-white/5 font-bold">{siteConfig.heroButton2Text||'Tham gia cùng chúng tôi'}</button></div></div></div></section>,
    direction:<section className="py-10 bg-[#071B3A] text-white"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="rounded-[28px] border border-white/15 bg-white/[.06] p-6 lg:p-8 grid lg:grid-cols-[.35fr_.65fr] gap-6"><div><div className="text-xs uppercase tracking-[.18em] text-sky-200 font-bold">{siteConfig.directionLabel||'Định hướng 2026'}</div><div className="mt-5 grid grid-cols-2 gap-3"><div className="rounded-2xl bg-white/8 p-5"><div className="text-3xl font-black">{siteConfig.directionPillarsCount||'05'}</div><div className="text-xs text-slate-300 mt-1">{siteConfig.directionPillarsLabel||'Trụ cột hoạt động'}</div></div><div className="rounded-2xl bg-white/8 p-5"><div className="text-3xl font-black">{siteConfig.directionValuesCount||'06'}</div><div className="text-xs text-slate-300 mt-1">{siteConfig.directionValuesLabel||'Giá trị cốt lõi'}</div></div></div></div><div className="text-lg leading-8 text-slate-300 self-center">{siteConfig.directionText}</div></div></div></section>,
    pillars:<section className="py-20 lg:py-24"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid lg:grid-cols-[.6fr_1.4fr] gap-10 mb-10"><div className="text-xs font-black tracking-[.18em] uppercase text-[#0B5FB4]">{siteConfig.pillarsHeading}</div><h2 className="text-4xl lg:text-5xl font-black tracking-[-.04em] text-slate-950">{siteConfig.pillarsSubtext}</h2></div><div className="grid md:grid-cols-2 xl:grid-cols-5 border border-slate-200 rounded-[28px] overflow-hidden">{pillars.map(([title,desc,Icon],i)=><div key={String(title)} className="p-6 min-h-[270px] flex flex-col border-b xl:border-b-0 xl:border-r last:border-r-0 border-slate-200"><div className="flex justify-between text-xs text-slate-400"><span>0{i+1}</span><span className="w-10 h-10 rounded-xl bg-sky-50 text-[#0B5FB4] grid place-items-center"><Icon size={20}/></span></div><div className="mt-auto"><h3 className="font-extrabold text-lg">{title}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{desc}</p></div></div>)}</div></div></section>,
    programs:<section className="py-20 bg-[#F5F8FC]"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex justify-between gap-5 mb-8"><div><div className="text-xs font-black tracking-[.18em] uppercase text-[#0B5FB4]">{siteConfig.programsLabel}</div><h2 className="mt-3 text-4xl font-black tracking-[-.035em]">{siteConfig.programsHeading}</h2></div><button onClick={()=>onNavigate('programs')} className="font-bold text-[#0B5FB4] flex items-center gap-2">Xem tất cả <ArrowRight size={16}/></button></div><div className="grid lg:grid-cols-3 gap-5">{publishedPrograms.length===0?<div className="lg:col-span-3 rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-slate-500">Chưa có chương trình được công bố.</div>:publishedPrograms.map((p:any)=><article key={p.id} className="rounded-[26px] overflow-hidden bg-white border border-slate-200"><div className="h-48 bg-slate-100">{p.imageUrl&&<img src={p.imageUrl} alt="" className="w-full h-full object-cover"/>}</div><div className="p-6"><div className="text-[11px] uppercase tracking-[.14em] font-black text-[#0B5FB4]">{p.categoryLabel||'Hoạt động'}</div><h3 className="mt-3 text-xl font-extrabold">{p.title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{p.summary}</p></div></article>)}</div></div></section>,
    units:<section className="py-20 lg:py-24"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="grid lg:grid-cols-2 gap-8 items-start"><div><div className="text-xs font-black tracking-[.18em] uppercase text-[#0B5FB4]">{siteConfig.unitsLabel}</div><h2 className="mt-3 text-4xl font-black tracking-[-.04em]">{siteConfig.unitsHeading}</h2><p className="mt-4 text-slate-500 leading-7">{siteConfig.unitsIntro}</p></div><div className="space-y-4">{publishedUnits.map((u:any)=><article key={u.id} className="rounded-2xl border border-slate-200 p-5 flex gap-4 items-center"><div className="w-16 h-16 rounded-2xl bg-white border border-slate-200 grid place-items-center overflow-hidden">{u.code==='SFEC'?<img src="/brand/the-sky-first-english-club.png" className="w-full h-full object-contain"/>:u.code==='NHN'?<img src="/brand/nha-han-ngu.jpg" className="w-full h-full object-contain"/>:<Building2/>}</div><div><h3 className="font-extrabold text-lg">{u.name}</h3><p className="text-sm text-slate-500 mt-1">{u.tagline}</p></div></article>)}</div></div></div></section>,
    certificate:<section className="py-6"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="rounded-[30px] bg-[#0B5FB4] text-white p-8 lg:p-10 grid lg:grid-cols-[1fr_.8fr] gap-8 items-center"><div><div className="text-xs uppercase tracking-[.18em] text-sky-200 font-black">{siteConfig.certificateLabel}</div><h2 className="mt-3 text-4xl font-black">{siteConfig.certificateHeading}</h2><p className="mt-4 text-sky-100 leading-7">{siteConfig.certificateText}</p></div><button onClick={()=>navigateUrl(siteConfig.certificateButtonUrl||'/certificate',onNavigate)} className="justify-self-start lg:justify-self-end px-5 py-3 rounded-xl bg-white text-[#0B5FB4] font-bold flex items-center gap-2">{siteConfig.certificateButtonText||'Mở trang tra cứu'} <ArrowRight size={17}/></button></div></div></section>,
    values:<section className="py-20"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="text-xs font-black tracking-[.18em] uppercase text-[#0B5FB4]">{siteConfig.valuesLabel}</div><h2 className="mt-3 text-4xl font-black tracking-[-.04em]">{siteConfig.valuesHeading}</h2><div className="mt-8 grid sm:grid-cols-2 lg:grid-cols-3 gap-4">{values.map((v,i)=><div key={v.name} className="rounded-2xl border border-slate-200 p-6"><div className="text-xs font-black text-[#0B5FB4]">0{i+1}</div><h3 className="mt-4 text-xl font-extrabold">{v.name}</h3><p className="mt-2 text-sm leading-6 text-slate-500">{v.desc}</p></div>)}</div></div></section>,
    news:<section className="py-20 bg-[#F5F8FC]"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="flex justify-between gap-5 mb-8"><div><div className="text-xs font-black tracking-[.18em] uppercase text-[#0B5FB4]">{siteConfig.newsLabel}</div><h2 className="mt-3 text-4xl font-black">{siteConfig.newsHeading}</h2></div><button onClick={()=>onNavigate('news')} className="font-bold text-[#0B5FB4]">Xem tin tức</button></div><div className="grid lg:grid-cols-3 gap-5">{publishedNews.length===0?<div className="lg:col-span-3 rounded-2xl border border-dashed border-slate-300 bg-white p-8 text-slate-500">Chưa có tin tức được công bố.</div>:publishedNews.map((n:any)=><article key={n.id} className="rounded-2xl bg-white border border-slate-200 p-6"><div className="text-xs text-slate-400">{n.publishedAt}</div><h3 className="mt-3 text-xl font-extrabold">{n.title}</h3><p className="mt-3 text-sm leading-6 text-slate-500">{n.summary}</p></article>)}</div></div></section>,
    transparency:<section className="py-14"><div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8"><div className="rounded-[28px] border border-slate-200 p-8 flex flex-col lg:flex-row lg:items-center gap-6"><div className="w-12 h-12 rounded-2xl bg-sky-50 text-[#0B5FB4] grid place-items-center"><ShieldCheck/></div><div className="flex-1"><h2 className="text-2xl font-black">{siteConfig.transparencyHeading}</h2><p className="mt-2 text-slate-500 leading-7">{siteConfig.transparencyText}</p></div><button onClick={()=>window.location.href=siteConfig.transparencyButtonUrl||'/phap-ly-minh-bach'} className="px-5 py-3 rounded-xl border border-slate-200 font-bold">{siteConfig.transparencyButtonText||'Tìm hiểu thêm'}</button></div></div></section>,
  };
  return <main className="bg-white">{order.filter(k=>visible[k]!==false).map(k=><React.Fragment key={k}>{section[k]}</React.Fragment>)}</main>;
};

function navigateUrl(url:string,onNavigate:(page:PageRoute)=>void){
  const map:Record<string,PageRoute>={'/':'home','/about':'about','/join':'join','/certificate':'certificate','/programs':'programs','/units':'units','/news':'news','/contact':'contact'};
  if(map[url]) onNavigate(map[url]); else window.location.href=url;
}
