import React from 'react';
import { Mail, Phone, Facebook, Instagram, Users, Globe2, GraduationCap, HeartHandshake, MessageCircle, Link as LinkIcon, ShieldCheck, ArrowUpRight } from 'lucide-react';
import { PageRoute } from '../types';
import { useDataContext } from '../context/DataContext';
interface FooterProps { onNavigate: (page: PageRoute, slug?: string) => void; }
const iconMap:Record<string,any>={mail:Mail,phone:Phone,facebook:Facebook,instagram:Instagram,message:MessageCircle,users:Users,heart:HeartHandshake,globe:Globe2,graduation:GraduationCap,link:LinkIcon};
function resolveInternal(url:string):{page:PageRoute;slug?:string}|null{if(!url.startsWith('/'))return null;if(url==='/')return{page:'home'};const parts=url.replace(/^\/+|\/+$/g,'').split('/');if((parts[0]==='page'||parts[0]==='trang')&&parts[1])return{page:'custom-page',slug:decodeURIComponent(parts.slice(1).join('/'))};const direct:Record<string,PageRoute>={home:'home',about:'about',programs:'programs',units:'units',news:'news',certificate:'certificate',sponsor:'sponsor',join:'join',contact:'contact',admin:'admin'};if(direct[parts[0]])return{page:direct[parts[0]]};return{page:'custom-page',slug:decodeURIComponent(parts.join('/'))}}
export const Footer:React.FC<FooterProps>=({onNavigate})=>{const {siteConfig}=useDataContext();const contacts=siteConfig.footerContacts||[],portals=siteConfig.footerPortals||[],legal=siteConfig.footerLegalLinks||[];const org=(siteConfig.organizationInfo||[]).filter((x:any)=>x.visible!==false&&String(x.value||'').trim());const groups=siteConfig.navigationGroups||[];const intro=groups.find((g:any)=>g.label==='Giới thiệu')?.items?.slice(0,6)||[];const join=groups.find((g:any)=>g.label==='Tham gia')?.items?.slice(0,4)||[];const go=(url:string,e:React.MouseEvent)=>{const t=resolveInternal(url);if(!t)return;e.preventDefault();onNavigate(t.page,t.slug);window.scrollTo({top:0,behavior:'smooth'})};const LinkRow=({label,url}:{label:string,url:string})=><a href={url} onClick={e=>resolveInternal(url)?go(url,e):undefined} target={!resolveInternal(url)&&/^https?:/i.test(url)?'_blank':undefined} rel={!resolveInternal(url)&&/^https?:/i.test(url)?'noopener noreferrer':undefined} className="text-[13px] leading-5 text-slate-400 transition hover:text-white">{label}</a>;
return <footer className="bg-[#06152F] text-slate-300"><div className="mx-auto max-w-[1380px] px-4 py-9 sm:px-6 lg:px-8 lg:py-10">
{org.length>0&&<section className="mb-8 rounded-[22px] border border-white/10 bg-white/[.035] p-5"><div className="mb-4 flex items-center gap-2 text-[11px] font-black uppercase tracking-[.16em] text-sky-300"><ShieldCheck size={14}/>Thông tin Mạng lưới</div><div className="grid gap-x-8 gap-y-3 sm:grid-cols-2 xl:grid-cols-4">{org.map((x:any,i:number)=><div key={`${x.label}-${i}`} className="min-w-0"><div className="text-[10px] font-bold uppercase tracking-wider text-slate-500">{x.label}</div>{x.url?<a href={x.url} className="mt-1 block break-words text-[13px] font-semibold text-slate-200 hover:text-sky-300">{x.value}</a>:<div className="mt-1 break-words text-[13px] font-semibold text-slate-200">{x.value}</div>}</div>)}</div></section>}
<div className="grid gap-8 sm:grid-cols-2 xl:grid-cols-[1.15fr_.8fr_.9fr_1.05fr]"><div><img src={siteConfig.logoUrl||'/brand/sky-first-network-web.png'} alt={siteConfig.siteName||'Sky First Network'} className="h-12 w-auto max-w-[190px] object-contain object-left"/><p className="mt-3 max-w-sm text-[13px] leading-6 text-slate-400">{siteConfig.footerAboutText||siteConfig.siteDescription}</p></div><div><h4 className="mb-3 text-xs font-black uppercase tracking-[.12em] text-white">Khám phá</h4><div className="grid gap-2">{intro.map((x:any)=><LinkRow key={x.label} label={x.label} url={x.slug?`/${x.slug}`:`/${x.page}`}/>)}</div></div><div><h4 className="mb-3 text-xs font-black uppercase tracking-[.12em] text-white">Tham gia & Tra cứu</h4><div className="grid gap-2">{join.map((x:any)=><LinkRow key={x.label} label={x.label} url={x.slug?`/${x.slug}`:`/${x.page}`}/>) }<LinkRow label="Xác thực GCN" url="/certificate"/><LinkRow label="Tài liệu công khai" url="/tai-lieu-cong-khai"/></div></div><div><h4 className="mb-3 text-xs font-black uppercase tracking-[.12em] text-white">Liên hệ</h4><div className="grid gap-2">{contacts.filter((x:any)=>x.url?.startsWith('mailto:')||x.url?.startsWith('tel:')).slice(0,5).map((x:any)=>{const Icon=iconMap[x.icon||'link']||LinkIcon;return <a key={x.label+x.url} href={x.url} className="flex items-center gap-2.5 rounded-xl px-1 py-1 text-slate-400 hover:text-white"><span className="grid h-7 w-7 shrink-0 place-items-center rounded-lg bg-white/5 text-sky-300"><Icon size={13}/></span><span className="min-w-0"><b className="block text-[11px] text-slate-200">{x.label}</b><span className="block break-all text-[11px]">{x.value}</span></span></a>})}</div></div></div>
{portals.length>0&&<section className="mt-8 border-t border-white/10 pt-6"><h4 className="mb-4 text-xs font-black uppercase tracking-[.12em] text-white">Hệ sinh thái số Sky First</h4><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-5">{portals.map((x:any)=>{const Icon=iconMap[x.icon||'link']||LinkIcon;return <a key={x.label+x.url} href={x.url} target="_blank" rel="noopener noreferrer" className="group flex min-h-[92px] items-start gap-3 rounded-2xl border border-white/10 bg-white/[.035] p-3.5 transition hover:-translate-y-0.5 hover:border-sky-400/30 hover:bg-white/[.06]"><span className="grid h-9 w-9 shrink-0 place-items-center rounded-xl bg-sky-400/10 text-sky-300"><Icon size={16}/></span><span className="min-w-0 flex-1"><b className="block text-[12px] leading-5 text-white">{x.label}</b><span className="mt-1 block text-[10px] leading-4 text-slate-500">{x.description||'Truy cập nền tảng Sky First'}</span></span><ArrowUpRight size={13} className="shrink-0 text-slate-600 group-hover:text-sky-300"/></a>})}</div></section>}
<div className="mt-7 flex flex-col gap-3 border-t border-white/10 pt-5 text-[11px] text-slate-500 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-x-4 gap-y-2">{legal.map((x:any)=><LinkRow key={x.label+x.url} label={x.label} url={x.url}/>)}</div><p>{siteConfig.footerCopyright||'© 2026. Mạng lưới Giáo dục & Phát triển Cộng đồng Sky First.'}</p></div></div></footer>};
