import React,{useRef,useState} from 'react';
import {Image as ImageIcon,Check,X,AlertCircle,UploadCloud,Loader2} from 'lucide-react';
import {adminApi} from '../lib/adminApi';

interface Props{label?:string;value?:string;onChange:(url:string)=>void;helperText?:string;category?:string;placeholder?:string}
export const ImageUrlInput:React.FC<Props>=({label='Ảnh',value='',onChange,helperText})=>{
 const inputRef=useRef<HTMLInputElement|null>(null); const [uploading,setUploading]=useState(false); const [error,setError]=useState('');
 const upload=async(file:File)=>{setUploading(true);setError('');try{const f=new FormData();f.append('file',file);const d=await adminApi('/api/media/upload',{method:'POST',body:f});if(!d?.url)throw new Error('Không nhận được tệp sau khi tải lên.');onChange(d.url)}catch(e:any){setError(e?.message||'Không thể tải ảnh.')}finally{setUploading(false);if(inputRef.current)inputRef.current.value=''}};
 return <div className="space-y-2"><div className="flex items-center justify-between gap-3"><label className="text-xs font-bold text-slate-700">{label}</label><div className="flex gap-2"><input ref={inputRef} type="file" multiple={false} accept="image/jpeg,image/png,image/webp,image/gif,image/avif,image/svg+xml" className="hidden" onChange={e=>{const f=e.target.files?.[0];if(f)void upload(f)}}/><button type="button" disabled={uploading} onClick={()=>inputRef.current?.click()} className="inline-flex items-center gap-1.5 rounded-lg border border-sky-200 bg-sky-50 px-3 py-1.5 text-[11px] font-extrabold text-sky-700 disabled:opacity-60">{uploading?<Loader2 size={13} className="animate-spin"/>:<UploadCloud size={13}/>} {uploading?'Đang tải...':value?'Thay ảnh':'Tải ảnh lên'}</button>{value&&<button type="button" onClick={()=>onChange('')} className="rounded-lg border px-2 text-slate-500" title="Gỡ ảnh"><X size={14}/></button>}</div></div>{error&&<div className="flex gap-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-[11px] font-semibold text-rose-700"><AlertCircle size={14}/>{error}</div>}{value?<div className="rounded-xl border bg-slate-50 p-2 flex items-center gap-3"><div className="max-w-[180px] max-h-28 overflow-hidden rounded-lg bg-white border"><img src={value} alt="Xem trước" className="max-w-full max-h-28 w-auto h-auto object-contain"/></div><div className="text-[11px] text-emerald-700 font-bold flex items-center gap-1"><Check size={13}/>Ảnh đã sẵn sàng</div></div>:<div className="flex gap-2 text-[11px] text-slate-500"><ImageIcon size={13}/><span>{helperText||'Tải ảnh trực tiếp; hệ thống giữ nguyên tỷ lệ ảnh gốc. Hỗ trợ JPG, PNG, WebP, GIF, AVIF và SVG.'}</span></div>}</div>
};
