import React,{useEffect,useState} from 'react';
import {X,Search,Loader2,Image as ImageIcon} from 'lucide-react';
import {listMedia,MediaItem} from '../lib/mediaApi';
export const MediaPicker:React.FC<{onSelect:(item:MediaItem)=>void;onClose:()=>void;imageOnly?:boolean}>=({onSelect,onClose,imageOnly=true})=>{
 const [items,setItems]=useState<MediaItem[]>([]),[cursor,setCursor]=useState<string|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[query,setQuery]=useState('');
 const load=async(next?:string)=>{setBusy(true);setError('');try{const d=await listMedia(next);setItems(prev=>next?[...prev,...d.items]:d.items);setCursor(d.cursor)}catch(e){setError(e instanceof Error?e.message:'Không tải được thư viện.')}finally{setBusy(false)}};
 useEffect(()=>{void load();const previous=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=previous}},[]);
 useEffect(()=>{const escape=(e:KeyboardEvent)=>{if(e.key==='Escape')onClose()};document.addEventListener('keydown',escape);return()=>document.removeEventListener('keydown',escape)},[onClose]);
 const visible=items.filter(x=>(!imageOnly||x.type.startsWith('image/'))&&(x.name+' '+(x.alt||'')).toLocaleLowerCase('vi').includes(query.toLocaleLowerCase('vi')));
 return <div className="fixed inset-0 z-[200] bg-slate-950/60 p-3 sm:p-7 flex items-center justify-center" onClick={e=>{if(e.target===e.currentTarget)onClose()}}><section role="dialog" aria-modal="true" aria-label="Chọn ảnh từ thư viện" className="bg-white w-full max-w-5xl rounded-2xl max-h-[88vh] overflow-hidden flex flex-col shadow-2xl"><header className="p-5 border-b flex justify-between gap-4"><div><h3 className="font-bold text-lg">Thư viện hình ảnh</h3><p className="text-xs text-slate-500">Chọn một ảnh đã tải lên để tái sử dụng.</p></div><button type="button" aria-label="Đóng thư viện" onClick={onClose}><X size={22}/></button></header><div className="p-5 overflow-auto"><label className="flex border rounded-xl gap-3 items-center p-3 mb-5"><Search size={17}/><input autoFocus aria-label="Tìm ảnh" className="outline-none flex-1 text-sm" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Tìm theo tên hoặc mô tả ảnh…"/></label>{error&&<p role="alert" className="text-rose-700 text-sm mb-4">{error}</p>}<div className="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">{visible.map(item=><button type="button" key={item.key} aria-label={`Chọn ${item.name}`} onClick={()=>onSelect(item)} className="rounded-xl border overflow-hidden text-left hover:border-sky-500 focus:ring-2 focus:ring-sky-500"><div className="aspect-square bg-slate-50 p-2">{item.type.startsWith('image/')?<img src={item.url} alt={item.alt||item.name} loading="lazy" className="w-full h-full object-contain"/>:<ImageIcon className="m-auto"/>}</div><p className="p-2 text-[11px] truncate">{item.name}</p></button>)}</div>{!busy&&!visible.length&&<p className="p-8 text-center text-sm text-slate-500">Chưa có ảnh phù hợp. Tải ảnh tại mục Thư viện hoặc trường ảnh của bài viết.</p>}{busy?<p className="py-5 flex justify-center items-center gap-2"><Loader2 className="animate-spin" size={18}/>Đang tải…</p>:cursor&&<button type="button" onClick={()=>void load(cursor)} className="mt-5 px-4 py-2 border rounded-lg text-sm">Tải thêm ảnh</button>}</div></section></div>;
};
