import { requireAdminToken, json } from '../../_auth.js';
const clean=(v,n=500)=>String(v??'').trim().slice(0,n);
const parse=(v,f)=>{try{return JSON.parse(v||'')}catch{return f}};
const code=()=>`SFN-${new Date().toISOString().slice(0,10).replace(/-/g,'')}-${crypto.randomUUID().slice(0,6).toUpperCase()}`;
async function ensure(c){await c.env.DB.batch([
 c.env.DB.prepare(`CREATE TABLE IF NOT EXISTS website_forms(id TEXT PRIMARY KEY,slug TEXT NOT NULL UNIQUE,title TEXT NOT NULL,description TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'draft',fields_json TEXT NOT NULL DEFAULT '[]',settings_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 c.env.DB.prepare(`CREATE TABLE IF NOT EXISTS website_form_submissions(id TEXT PRIMARY KEY,form_id TEXT NOT NULL,application_code TEXT NOT NULL UNIQUE,applicant_name TEXT,applicant_email TEXT,answers_json TEXT NOT NULL DEFAULT '{}',status TEXT NOT NULL DEFAULT 'received',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)`),
 c.env.DB.prepare(`CREATE TABLE IF NOT EXISTS website_form_rate(rate_key TEXT PRIMARY KEY,count INTEGER NOT NULL DEFAULT 0,window_start TEXT NOT NULL)`)
]);}
function safeForm(r){return {...r,fields:parse(r.fields_json,[]),settings:parse(r.settings_json,{}),fields_json:undefined,settings_json:undefined}}
function isOpen(row){const s=parse(row.settings_json,{}),now=Date.now(),open=s.openAt?new Date(s.openAt).getTime():0,close=s.closeAt?new Date(s.closeAt).getTime():0;return row.status==='open'&&(!open||now>=open)&&(!close||now<=close)}
function validateValue(f,v){const type=String(f.type||'text');if(v==null||v==='')return true;if(type==='email')return /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(String(v));if(type==='url')return /^https?:\/\//i.test(String(v));if(type==='number'||type==='rating')return Number.isFinite(Number(v));if(type==='phone')return /^[+\d][\d\s().-]{6,20}$/.test(String(v));if(type==='date'||type==='datetime'||type==='time')return !Number.isNaN(Date.parse(type==='time'?`1970-01-01T${v}`:String(v)));if(type==='consent')return v===true||v==='true'||v===1;return true}
async function rateLimit(c,formId){const ip=clean(c.request.headers.get('CF-Connecting-IP')||'unknown',80);const key=`${formId}:${ip}`;const row=await c.env.DB.prepare('SELECT count,window_start FROM website_form_rate WHERE rate_key=?').bind(key).first();const now=Date.now();if(!row||now-new Date(row.window_start).getTime()>3600000){await c.env.DB.prepare('INSERT OR REPLACE INTO website_form_rate(rate_key,count,window_start) VALUES(?,1,?)').bind(key,new Date().toISOString()).run();return true}if(Number(row.count)>=10)return false;await c.env.DB.prepare('UPDATE website_form_rate SET count=count+1 WHERE rate_key=?').bind(key).run();return true}
const uploads={'image/jpeg':'jpg','image/png':'png','image/webp':'webp','application/pdf':'pdf'};
function validUpload(bytes,type){if(type==='image/jpeg')return bytes[0]===255&&bytes[1]===216&&bytes[2]===255;if(type==='image/png')return [137,80,78,71,13,10,26,10].every((n,i)=>bytes[i]===n);if(type==='image/webp'){const t=new TextDecoder().decode(bytes.slice(0,16));return t.slice(0,4)==='RIFF'&&t.slice(8,12)==='WEBP'}if(type==='application/pdf')return new TextDecoder().decode(bytes.slice(0,5))==='%PDF-';return false}
async function uploadField(c,u){if(!c.env.MEDIA)return json({ok:false,error:'Kho tệp chưa sẵn sàng.'},{status:503});const formId=clean(u.searchParams.get('formId'),100),fieldId=clean(u.searchParams.get('fieldId'),100);const row=await c.env.DB.prepare('SELECT * FROM website_forms WHERE id=? LIMIT 1').bind(formId).first();if(!row||!isOpen(row))return json({ok:false,error:'Biểu mẫu không tồn tại hoặc đã đóng.'},{status:404});const field=parse(row.fields_json,[]).find(f=>String(f.id)===fieldId);if(!field||!['file','image','signature'].includes(String(field.type)))return json({ok:false,error:'Trường tải tệp không hợp lệ.'},{status:400});const fd=await c.request.formData();const file=fd.get('file');if(!(file instanceof File)||!uploads[file.type]||!file.size||file.size>5*1024*1024)return json({ok:false,error:'Tệp không hợp lệ. Hỗ trợ JPG, PNG, WebP, PDF tối đa 5MB.'},{status:400});if(field.type==='signature'&&file.type!=='image/png')return json({ok:false,error:'Chữ ký phải ở định dạng PNG.'},{status:400});const bytes=new Uint8Array(await file.arrayBuffer());if(!validUpload(bytes,file.type))return json({ok:false,error:'Nội dung tệp không khớp định dạng.'},{status:400});const key=`form-submissions/${formId}/${crypto.randomUUID()}.${uploads[file.type]}`;await c.env.MEDIA.put(key,bytes,{httpMetadata:{contentType:file.type,cacheControl:'private, max-age=0'},customMetadata:{formId,fieldId,uploadedAt:new Date().toISOString()}});return json({ok:true,url:`/media/${key}`})}

export async function onRequestGet(c){await ensure(c);const u=new URL(c.request.url),admin=u.searchParams.get('admin')==='1',lookup=clean(u.searchParams.get('lookup'),80),slug=clean(u.searchParams.get('slug'),120),submissions=u.searchParams.get('submissions')==='1';
 if(admin){const denied=await requireAdminToken(c);if(denied)return denied;if(submissions){const formId=clean(u.searchParams.get('formId'),100);const q=formId?c.env.DB.prepare('SELECT * FROM website_form_submissions WHERE form_id=? ORDER BY created_at DESC LIMIT 500').bind(formId):c.env.DB.prepare('SELECT * FROM website_form_submissions ORDER BY created_at DESC LIMIT 500');const r=await q.all();return json({ok:true,items:(r.results||[]).map(x=>({...x,answers:parse(x.answers_json,{})}))})}const r=await c.env.DB.prepare('SELECT * FROM website_forms ORDER BY updated_at DESC').all();return json({ok:true,items:(r.results||[]).map(safeForm)})}
 if(lookup){const r=await c.env.DB.prepare(`SELECT s.application_code,s.status,s.created_at,s.updated_at,f.title form_title FROM website_form_submissions s JOIN website_forms f ON f.id=s.form_id WHERE upper(s.application_code)=upper(?) LIMIT 1`).bind(lookup).first();return r?json({ok:true,item:r},{headers:{'cache-control':'no-store'}}):json({ok:false,error:'Không tìm thấy hồ sơ với mã này.'},{status:404})}
 if(slug){const r=await c.env.DB.prepare("SELECT * FROM website_forms WHERE slug=? AND status='open' LIMIT 1").bind(slug).first();return r&&isOpen(r)?json({ok:true,item:safeForm(r)},{headers:{'cache-control':'public, max-age=15, s-maxage=30'}}):json({ok:false,error:'Biểu mẫu không tồn tại, chưa mở hoặc đã hết hạn.'},{status:404})}
 const r=await c.env.DB.prepare("SELECT id,slug,title,description,status,settings_json,updated_at FROM website_forms WHERE status='open' ORDER BY updated_at DESC").all();return json({ok:true,items:(r.results||[]).filter(isOpen).map(safeForm)},{headers:{'cache-control':'public, max-age=30, s-maxage=120'}});
}
export async function onRequestPost(c){await ensure(c);const u=new URL(c.request.url);if(u.searchParams.get('upload')==='1')return uploadField(c,u);const admin=u.searchParams.get('admin')==='1';const b=await c.request.json().catch(()=>({}));
 if(admin){const denied=await requireAdminToken(c);if(denied)return denied;const id=clean(b.id,100)||crypto.randomUUID(),slug=clean(b.slug,120).toLowerCase().replace(/[^a-z0-9-]+/g,'-').replace(/^-|-$/g,''),title=clean(b.title,240);if(!slug||!title)return json({ok:false,error:'Tên và slug là bắt buộc.'},{status:400});const fields=Array.isArray(b.fields)?b.fields:[];const settings=b.settings&&typeof b.settings==='object'?b.settings:{};await c.env.DB.prepare(`INSERT INTO website_forms(id,slug,title,description,status,fields_json,settings_json,updated_at) VALUES(?,?,?,?,?,?,?,CURRENT_TIMESTAMP) ON CONFLICT(id) DO UPDATE SET slug=excluded.slug,title=excluded.title,description=excluded.description,status=excluded.status,fields_json=excluded.fields_json,settings_json=excluded.settings_json,updated_at=CURRENT_TIMESTAMP`).bind(id,slug,title,clean(b.description,4000),['draft','open','closed'].includes(b.status)?b.status:'draft',JSON.stringify(fields),JSON.stringify(settings)).run();return json({ok:true,id})}
 const form=await c.env.DB.prepare("SELECT * FROM website_forms WHERE id=? AND status='open' LIMIT 1").bind(clean(b.formId,100)).first();if(!form||!isOpen(form))return json({ok:false,error:'Biểu mẫu không tồn tại, chưa mở hoặc đã đóng.'},{status:404});if(!(await rateLimit(c,form.id)))return json({ok:false,error:'Bạn đã gửi quá nhiều hồ sơ trong thời gian ngắn. Vui lòng thử lại sau.'},{status:429});const fields=parse(form.fields_json,[]),settings=parse(form.settings_json,{}),answers=b.answers&&typeof b.answers==='object'?b.answers:{};
 for(const f of fields){const v=answers[f.id];if(f.required&&(v==null||v===''||(Array.isArray(v)&&!v.length)||f.type==='consent'&&v!==true))return json({ok:false,error:`Vui lòng hoàn thành: ${f.label||f.id}`},{status:400});if(!validateValue(f,v))return json({ok:false,error:`Dữ liệu chưa đúng định dạng: ${f.label||f.id}`},{status:400})}
 if(settings.maxSubmissions){const r=await c.env.DB.prepare('SELECT COUNT(*) n FROM website_form_submissions WHERE form_id=?').bind(form.id).first();if(Number(r?.n||0)>=Number(settings.maxSubmissions))return json({ok:false,error:'Biểu mẫu đã đạt giới hạn hồ sơ tiếp nhận.'},{status:409})}
 const applicationCode=code(),id=crypto.randomUUID();const name=clean(answers.full_name||answers.name||answers.ho_ten,160),email=clean(answers.email,180);await c.env.DB.prepare(`INSERT INTO website_form_submissions(id,form_id,application_code,applicant_name,applicant_email,answers_json,status,created_at,updated_at) VALUES(?,?,?,?,?,?,'received',CURRENT_TIMESTAMP,CURRENT_TIMESTAMP)`).bind(id,form.id,applicationCode,name,email,JSON.stringify(answers)).run();return json({ok:true,applicationCode,status:'received',message:clean(settings.confirmationMessage,500)||'Hồ sơ đã được tiếp nhận.'})}
export async function onRequestPatch(c){await ensure(c);const denied=await requireAdminToken(c);if(denied)return denied;const b=await c.request.json().catch(()=>({}));if(b.submissionId){const status=clean(b.status,30);if(!['received','reviewing','accepted','rejected','closed'].includes(status))return json({ok:false,error:'Trạng thái không hợp lệ.'},{status:400});await c.env.DB.prepare('UPDATE website_form_submissions SET status=?,updated_at=CURRENT_TIMESTAMP WHERE id=?').bind(status,clean(b.submissionId,100)).run();return json({ok:true})}return json({ok:false,error:'Yêu cầu không hợp lệ.'},{status:400})}
export async function onRequestDelete(c){await ensure(c);const denied=await requireAdminToken(c);if(denied)return denied;const b=await c.request.json().catch(()=>({}));if(b.submissionId){await c.env.DB.prepare('DELETE FROM website_form_submissions WHERE id=?').bind(clean(b.submissionId,100)).run();return json({ok:true})}const id=clean(b.id,100);if(!id)return json({ok:false,error:'Thiếu id.'},{status:400});await c.env.DB.batch([c.env.DB.prepare('DELETE FROM website_form_submissions WHERE form_id=?').bind(id),c.env.DB.prepare('DELETE FROM website_forms WHERE id=?').bind(id)]);return json({ok:true})}
